### ISSUE TITLE
Non project administrator users are unable to edit feature description

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1016]
Users with the `CREATE_FEATURE` permission should be able to edit the description of a feature. Note that this bug exists on both the edit feature and the create feature slide outs. 

<img width="1375" alt="Screenshot 2022-04-26 at 14 00 16" src="https://user-images.githubusercontent.com/14089968/165305566-c3082a39-fd69-42ac-b56f-869dc5908193.png">

**Comment by matthewelwell** [comment]
Issue here is that editing a feature allows you to edit the multivariate feature options which can affect flag evaluation in other environments. As such, we need to keep the edit feature endpoint as project admin only for now. 

Solution will be to split out the multivariate feature option management into a separate option. This is also somewhat tied to the solution needed to allow multivariate percentage splits for segment overrides.

**Comment by kyle-ssg** [comment]
Should this mean staging allows a put to projects/${projectId}/features/${flag.id} as a CREATE_FEATURE user? I still seem to get a 403

**Comment by matthewelwell** [comment]
Curl?

**Comment by matthewelwell** [comment]
Curl?

**Comment by kyle-ssg** [comment]
Sorry, that's my mistake, I can't replicate it now, I must have been looking at the staging dashboard. Can create a new mv-option as CREATE_USER as well as save settings, other envs get 0 as the mv value with this change which is great 👍

**Comment by kyle-ssg** [comment]
This is live under the flag segment_mv_percentages
