### ISSUE TITLE
Editing tags on a feature as a user

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1017]
There are a couple of issues here: 

 1. We only allow project admins to create tags in a project - is this valid?
 2. We show the 'tags' label to all users but only project administrators are able to apply them to a feature so regular users end up with an empty form section (see screenshot below). 

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/14089968/165307065-68dbb3f4-13ca-4f46-a79d-386a148eeda5.png">

The first thing to do is certainly to allow users with the CREATE_FEATURE permission to apply tags to their features (but not create or remove them from the project). Then the next question is whether we should remove the restriction that only project administrators should be able to edit tags for a project.

**Comment by matthewelwell** [comment]
Similarly to #1016, the issue with editing these values on a feature is more difficult, however, feature create should allow the user to add tags.

**Comment by kyle-ssg** [comment]
This is live under the flag segment_mv_percentages
