### ISSUE TITLE
Regular environment users cannot view identities

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1018]
To reproduce: 

 1. Create an organisation user that has 'VIEW_PROJECT' and 'VIEW_ENVIRONMENT' permissions on a given project / environment
 2. As this user, click on the 'users' option from the left hand menu
 3. Click on one of the users

Expected behaviour: TBD
Actual behaviour: Loading spinner shows and page never loads. 403 in console from attempting following request: 

```
GET https://api.flagsmith.com/api/v1/environments/:key/identities/:id/
```

**Comment by matthewelwell** [comment]
Options here are: 

1. Open up permissions to allow users to retrieve identities
2. Prevent non environment admin users from clicking through on a specific identity

I am in favour of option 1 which would make this a minor BE change, however, we may need to be wary of what else is available on the identity page that will need stricter permissioning.

**Comment by matthewelwell** [comment]
> we may need to be wary of what else is available on the identity page that will need stricter permissioning.

I've tested this now and the key things that are exposed are: 

 1. It's possible to edit segments from this screen (should this really be possible for any user?)
 2. Users that access this screen can edit traits for that user - is this the expected behaviour?

**Comment by matthewelwell** [comment]
Discussed with @kyle-ssg. BE needs to add a new 'MANAGE_IDENTITIES' permission to determine whether a user can view an identity and edit traits. Managing their feature states will be controlled by the existing UPDATE_FEATURE_STATE permission. Segments will be read only on this screen for all users.

**Comment by matthewelwell** [comment]
@kyle-ssg BE is on staging now. 

As part of this change, could you please move to using the endpoints at `/api/v1/environments/:key/identities/:id/traits` rather than relying on the SDK endpoints for trait management?

**Comment by kyle-ssg** [comment]
Use admin endpoint for traits - https://github.com/Flagsmith/flagsmith/issues/1053 Tracking here

Todo:

- [x] Make Segments Read Only when viewing a user
- [x] Use MANAGE_IDENTITIES to determine if they can view a user
- [ ] BE, allow MANAGE_IDENTITIES to hit /trait-keys

**Comment by kyle-ssg** [comment]
@matthewelwell All looks good except I think we need to use that permission for /trait-keys

**Comment by kyle-ssg** [comment]
Frontend live under flag **manage_identities_permission**

**Comment by matthewelwell** [comment]
@kyle-ssg just double checking here - we removed the call to `trait-keys` right?
