### ISSUE TITLE
Be able to link to individual Segments or Flags

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1032]
It makes it much harder to describe what flag is being used in a feature from a given pull request without being able to link to the Segment/Flag in question directly. 

When the flag/segment modal is being shown, we should modify the browser URL and allow deeplinking into that content.

**Comment by kyle-ssg** [comment]
Feature
https://app.flagsmith.com/project/12/environment/4vfqhypYjcPoGGu8ByrBaj/features?feature=19941

User Feature 
https://app.flagsmith.com/project/12/environment/4vfqhypYjcPoGGu8ByrBaj/users/kyle%40solidstategroup.com/39584?flag=4eyes

Segment
https://app.flagsmith.com/project/12/environment/4vfqhypYjcPoGGu8ByrBaj/segments?id=2051

**Comment by darraghmckay** [comment]
Amazing @kyle-ssg ! 🎉🎉
