### ISSUE TITLE
Identity overrides do not appear to be being written to Edge Identities

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1034]
Flagsmith on Flagsmith migrator has been run - Identities were correctly copied. 

If I find an account in e.g Flagsmith Website Project, Staging Env, and override a flag value (e.g. the butter_bar), the values are being persisted in Core but not in edge.

**Comment by gagantrivedi** [comment]
Caused by https://flagsmith.slack.com/archives/CTF0THS2D/p1651256947051229 i.e:  edge_identities feature flag  was turned off
