### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jamesgeddes** [SolidStateGroup/bullet-train-api#1044]
Would Flagsmith consider using an [OSI license](https://opensource.org/licenses)?

**Comment by dabeeeenster** [comment]
Hi James - we have an explicit license defined as per https://github.com/Flagsmith/flagsmith/blob/main/LICENSE.md

**Comment by jamesgeddes** [comment]
Hi @dabeeeenster - yes I did see that, however, I could not see it listed as an OSI approved license. The [OSI FAQ](https://opensource.org/faq#:~:text=releases%20appropriate%20software.-,Can%20I%20call%20my%20program%20%22Open%20Source%22%20even%20if%20I%20don%27t%20use%20an%20approved%20license%3F,-Please%20don%27t%20do) says,

> **Can I call my program "Open Source" even if I don't use an approved license?**
> Please don't do that. If you call it "Open Source" without using an approved license, you will confuse people. This is not merely a theoretical concern — we have seen this confusion happen in the past, and it's part of the reason we have a formal [license approval process](https://opensource.org/approval). See also our page on [license proliferation](https://opensource.org/proliferation) for why this is a problem.

At [Geek.Zone](https://github.com/GeekZoneHQ), we are eager to use FOSS tools, and as an OSI member we just want to ensure that we are upholding the recognised standards 😄

**Comment by dabeeeenster** [comment]
The license is BSD 3 but with the following addition: 

> All content that resides under the "api/permissions" directory of this repository, if that directory exists, is licensed under the license defined in "api/permissions/LICENSE.md".

**Comment by jamesgeddes** [comment]
Is api/permissions/LICENSE.md an OSI approved license also?

**Comment by dabeeeenster** [comment]
No - that's a proprietary license.
