### ISSUE TITLE
Feature name missing from Change Request page

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1045]
![image](https://user-images.githubusercontent.com/173290/166452053-221d163a-2302-4ec2-bb31-dceac77055f3.png)

Name of feature completely missing here.

Needs to be provided by API.

**Comment by gagantrivedi** [comment]
Feature is part of the response
![image](https://user-images.githubusercontent.com/18366226/167062927-83d2eecc-2700-4d2e-8e69-0f54daa08d75.png)

**Comment by matthewelwell** [comment]
@gagantrivedi looks like we're only providing the id. Perhaps that's sufficient for @kyle-ssg (?) but I wonder if we can provide the name here?

**Comment by gagantrivedi** [comment]
We can  if needed, let's see what @kyle-ssg  thinks

**Comment by kyle-ssg** [comment]
Yeah, I guess I can do another get to the feature state once I get that. Though I won't be able to do that for the list view.

**Comment by kyle-ssg** [comment]
Actually, since this is paged I'm inclined to just do this for the list view too for now. We can reopen and optimise ticket later.
