### ISSUE TITLE
Change Requests should work with zero required approvals

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1046]
Currently its impossible to set an Environment with Change Requests enabled but zero required approvals. It would be good to support this configuration. 

Front End currently makes this impossible in the UI, so this needs changing; when you set Required approvals to zero it automatically disables Change Requests altogether.

We also need to check that the Back End supports this setup too.

**Comment by kyle-ssg** [comment]
If we want to do this I think we'd need a new field on the backend to indicate they want the ability to submit a change request. Also this would mean we'd need to set this to true for any live environments that have minimum number of approvals. cc @matthewelwell

**Comment by gagantrivedi** [comment]
> If we want to do this I think we'd need a new field on the backend to indicate they want the ability to submit a change request. Also this would mean we'd need to set this to true for any live environments that have minimum number of approvals. cc @matthewelwell

Wait, I don't think I understand this - backend already supports 0 required approvals, right? @matthewelwell

**Comment by matthewelwell** [comment]
Yeah, the BE assumes that change requests are enabled if `minimum_change_request_approvals` is not null so 0 is a perfectly valid option here. Let me know if this isn't sufficient @kyle-ssg.

**Comment by kyle-ssg** [comment]
Can I send null too as a way to disable change requests @matthewelwell ?

**Comment by kyle-ssg** [comment]
Ah ok yep can send null to disable them it looks like!
