### ISSUE TITLE
Set up Github Action to test dependencies for security vulnerabilities

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1060]
Run the action every 24h and raise a failure if there are security vulnerabilities

## For Front End

https://docs.npmjs.com/cli/v8/commands/npm-audit

## For API

???

**Comment by kyle-ssg** [comment]
FE done https://github.com/Flagsmith/flagsmith/runs/6357115629?check_suite_focus=true
https://github.com/Flagsmith/flagsmith/blob/main/.github/workflows/frontend-audit.yml
