### ISSUE TITLE
Frontend: Feature override show incorrect value(for edge identity) on identity detail page

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#1061]
Steps to reproduce(on production/ Flagsmith Website project/ staging environment):  
1. disable any feature that is by default enabled for any identity
2. It shows up as enabled 
PS: https://flagsmith.slack.com/archives/CTF0THS2D/p1651746530372279

**Comment by kyle-ssg** [comment]
Based on our conversation I think this could be backend, assign back if you think not.
