### ISSUE TITLE
Email enumeration possible

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1089]
The registration function can be used to determine whether a provided email address is known to the system or not.

The application should not provide any details about the existence of a user account within the responses which are sent to the client during the account registration process.

**Comment by gagantrivedi** [comment]
So throw an abstract 400?

**Comment by matthewelwell** [comment]
Could we add a backoff delay based on IP address or something? I guess people could just rotate around IP addresses. 

I don't know how useful it would be to just mask the error message itself though.

**Comment by gagantrivedi** [comment]
> I don't know how useful it would be to just mask the error message itself though.

Yeah, I don't think it will be of much use
