### ISSUE TITLE
Scheduled flag list should show the time the flag is scheduled to change

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1117]
![image](https://user-images.githubusercontent.com/173290/168553083-72b8e215-6b5f-4fed-b9b8-788c359108b0.png)

Currently you have to go into every change request to see when the schedule is

**Comment by dabeeeenster** [comment]
Ah this might be a dupe of #1031

**Comment by kyle-ssg** [comment]
Yep
