### ISSUE TITLE
Show list of flags being overridden by a segment

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1122]
**Needs API work first**

In the segment swipe out, add a third tab, `Feature Flags` that lists all the flags that the segment is currently associated with (i.e. there's an override set).

This list would need to show flag name and the environments that it overriding that flag for. 

<img width="766" alt="image" src="https://user-images.githubusercontent.com/173290/168780466-7981a67f-ba04-4c18-91bd-c31cbeb99994.png">

**Comment by kyle-ssg** [comment]
Makes sense, great idea. I imagine we'd have an endpoint that returns a similar data structure to /environments/{environment_api_key}/featurestates/, 

![image](https://user-images.githubusercontent.com/8608314/169066310-ee1463f5-1d22-4ccd-9642-970f5261ee3c.png)

Maybe we'd even have reuse same endpoint and send segment as a param?

I think either let me know that this would be the case @gagantrivedi @matthewelwell and reassign to me and I can work on that assumption, or reassign to me when the API is ready.

**Comment by kyle-ssg** [comment]
![image](https://user-images.githubusercontent.com/8608314/179565150-1dff419b-0588-4b64-8a50-3255e7277847.png)

Clicking a feature takes them to the segment override tab of that feature in a new tab for the selected environment 

![image](https://user-images.githubusercontent.com/8608314/179565255-cad5963f-3ab2-4a4d-9514-30d956b12695.png)

**Comment by kyle-ssg** [comment]
Live under flag segment_associated_features
