### ISSUE TITLE
Creating a new project when in the context of an Edge project hangs

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1123]
When you try to create a new project when viewing the dashboard in the context of an 'Edge' project (i.e. a project that has `use_edge_identities: true`), clicking the 'Create Project' button hangs and never completes. 

Likely this is due to the following network request failure: 

<img width="830" alt="image" src="https://user-images.githubusercontent.com/14089968/168796290-93a460e9-977d-4ca6-96ed-fda6022e87ad.png">

The FE should use the value of `use_edge_identities` on the response from the `POST` request to create the project to determine which endpoint to hit to create the initial identity.

**Comment by kyle-ssg** [comment]
Yep makes sense, it thought the current "active" project was edge so it called the wrong endpoint.
