### ISSUE TITLE
Migrating identities for projects with small numbers of identities causes a 504

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1124]
e.g. I just migrated a project with only 10 identities and got a 504 error when the request timed out after 30s.

**Comment by matthewelwell** [comment]
Screen recording: https://photos.app.goo.gl/CrejL5VPYLuN2Bzs9

**Comment by dabeeeenster** [comment]
Going to move to ecs task processor
