### ISSUE TITLE
Feature segment priority has no effect on edge evaluations

### ISSUE THREAD

**Issue by kyle-ssg** [SolidStateGroup/bullet-train-api#1134]
![image](https://user-images.githubusercontent.com/8608314/169060331-9c367121-4690-4db1-a077-79ec37224ace.png)

Given the above segment override priority order, I'd expect a user belonging to all 3 segments to use the override fro seg_1

![image](https://user-images.githubusercontent.com/8608314/169060270-49d9fde2-7986-45a0-93bf-57700f816d71.png)

**Comment by gagantrivedi** [comment]
Okay, So I believe there is something off with this page - How do you paint this page (the feature one)? Are you maybe hitting core endpoint to get the value of override? But the traits only exists on edge or something?

**Comment by kyle-ssg** [comment]
Just to confirm this too, hitting edge and the user definitely has the traits - it's all working except it's choosing the wrong segment override
