### ISSUE TITLE
Free plan environments can get into a state where they have 0 CR approvals rather than null

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1136]
Free plans should never allow a value other than `null` in the `Minimum change request approvals` value for the environment.

We have a user who has 3 environments on a free plan where the value is 0, which breaks the platform.

Need to:

- [x] not allow this int to be set unless the project is part of a scale up or enterprise plan
- [ ] figure out what endpoint is causing this value to be set incorrectly and fix

**Comment by matthewelwell** [comment]
I've added logic on the API side to prevent free plan users from setting this value. Left to confirm on the FE how this is being set (although probably not that important since it shouldn't affect anything now anyway).

**Comment by kyle-ssg** [comment]
From a frontend perspective, I can't see any way to do this, the only thing that sets minimum_change_request_approvals to 0 is turning on the switch for 4 eyes. For some reason this was changed for all payment tiers however I've just changed this back to scaleup.
