### ISSUE TITLE
Unable to login in to django admin (self-hosted)

### ISSUE THREAD

**Issue by Vrtak-CZ** [SolidStateGroup/bullet-train-api#1139]
Hi guys, I'm not able to login into Django Admin. I fill up the email and password (same as I use for the frontend) and hit the login button and I got redirected back to login screen without any message.

There is message from logs:

```
flagsmith-api-85495d7c75-fb958 django.security.SuspiciousSession WARNING  Session data corrupted
```

Some info:
I have `ENABLE_ADMIN_ACCESS_USER_PASS` set to `True` also I have checked in database that my user has `is_superuser` set to `TRUE` and `is_staff` is also set to `TRUE`.
Version: `flagsmith/flagsmith:2.23.3`

**Comment by gagantrivedi** [comment]
Hi @Vrtak-CZ  did you change the value of `SECRET_KEY` recently ? 
can you create a new superuser and login with that and see if that works?

**Comment by Vrtak-CZ** [comment]
Hi @gagantrivedi I did not have `SECRET_KEY` set because we are using helm chart `0.8` but i saw changes in `0.9` and upgraded to this version and now all works as expected.

Thank you.
