### ISSUE TITLE
Add IS_SET and IS_NOT_SET segment operators

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1145]
These operators would not need a 'value' to compare against and would just check whether a given trait is set or not. 

SDK Implementation tracker: 

 - [x] python - gagan
 - [x] nodejs - edison
 - [x] java - matt
 - [x] .NET - matt
 - [x] rust - gagan
 - [x] ruby - matt
 - [x] go - gagan
 - [x] elixir - micael
 - [x] PHP - matt

**Comment by dabeeeenster** [comment]
We also need to implement this logic in the SDKs
