### ISSUE TITLE
Incorrect message in modal when removing integration

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1146]
To reproduce: 

 1. Add an integration from the integrations page
 2. Hit the delete button next to the newly added integration

<img width="614" alt="image" src="https://user-images.githubusercontent.com/14089968/170016616-c199b59b-6f18-49ce-ae09-4a2a4a813c75.png">

**Comment by kyle-ssg** [comment]
Done
