### ISSUE TITLE
Ability for users to "unlock" new features that we release in the interface. 

### ISSUE THREAD

**Issue by malthauser** [SolidStateGroup/bullet-train-api#1170]
I'd love to have a mechanism where we can release new features and have our customers "self-toggle" the features on. This would be an amazing user experience and way for them to "unwrap" the great things we ship for them while reinforcing the concept of release management.

**Comment by malthauser** [comment]
@kyle-ssg let me know if you have questions about this. me and @dabeeeenster are excited about this idea!

**Comment by kyle-ssg** [comment]
Building under the feature flag **beta_features** which is enabled for internal users, reopen with any feedback
