### ISSUE TITLE
Ability to create custom UTM Parameters for Referral partners

### ISSUE THREAD

**Issue by malthauser** [SolidStateGroup/bullet-train-api#1171]
I'd like to start a referral program for people that refer customers to us. To do this, I need a way to create custom UTM Parameters that store cookies in our front-end and back-end systems. This will allow us to track the customers that they refer and pay them a revenue share.

**Comment by kyle-ssg** [comment]
Completed as part of https://github.com/Flagsmith/flagsmith/pull/3095
