### ISSUE TITLE
Add filtering by tag, showing features that match ALL tags

### ISSUE THREAD

**Issue by Jaribeau** [SolidStateGroup/bullet-train-api#1173]
**Use-case**

When using tags to filter features, it would be great to be able to display only tags that match **all** of the selected tags.

Example: Given the available tags: temporary, permanent, config, release, permissions; it would be useful to be able to display only features that have both permanent and config tags.

**Current Behaviour**

- Selecting filter by permanent and config tags would display all features that have either the permanent tag, config tag, or both.

**Desired Behaviour**

- Selecting filter by permanent and config flags would display only features 

- Perhaps with the options to toggle between the two behaviours.

**Comment by kyle-ssg** [comment]
Thanks for the suggestion 🚀 , I've adjusted the behaviour to match what you'd described, for now we won't add a toggle to switch to OR but this may change based on feedback.

**Comment by kyle-ssg** [comment]
@Jaribeau your company looks really awesome by the way, so cool! If you wanted to, we'd love to do a case study on how you're using Flagsmith?

**Comment by Jaribeau** [comment]
Awesome, thanks for the quick change! Makes our workflow smoother 🎉

We actually spun things down at Demine Robotics at the beginning of the year -- just noticed I hadn't updated my github profile, but thanks! 

I'm at Smartex now, where we're also using Flagsmith for some cool embedded stuff (this time for waste/pollution reduction in the textile industry). Already planning with Ben on doing a case study 👍
