### ISSUE TITLE
Slack integration does not include information about source environment.

### ISSUE THREAD

**Issue by Jaribeau** [SolidStateGroup/bullet-train-api#1180]
According to the slack integration on Flagsmith, there should be a tag with the source environment:

"Sends messages to Slack when flags are created, updated and removed. Logs are tagged with the environment they came from e.g. production. [View docs](https://docs.flagsmith.com/integrations/slack/)"

But changes for both environments look the same.
<img width="494" alt="image" src="https://user-images.githubusercontent.com/6071465/172396303-7b886a62-ef8d-4d08-91d7-a59f1a52852c.png">

Additionally -- when a change is made via a change request, it does not trigger a slack message.

**Comment by dabeeeenster** [comment]
Thanks for the report - we're looking into this now.

**Comment by matthewelwell** [comment]
```python
    @staticmethod
    def generate_event_data(log: str, email: str, environment_name: str) -> dict:
        return {
            "text": f"{log} by user {email}",
            "title": "Flagsmith Feature Flag Event",
            "tags": [f"env:{environment_name}"],
        }

    def _track_event(self, event: dict) -> None:
        self._client.chat_postMessage(channel=self.channel_id, text=event["text"])
```

@gagantrivedi it looks like the `SlackWrapper` class is generating the event with additional attributes `title` and `tags` but neither are actually used when calling the `chat_postMessage` method. Is there a reason we did this? 

@Jaribeau I'm going to create a separate issue regarding the lack of Slack message when a change request is committed.
