### ISSUE TITLE
Receiving 405 for deleting the Multi-Variate Flags value 

### ISSUE THREAD

**Issue by ram2104** [SolidStateGroup/bullet-train-api#1189]
I was exploring the open-source version of the flagsmith. While exploring I created a feature flag with a 'multi-variate' value. 
I was trying to delete one of the existing variation values from the admin UI. 

When I'm triggering the deletion request it's failing with an HTTP error-code 405 which is of the 'DELETE' type.  How can I delete the existing variation data? 

Attaching the screenshot for reference.

<img width="1000" alt="Screenshot 2022-06-09 at 18 35 53" src="https://user-images.githubusercontent.com/19301579/172854874-241c94bb-3a91-43ae-84e3-f88cce3744a4.png">
<img width="638" alt="Screenshot 2022-06-09 at 18 37 20" src="https://user-images.githubusercontent.com/19301579/172854884-9d66037a-9d27-4368-8da8-157bceea661f.png">

**Comment by matthewelwell** [comment]
@kyle-ssg I think this would be resolved if you add the trailing slash to the delete request. At the moment, it's trying to redirect to `DELETE /api/v1/projects/1/features/3/mv-options/6/` and perhaps being routed elsewhere by the node proxy that's used in the open source version?

**Comment by kyle-ssg** [comment]
This would make sense since the SaaS version doesn't experience this, this has been adjusted now, please feel free to reopen if this doesn't solve your issue @ram2104

**Comment by ram2104** [comment]
It's working now wow. Thanks, @kyle-ssg  & @matthewelwell
