### ISSUE TITLE
Flag Search should be server side. 

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1200]
- [x] Implement flag search API
- [x] Migrate the front end to use the above API
- [x] Ability to filter flags by 1 or more tags
- [x] Ability to filter flags by if they are untagged
- [x] Ability to filter flags by if they are archived

**Comment by matthewelwell** [comment]
API is done here: #1201.

**Comment by matthewelwell** [comment]
@kyle-ssg API is done and on staging (although the E2E tests failed - looking into those now)

**Comment by matthewelwell** [comment]
E2E tests passed on retry. Could have been a collision perhaps.

**Comment by matthewelwell** [comment]
I'll add the following: 

```
tags=1,2,3  # leave blank for untagged, exclude parameter for all
is_archived=true|false
```
