### ISSUE TITLE
Segment User Sampling is not consistent

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1202]
Ask @dabeeeenster for Saas acct details if needed

It looks like the FE is not making requests for each identity on subsequent paging of the component. The first time the component loads, it makes 10x calls to `https://api.flagsmith.com/api/v1/projects/<project id>/segments/?identity=<identity ID>` to get the segment on/off data for each identity on that page. Looking on page 2, 3 etc there are no calls to that endpoint - there's only 1 call to `https://api.flagsmith.com/api/v1/environments/<env id>/identities/?page=2&page_size=10` to the next 10 users, but none of them are sampled.

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/commit/64a7a708dfd66765360b2d9ee5d30a4371f3c792
