### ISSUE TITLE
Front-End: UI is not showing 0 for multivariate value

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#1208]
Steps to reproduce
1. override mv value for any feature with 0

![image](https://user-images.githubusercontent.com/18366226/173752802-36cff34d-50e9-4d1e-aecb-f82e86c3d7f3.png)

2. Refresh the page
![image](https://user-images.githubusercontent.com/18366226/173752915-3fc4b445-d7b7-4bf5-a497-d4474352ed18.png)

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/commit/7fd57a52e55b3bc2aae29e877a3304bd98beb216
