### ISSUE TITLE
Get multiple identities with api do not work

### ISSUE THREAD

**Issue by davidsoderberg** [SolidStateGroup/bullet-train-api#1210]
Hi when I try to get multiple identities I get that identifier is missing... Is this a bug or should it be like that? If it is okay how can I get a list of them?

**Comment by davidsoderberg** [comment]
In the api docs it has tag `identities_list` if that helps 😄

**Comment by dabeeeenster** [comment]
Can you provide a `curl` command or similar that you are running that you would expect to work?

**Comment by davidsoderberg** [comment]
```
 public async getFlagsForUsers() {
    const res = await fetch(`${this.url}/identities/`, {
      method: 'get',
      headers: this.getHeaders(),
    });
    return await res.json();
  }

  private getHeaders(): Headers {
    const headers = new Headers();
    headers.append('X-Environment-Key', 'key');
    headers.append('Content-Type', 'application/json');
    return headers;
  }
```

**Comment by davidsoderberg** [comment]
I tried to do the same thing from your swagger page and did get the same error

**Comment by dabeeeenster** [comment]
Hi @davidsoderberg - is this in reference to a particular SDK?

**Comment by davidsoderberg** [comment]
No it is my own code... but it is working for other api endpoints I use...

**Comment by dabeeeenster** [comment]
Sorry - I'm not clear what language this is! Can you confirm?

**Comment by davidsoderberg** [comment]
It is Javascript...

**Comment by dabeeeenster** [comment]
Ah - so you're not using one of our SDKs?

**Comment by davidsoderberg** [comment]
No

**Comment by kyle-ssg** [comment]
Hey @davidsoderberg, the identities endpoint is part of the Admin API and you're trying to hit it with an SDK environment key.

If you wish to use non-SDK endpoints you can just use your API token found at https://app.flagsmith.com/account

**Comment by kyle-ssg** [comment]
Also, with these admin APIs the header for tokens is actually

```
authorization: Token <TOKEN>

```

**Comment by dabeeeenster** [comment]
https://docs.flagsmith.com/clients/rest#private-endpoints

**Comment by davidsoderberg** [comment]
@kyle-ssg I have already tried that on this page https://api.flagsmith.com/api/v1/docs/ and still get the same error

**Comment by matthewelwell** [comment]
Sorry @davidsoderberg, I think there's some confusion here. I can confirm that the authentication method you're using should work here (assuming `this.url` looks something like `api.flagsmith.com/api/v1`). 

The request to this endpoint requires a GET parameter of `identifier`, however which I think you're missing? 

So you should be able to make a request along the lines of: 

```bash
curl --location --request GET 'https://api.flagsmith.com/api/v1/identities/?identifier=mattelwell' \
--header 'X-Environment-Key: <your key>'
``` 

This will retrieve the flags and traits for your identity so you should get a response that looks something like: 

```json
{
  "flags": [{...}],
  "traits": [{...}]
```

**Comment by davidsoderberg** [comment]
Okay @matthewelwell so I can not get an list of those for all identities?

**Comment by davidsoderberg** [comment]
Like the swagger docs says...

**Comment by davidsoderberg** [comment]
<img width="1452" alt="Screenshot 2022-06-16 at 10 48 26" src="https://user-images.githubusercontent.com/2233092/174031692-b97713d7-d294-4ee4-99fe-892b28dac3e1.png">

**Comment by matthewelwell** [comment]
I'm afraid you can't at the moment, no. Not through our SDK endpoints at least. There are some endpoints that allow you to build this information up through our Rest API that Ben linked the documentation for above but there is no single endpoint to get this information for multiple identities. 

I will update our swagger documentation to ensure it is correct, I apologise for that.

**Comment by davidsoderberg** [comment]
Okay maybe worth looking into 😄 thanks for your help
