### ISSUE TITLE
Implement self-service Edge API Migrator

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1215]
- [x] Add button in project settings to migrate from Core to Edge if the project is currently set to Core - should check migration status and report on "Not started", "In Progress", "Complete". We also want to be able to control whether this shows behind a flag, as we want to hide it for some folk with a lot of Identities. 
- [x] Implement trigger API with auth - only org admins can press the button
- [x] Implement Read Migration Status endpoint
- [x] Add copy in project settings with more info and links to docs
- [x] Update docs to show self service button

**Comment by gagantrivedi** [comment]
Back-end API https://github.com/Flagsmith/flagsmith/pull/1268

**Comment by gagantrivedi** [comment]
![image](https://user-images.githubusercontent.com/18366226/177985487-df4fdddd-c85e-4786-bf73-4060feacc9b9.png)
API endpoint to trigger migration

**Comment by gagantrivedi** [comment]
/projects/ now include migration status
![image](https://user-images.githubusercontent.com/18366226/177985649-b15dd02d-8fb9-472b-8f60-9edcc6dc32e2.png)

**Comment by kyle-ssg** [comment]
![image](https://user-images.githubusercontent.com/8608314/178003229-b918b9a0-a5a7-4337-bcb3-734f2d0c648f.png)
![image](https://user-images.githubusercontent.com/8608314/178003277-16f9af71-548a-44e1-b5b6-713deef86705.png)
![image](https://user-images.githubusercontent.com/8608314/178003758-13847553-6733-45cf-9282-dd206d4a1a04.png)

**Comment by kyle-ssg** [comment]
![image](https://user-images.githubusercontent.com/8608314/178003994-75a47cd2-024b-49ea-b37b-1ab7c64f6bc2.png)
![image](https://user-images.githubusercontent.com/8608314/178004030-603ee9be-09a5-4349-a8d1-5b5407429924.png)
