### ISSUE TITLE
Show me code drop down is cut off on identities list page

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1217]
![image](https://user-images.githubusercontent.com/173290/174608313-c2f002dc-8506-418c-bd4d-1b56ab9c3243.png)

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/commit/848c36edb7ae43f30bf63d0a5f224189c4f0a6bc
