### ISSUE TITLE
Environments are not cached when using server keys

### ISSUE THREAD

**Issue by maticomp** [SolidStateGroup/bullet-train-api#1226]
Hello!

When retrieving flags, two steps are happening. First, environment is retrieved and verified against the API key. Then, flags are retrieved and returned.

Both steps are now cached in LocMem in Flagship, but whereas with `CACHE_FLAGS_SECONDS` set to a non-zero value flags are cached properly, caching environment data doesn't always work. It does, when authenticating using main environment API key. It doesn't when authenticating using server keys instead.

With heavy load, the underlying database is then hit hard, even though the environment retrieval is a relatively cheap query.

I pinpointed this to `environments/models.py:112`, 

```
    @classmethod
    def get_from_cache(cls, api_key):
            (...)
            environment = environment_cache.get(api_key)
            if not environment:
                (...)
                environment = (
                    (...)
                    .filter(Q(api_key=api_key) | Q(api_keys__key=api_key))
                    (...)
                )
                environment_cache.set(environment.api_key, environment, timeout=60)
```

Cache is checked against `api_key` supplied to the method, and if not found, retrieved based on `api_key` or `api_keys` collection that includes server keys. However, cache is _set_ with the main key only.

Is this an intentional behaviour I misunderstand or missed in the documentation? Or maybe the intention is for:

```
- environment_cache.set(environment.api_key, environment, timeout=60)
+ environment_cache.set(api_key, environment, timeout=60)
```

to cache all properly validated environments for a while?

Thanks!

**Comment by matthewelwell** [comment]
Hi @maticomp, 

Thanks for the very detailed issue report - really appreciate it. 

Your suggestion looks like what I would go with for sure. Do you want to submit a PR yourself? Otherwise, I can go ahead and do it. 

Thanks,
Matt

**Comment by maticomp** [comment]
@matthewelwell I'll be happy to do so next week. If that's too late, feel free to go ahead!

**Comment by matthewelwell** [comment]
Thanks @maticomp. I'll see how my day today goes and keep you posted here.
