### ISSUE TITLE
Identity overrides skip flags cache entirely

### ISSUE THREAD

**Issue by maticomp** [SolidStateGroup/bullet-train-api#1243]
Hello!

As part of looking why we've started hitting performance issues with our Flagsmith configuration, I'm digging more into how the flags engine work and why the cache we thought should keep the performance at bay isn't doing so.

In #1226 I stumbled upon environments not being cached, but now I noticed something bigger and also more impactful. 

Whereas `/flags/` for main environment flags use Django cache, if configured, identity overrides at `/identities/` don't.

The queries issued by identity overrides are also expensive, since they return not only the ovveride, but a reconciled value of base flags + overrides. 

This means that if we get all environment flags without overrides through `/flags/`, we can reliably hit the cache. But even with just a single overriden flag on top of dozens of unchanged ones, getting those through `/identities/` endpoint kills the performance.

Ideally, identity overrides could be also cached. However maybe a simpler solution would be to at least use the main flags cache to get the base values, and evaluate overrides on top of that?

Getting a single flag value as opposed to the full results is not helping either, since:

```
    def _get_single_feature_state_response(self, identity, feature_name):
        for feature_state in identity.get_all_feature_states():
```

this does a full evaluation of the identity-overriden environment either way. 

Correct me if I'm wrong, but my current understanding is that to be able to get correct values for all flags including identity overrides, I have to call `/identities/` endpoint, and thus I'm bound to miss the cache and retrieve the full environment without it. Maybe I'm missing some other way to just get the overrides?

Thanks!

**Comment by dabeeeenster** [comment]
There's not much benefit from caching Identity flags - normally they are just requested once and then not requested again for some time. They need to be computed every time on account of % splits, multivariate flag values or changes in Segment definitions. You could cache them then invalidate the cache every time the state of the Flagsmith Environment changes, but it is a lot of effort/complexity for little benefit. 

What sort of requests per second are you looking to serve? 

https://docs.flagsmith.com/clients/overview#remote-and-local-evaluation-modes might be helpful to you?

**Comment by maticomp** [comment]
We're aiming for handling 10-20 req/s for environments with ~50 flags of which ~10 are overriden, and the rest come always with default environment values. This is load that's easy to handle with adding just bit more hardware to the stack, but with in-memory cache we could easily coast with a very small resource usage for Flagsmith. Right now, the small-ish PostgreSQL cluster gets slightly choked by identity queries at this rate.

We're already using local evaluation on the server side, but as the documentation states:

> Identity overrides do not operate at all.

We're yet to restructure our code & flags structure to benefit from the suggested workaround with segments that are locally evaluated. That would definitely serve our purpose well, but is a solid overhead on top of the very simple solution with identity overrides. All segments in our case would contain a single identity.

Anyway, enhancing our use of local evaluation & properly caching flags on our end the is the route we are going to take if caching identity flags is not planned as a feature, as this will be immune to further traffic increase as opposed to just giving more beans to the database. At first, for the sake of simplicity, we opted for relying on Flagsmith and not optimizing our flag use too much, but that's obviously a mediocre approach on my end. 

I get that and appreciate your response!

**Comment by dabeeeenster** [comment]
Can you define "small-ish PostgreSQL cluster"?  A single 2gb AWS fargate instance can easily manage 20 rps - curious to know what the size of the DB is?

**Comment by dabeeeenster** [comment]
Going to close this for now!

**Comment by maticomp** [comment]
> Can you define "small-ish PostgreSQL cluster"? A single 2gb AWS fargate instance can easily manage 20 rps - curious to know what the size of the DB is?

I was using t3.micro for this particular case, and with 1GB of RAM (excessively small for a DB, I know - though my assumption was this is for rarely executed and subsequently cached queries) it was hitting memory bottlenecks when querying for identity overrides. Plain flags were never a problem, even under much higher load, even without the cache. 

Either way, I will go forward with changes on my end, let's keep this closed. Thanks!
