### ISSUE TITLE
Add configuration to environment to prevent clients from setting traits

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1249]
Add a configuration option on environments to prevent clients using the client key from setting traits. 

Note: this should default to allow to maintain current behaviour.

**Comment by matthewelwell** [comment]
API is in PR here: #1248

**Comment by matthewelwell** [comment]
@kyle-ssg you'll just need to pass `allow_client_traits` when creating / updating environments

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/1251#partial-pull-merging
