### ISSUE TITLE
Okta Integration

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1256]
Want to create an integration which is listed here: https://www.okta.com/integrations/

For now, we should focus on Single Sign-on only. User provisioning management can come at a later stage.

**Comment by riceyrice** [comment]
https://developer.okta.com/docs/guides/#publish-an-integration

![image](https://user-images.githubusercontent.com/12712166/201347984-db1777a0-7937-432f-bf29-996a4a84ed9a.png)

**Comment by riceyrice** [comment]
https://developer.okta.com/docs/guides/build-sso-integration/saml2/main/
