### ISSUE TITLE
Add POST identity endpoint that takes identifier string as opposed to internal ID

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1273]
Currently the Identity endpoints rely on the internal ID to reference the object in question. It would be helpful (particularly when running CI tests) to be able to manage these identities using their client-provided string identifier.

**Comment by gagantrivedi** [comment]
Fixed in https://github.com/Flagsmith/flagsmith/commit/d37a237db7ec36a565ddec857c40b4e19ab672bf
