### ISSUE TITLE
Add new permission for managing segments

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1298]
At the moment only project administrators are able to manage segments and segment rules. We should add a new permission to allow users to allow non-project admin users to manage segments.

**Comment by dabeeeenster** [comment]
Yep totally agree on this reqt.

**Comment by matthewelwell** [comment]
API is done for this. New project level permission called `"MANAGE_SEGMENTS"` will allow users to edit / create / delete segments.
