### ISSUE TITLE
Toggling a feature in Compare page affects the wrong feature

### ISSUE THREAD

**Issue by Jaribeau** [SolidStateGroup/bullet-train-api#1301]
⚠️ Toggling a flag from the Compare page toggles a different feature than the one selected.

Video of bug:
https://www.loom.com/share/1b98af1a94b84b9187e4c11a897a663c

**Comment by dabeeeenster** [comment]
Will get on this!

**Comment by kyle-ssg** [comment]
Hey, @Jaribeau - this should be sorted now. Please reopen if this isn't resolved for you.
