### ISSUE TITLE
Add "Identity Overrides" tab to the Feature modal that shows per-identity overrides. 

### ISSUE THREAD

**Issue by Jaribeau** [SolidStateGroup/bullet-train-api#1303]
Currently it is difficult to keep track of what user-based overrides exist for a given feature.

Similar to the Segment Overrides tab, having a User Overrides tab showing a list of users with an override active for that feature would make using user-overrides via the Flagsmith app a scalable option.

Our B2B use-case:
We most often segment users by the client/factory they belong to; however, when we roll out new features, we also like to target with more granularity, to specific users (super-users, early adopters within a client, test devices).

**Comment by dabeeeenster** [comment]
This is something we have in the backlog!

There are complexities here with our move to the Edge API as we can no longer do a simple query to retrieve this data.

**Comment by Jaribeau** [comment]
Ah yes that makes sense. Let me know if there's another github issue related to it so I can follow along.

**Comment by dabeeeenster** [comment]
This feature is dependent on implementing https://github.com/Flagsmith/flagsmith/issues/1675

**Comment by matthewelwell** [comment]
This is done in core. The edge requirement is going to be solved by limiting the number of identity overrides as per #1675
