### ISSUE TITLE
Enhancement request: Flexibility to change the public assets URL

### ISSUE THREAD

**Issue by ram2104** [SolidStateGroup/bullet-train-api#1305]
We had the requirement to update the public path for assets used in the dashboard. This is one of the most common requirement in any web app to customize the filepath for public assets. Currently, I see that we don't have the flexibility to change the public path in the webpack configuration. 

https://github.com/Flagsmith/flagsmith/blob/378f200fc2c3ad6626c856bf8045cdcc6646face/frontend/webpack/webpack.config.prod.js#L52

Is there any plan in the product roadmap to give flexibility to the consumer?

**Comment by dabeeeenster** [comment]
Hi,

Can I ask what the use case is here?

**Comment by ram2104** [comment]
We wanted to prefix some after "URL paths" to the generated assets. We wanted to capture those asset requests based on the common pattern.

for example: flagsmith is deployed on **https://example.com/flagsmith**, today all the web assets would try to be loaded from https://example.com/static/main.{fingerprint}.js, where the assets are available on https://example.com/flagsmith/static/main.{fingerprint}.js.

Something similar as "https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix"

How can I add "flagsmith" in the URL path of the web assets like CSS, JS, fonts, etc?

**Comment by dabeeeenster** [comment]
We don't support the application running under a subfolder I'm afraid - we'd recommend providing its own domain name and SSL certificate.
