### ISSUE TITLE
Enable Paging on Edge API Identities page

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1308]

**Comment by dabeeeenster** [comment]
@kyle-ssg this just needs enabling on the front end

**Comment by kyle-ssg** [comment]
![image](https://user-images.githubusercontent.com/8608314/179470351-f7ebba9a-54c9-4dcc-ad27-169c427b371d.png)

At the moment, the frontend relies on count to do paging. I can adjust this however, it means we will only ever be able to do next / previous for paging.

Also, it looks like there's a bug at the moment where the previous is always null, sent a curl in slack.

**Comment by gagantrivedi** [comment]
Backend: https://github.com/Flagsmith/flagsmith/pull/1322

**Comment by gagantrivedi** [comment]
> Also, it looks like there's a bug at the moment where the previous is always null, sent a curl in slack.

Right, so backend can't really generate previous URL here(I have removed it from the response):
The new response looks like this: 
![Screenshot_20220719_125236](https://user-images.githubusercontent.com/18366226/179691297-87ff0d5a-13d7-47b0-8c66-9ebd13d5a40d.png)

Front-end now need to keep track of last_evaluated_key for each page and send that to fetch the result for a given page.
ref: https://stackoverflow.com/questions/61414775/forward-and-backward-pagination-in-dynamodb

**Comment by kyle-ssg** [comment]
Hmm ok I'll see how I can manage this!

**Comment by kyle-ssg** [comment]
Added. If we're aiming to have a v2 admin SDK that's more usable we'll need a solution to make this a bit more user-friendly, it won't be easy for consumers to maintain a paging state with the data this endpoint provides.
