### ISSUE TITLE
Quick license question

### ISSUE THREAD

**Issue by hut8** [SolidStateGroup/bullet-train-api#1313]
I saw that the license was BSD 3-clause here: https://github.com/Flagsmith/flagsmith/issues/1044

But it has this text confuses me:

> 3. Neither the name of the Sentry nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

https://github.com/Flagsmith/flagsmith/blob/49c7890c39a4580fa7136075ba90b3765733bedf/LICENSE.md?plain=1#L13

Who's "the Sentry"? I can only find that clause with "the Sentry" in products made by Sentry by googling it. Was this a copy/paste error?

**Comment by dabeeeenster** [comment]
Thanks for flagging this - it looks like an error. Will check up on this now.

**Comment by dabeeeenster** [comment]
Thanks - fixed in #1315
