### ISSUE TITLE
Add a Notes field to Environments

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1320]
Underneath the Env name and client side key, add a textarea called "Notes" that can store 20kb of text.

**Comment by dabeeeenster** [comment]
Please add the API for this then assign to @kyle-ssg

**Comment by dabeeeenster** [comment]
Is the FE done for this? If not please assign @kyle-ssg !

**Comment by matthewelwell** [comment]
@kyle-ssg new field called `description` on the environment.
