### ISSUE TITLE
segments with text "true" get converted to test "True" when saved

### ISSUE THREAD

**Issue by TD-4242** [SolidStateGroup/bullet-train-api#1344]
When creating a segment with the Exactly Matches condition and a value of true it is capitalizing it.
It wasn't doing this a week ago.  all my old segments have true but now I can't create a new one with that.
this is what is getting sent 
![image](https://user-images.githubusercontent.com/3487671/181814038-27d1bf64-95f3-4a5c-ba15-1beddae3a24c.png)

This is what is in the response to the segemnt creationg
![image](https://user-images.githubusercontent.com/3487671/181814074-bde48dab-d082-4a87-ab5a-64ef57958281.png)

this seems to happen for false to False as well
found a bit of a workaround by prepending a space to the word " true"

**Comment by kyle-ssg** [comment]
@TD-4242 I can confirm there was an issue with displaying boolean segment rules as uppercase T however have tested and confirmed this has no functional impact. Also, we've added documentation that clarifies segment rule typing here https://docs-git-improvement-segment-rule-value-typing-flagsmith.vercel.app/basic-features/managing-segments#rule-typing

It's my understanding that your mentioned segment will correctly segment users with the trait 

```
flagsmith.setTrait("test", true);
```

or even

```
flagsmith.setTrait("test", "true");
```

We have also resolved the issue with the upper case t, if you change the rule value to "true" and resave it should update.


You can confirm all of the above by going to one of your user's pages in the dashboard and checking the segments panel alongside their traits. If you still think there's an issue where your users aren't in a segment then please feel free to open this issue and send us a message with your project/segment that you believe to be incorrect.

**Comment by TD-4242** [comment]
All of our internal code is using the string "true" and not the bool `true` I had not tested validating that the capital T version of true would work as I assumed `"True" != "true"`  I will validate that this hasn't effected any segment expectations.

_* I also see your documentation on the truthy string values._

**Comment by dabeeeenster** [comment]
I've added some docs here https://docs.flagsmith.com/basic-features/managing-segments#rule-typing that will hopefully explain things more clearly.
