### ISSUE TITLE
Improve Segment Rule value life

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1345]
- [x] Add summary and link to docs explaining type conversion
- [x] Add to docs for previous link
- [x] FE should always send string to API when saving rule values

**Comment by matthewelwell** [comment]
Linked to #1344

**Comment by kyle-ssg** [comment]
I'd like to understand this a bit more - the proposed solution doesn't seem very good. I don't really understand how to add boolean traits to segment rules from this.

If I have a trait ``{"power_user": true}``, how do I target it in a segment?

**Comment by dabeeeenster** [comment]
That's the point of this issue - we want to try and avoid people using strings to represent booleans, and move to `0` and `1`.
