### ISSUE TITLE
Add change details to audit log

### ISSUE THREAD

**Issue by Jaribeau** [SolidStateGroup/bullet-train-api#1347]
It would be helpful if the audit log included some details of the change made, rather than just indicating that a change occurred.

A few use-cases:
- Post-mortems
- Debugging
- Double checking changes made by others
- Checking recent changes to the state of the system (like skimming over recent commits/merges in a git repo to catch up on where everything is at)

**Comment by matthewelwell** [comment]
With the refactor of the AuditLog, this will be achievable using the history record stored against the AuditLog record. 

Note that [this functionality](https://django-simple-history.readthedocs.io/en/latest/history_diffing.html) available in django-simple-history may also come in useful when implementing this.

**Comment by matthewelwell** [comment]
The API for this was implemented [here](https://github.com/Flagsmith/flagsmith/pull/3218). It works by adding a new endpoint (`GET /api/v1/audit/:id/`) to retrieve a specific AuditLog record which includes a `change_details` attribute consisting of a list of changes that were made to trigger the AuditLog record. 

Further details of the new endpoint can be found by reviewing the API docs [here](https://api-staging.flagsmith.com/api/v1/docs/).

**Comment by kyle-ssg** [comment]
@matthewelwell This is live under the flag **audit_log_detail**

**Comment by matthewelwell** [comment]
Flag has been enabled in all environments.
