### ISSUE TITLE
Cannot create a segment on self-hosted

### ISSUE THREAD

**Issue by PrettyWood** [SolidStateGroup/bullet-train-api#1354]
Hello!
I started to play a bit with Flagsmith. It really feels good and the documentation is super clear. Great job!
I just have an issue when I try to create my first segment after running the docker compose (so the steps to reproduce are only to dl [the docker image](https://docs.flagsmith.com/deployment/docker) and run `docker-compose up`)

<img width="1004" alt="Screenshot 2022-08-05 at 14 05 54" src="https://user-images.githubusercontent.com/18406791/183073971-94400ed3-8d4b-49c8-a0b2-93ee1a1cedc6.png">

Did I do something wrong?
If this is indeed a bug, I can probably have a look and open a PR if you're already overwhelmed
Thanks!

**Comment by dabeeeenster** [comment]
Thanks for the kind words!

We can look at this early next week but if you want to have a crack at it that would be great!

**Comment by PrettyWood** [comment]
It works with latest version! 👍

**Comment by PrettyWood** [comment]
My bad I thought it worked on latest version but it's because I tried in SaaS environment.
But when I cloned the repo and started the frontend with `master`, I got the same error.
