### ISSUE TITLE
Change requests not visible when 0 approvals are required

### ISSUE THREAD

**Issue by Jaribeau** [SolidStateGroup/bullet-train-api#1373]
Change requests required approvals = 1
![image](https://user-images.githubusercontent.com/6071465/183881232-f8fdc62d-710f-47d9-8e83-a6139f8bbe8a.png)
![image](https://user-images.githubusercontent.com/6071465/183880677-2aab1bba-636e-4acc-93c1-11b4140b63e2.png)

Change requests required approvals = 0
![image](https://user-images.githubusercontent.com/6071465/183880768-d09bbf14-4cec-4bf1-adb4-4718e2448acf.png)
![image](https://user-images.githubusercontent.com/6071465/183881116-feb84123-c80f-422a-846b-66f7883e5b6d.png)

**Comment by kyle-ssg** [comment]
Thanks for raising, should be fixed 🚀
