### ISSUE TITLE
Feature edit modal UI tweaks

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1378]
While using the feature edit modal with a client, a few things that could be improved in the UI were noticed. 

- [ ] **User override for MV feature**

It's not immediately obvious how multivariate overrides work. Could we provide some help text? Also, is it possible to make it more obvious that the text input fields are not editable? 

- [x] **Indication of unsaved changes on feature edit modal**
 
At the moment, if you toggle the state of a feature but don't click the 'Update feature value' button, the changes are lost. Could we provide an alert modal when the user tries to click away from the modal to indicate there are unsaved changes? Perhaps a UI hint to show unsaved changes would be useful too. 

- [x] **JSON input for feature value**

It's not immediately obvious that the input is editable when 'json' is chosen for the editor. Is there a way to make this more obvious? I think perhaps the main confusion is that it looks identical when you're looking at the user override modal where it _isn't_ editable. 

- [x] **Resizing feature value input**

Is it possible to automatically resize the input when a large amount of data exists in there.

**Comment by kyle-ssg** [comment]
"It's not immediately obvious that the input is editable when 'json' is chosen for the editor. Is there a way to make this more obvious? I think perhaps the main confusion is that it looks identical when you're looking at the user override modal where it isn't editable."

Is it possible to clarify what this means? The value is editable in the override modal.

**Comment by matthewelwell** [comment]
Sorry, I missed out the key detail that it's not editable in the user override for an MV feature.
