### ISSUE TITLE
Flagsmith: Fetch error: ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by nvsd** [SolidStateGroup/bullet-train-api#1385]
When building an SSR app (locally and vercel.com) I get the error `Flagsmith: Fetch error: ReferenceError: XMLHttpRequest is not defined`.

I'm using nextjs with the flagsmith react project.

Please let me know if I can help further.

**Comment by dabeeeenster** [comment]
Hi,

Please can you add as much code as possible so we can figure out what's going on? Thanks!

**Comment by nvsd** [comment]
Sure!

To clarify when I say "building" I mean this is an issue at build time.
It's just a warning too so it doesn't block me or anything just slightly annoying.

To repro clone and `yarn build` in the below repo:
https://github.com/nvsd/flagsmith-repro

**Comment by nvsd** [comment]
Whoops, I derped the repo. I'm going to move this to flagsmith-js-client. Sorry about that.
