### ISSUE TITLE
[Feature Request] Allow conditions as prerequisites to features

### ISSUE THREAD

**Issue by taylorsmithgg** [SolidStateGroup/bullet-train-api#1387]
Having conditional arguments in flags would help to provide a more modular approach to complex feature flags.

For example:
IF Feature A is enabled -> Evaluate Feature B

**Comment by dabeeeenster** [comment]
We've discussed this a lot internally but feel that this is better suited in code than in Flagsmith itself. Happy to hear arguements for why this should not be the case however!
