### ISSUE TITLE
Core projects show 'Starts with' when 'Contains' selected on users page

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1411]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/14089968/186883149-2d811aa1-b542-4156-af3a-9910efb8c4d7.png">

e.g. https://staging.flagsmith.com/project/42/environment/Wo2TRannYBd25RPr45C2Hf/users

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/commit/212f8cdb78723b4cfba84606d420a5569adb2f4b
