### ISSUE TITLE
Report `get environment document` calls in various places

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1412]
We are storing `get environment document` calls in Influx but we need to show this data. 

We need to update:

- [x] The Flagsmith Dashboard - Org settings view showing API call usage < pretty sure this just needs front end work and the data is in the exisitng get Influx data endpoint 
- [x] The private Sales Dashboard organisation page

These should split out `get environment document` calls alongside Get Flags, Identities and Set Traits.

We also need to make sure that the totals where shown include  `get environment document`

**Comment by gagantrivedi** [comment]
Get influx data API, i.e: `api/v1/organisations/<organisation_id>/influx-data/` now contains another key called `Environment-document`.
Example response:

```
{
    "events_list": [
        {
            "Environment-document": null,
            "name": "2022-09-05",
            "Flags": null,
            "Identities": null
        },
        {
            "Environment-document": null,
            "name": "2022-09-06",
            "Flags": null,
            "Identities": null
        },
        {
            "Environment-document": 8,
            "name": "2022-10-04",
            "Flags": 4,
            "Identities": 4
        }
    ]
}



```

**Comment by gagantrivedi** [comment]
https://github.com/Flagsmith/flagsmith/pull/1497 Add environment document data to sales dashboard

**Comment by matthewelwell** [comment]
Adding @kyle-ssg to the assignees so that the FE item can be completed.
