### ISSUE TITLE
Deleted flag still appearing in web app

### ISSUE THREAD

**Issue by bonjo7** [SolidStateGroup/bullet-train-api#1428]
Hi everyone,

I have a very simple application where I have implemented flagsmith for feature flags (free plan). I deleted one of the features in the flagsmith UI console but yet when I console log `flagsmith.getAllFlags()` the deleted flag is still present. I would have expected the flag to have been removed

node version `v14.0.0`
react version `17.0.2`

Code example
```
import { useState, useEffect } from 'react'
import flagsmith from 'flagsmith'

export const FeatureFlag = () => {
    const [flags, setFlags] = useState()

    useEffect(() => {
        flagsmith.init({
            environmentID: "<id>",
            onChange: () => { // Occurs whenever flags are changed
                setFlags(flagsmith.getAllFlags())
                console.log("flags", flagsmith.getAllFlags())
            }
        });
    }, [])
    return {
        flags
    }
}
```

In the UI console I only have 1 flag called `movies` but console logging the flags shows 2 flags, `movies` and `shows` even though I have deleted `shows` from the console UI at `https://app.flagsmith.com/project/<ID>/environment/<env_ID>/features`

Have I missed something as I haven't seen anything in the docs that I might have missed

**Comment by dabeeeenster** [comment]
Hi,

Are you able to confirm what you are seeing via `curl`? Something like:

`curl "https://api.flagsmith.com/api/v1/flags/" -H 'X-Environment-Key: <env key>' | jq`

Thanks!

**Comment by bonjo7** [comment]
Thanks, the curl output only has the one feature, must be a caching issue on my end

```
[
  {
    "id": 149941,
    "feature": {
      "id": 28375,
      "name": "movie_table",
      "created_date": "2022-09-01T16:09:49.192726Z",
      "description": "This is a flag to hide my feature table",
      "initial_value": "Alpha",
      "default_enabled": false,
      "type": "STANDARD"
    },
    "feature_state_value": "Alpha",
    "environment": 19483,
    "identity": null,
    "feature_segment": null,
    "enabled": true
  }
]
```

console output from the code in my initial post
![Screenshot 2022-09-02 at 10 12 46](https://user-images.githubusercontent.com/39221065/188106616-95cd2feb-c18b-4459-998b-9261943fc084.png)

**Comment by bonjo7** [comment]
Resolved by adding the `api` param when initialising flagsmith

```
flagsmith.init({
            environmentID: "UjfeiRndaUxCXQBq8zGt7G",
            api: "https://api.flagsmith.com/api/v1/flags/",
            onChange: (oldFlags, params) => { // Occurs whenever flags are changed
                setFlags(flagsmith.getAllFlags())
            }
        });
```

**Comment by dabeeeenster** [comment]
We would advise you to move to `https://edge.api.flagsmith.com/api/v1/flags/` - see https://docs.flagsmith.com/advanced-use/edge-api - thanks!
