### ISSUE TITLE
Rationalise sales-dashboard and Organisation Settings to pull seat data from Chargebee

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1434]
Where organisations have a paid subscription in Chargebee, we should use the Chargebee meta data to display seat count and max api calls. 

This should replace pulling the data directly from the postgres table `organisation_subscription`

**Comment by gagantrivedi** [comment]
Yep, we already do that for seats, api calls and projects

**Comment by dabeeeenster** [comment]
Can we also use CB data for the Sales Dashboard overview table @gagantrivedi

**Comment by dabeeeenster** [comment]
Just needs data for overview table to read from CB API
