### ISSUE TITLE
Add newly created accounts on SaaS into Pipedrive

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1438]
Add Name and email as a new `Lead` in pipedrive. Similar to https://github.com/Flagsmith/flagsmith-website/blob/main/api/contact-us.js

**Comment by malthauser** [comment]
Whoever takes this on, please sync with me before you do this. I just want to make sure we get this done correctly. Thanks!!

**Comment by matthewelwell** [comment]
@malthauser I think the key thing we'd need to know here is when do we count a user as a new lead? Do we only want to count users that sign up and create an organisation or do we want to include users that, for example, sign up to an organisation via an invite?

**Comment by dabeeeenster** [comment]
to add to this - Pipedrive has an entity that maps well to our Organisation I believe - should we use that?

**Comment by malthauser** [comment]
Ideal structure:

- Create Organization that is connected to the domain name (ex: Disney.com = Disney)
- New leads should be checked against a similar Organization to their domain

As for when we want to create a lead, we should create ALL emails that are added to the system, but include HOW they were added as a property. This will allow us to track how many new leads we are getting vs how the growth of invites is trending (also very important). I have a guy that I'm meeting with tomorrow that has a ton of Pipedrive experience. Let me check with him and circle back on this stuff.

**Comment by matthewelwell** [comment]
Having discussed with @malthauser, my understanding of the requirements is as follows: 

 * When a new user signs up, we create a new lead in Pipedrive
 * New users should include context as to how they signed up (clean sign up, via invite, via SSO)
 * (perhaps a future requirement) Users should be added to an organisation based on the domain in their email address

**Comment by malthauser** [comment]
looks great. thanks!

**Comment by matthewelwell** [comment]
@kyle-ssg as discussed, I think we'll need to add a parameter (POST) to the sign up endpoints (email / password, github, google) to know whether the page was reached via an invite or not. As a starter, I'm suggesting: 

```
"sign_up_type": "NO_INVITE|INVITE_EMAIL|INVITE_LINK"
```

I'll also need to look into how LDAP works, although that's less important as it's currently enterprise on premise only.

**Comment by kyle-ssg** [comment]
Frontend is live

**Comment by kyle-ssg** [comment]
@matthewelwell I think this can be closed?
