### ISSUE TITLE
Add statsd to helm chart

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1449]
We want to have the flagsmith api implement statsd so it can send apm data out into a collector as part of our helm chart.

**Comment by plumdog** [comment]
These are the things that I think are required for this:
- The flagsmith application uses some env-vars to configure its statsd client:
    - Eg: `STATSD_HOST`, `STATSD_PORT`, `STATSD_PREFIX` and `STATSD_MAXUDPSIZE`
    - Maybe also a `STATSD_ENABLED`, as all of the above have default values in the statsd client.
    - These are used to configure the statsd client in Python code https://statsd.readthedocs.io/en/v3.3/reference.html#StatsClient
        - And then uses this to report stats.
        - This could have more config options, to control things like sample rates, maybe to switch reporting on and off for different areas of the application.
    - And passed to gunicorn https://docs.gunicorn.org/en/stable/settings.html#statsd-host
- The flagsmith chart then has options for setting these
    - With an option to handle the statsd host being a pod on the node, like Datadog's daemonset, or a provided host, like if you're running your own Statsd somewhere.
- Some documentation, both for the application env-vars, and for the chart.

Some extra options around Datadog:
- Per https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent, can just use plain a plain Statsd client when talking to Datadog and it will be fine. So doing nothing Datadog-specific would be fine.
- Or, can provide some specific Datadog options
    - See https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent&code-lang=python#client-instantiation-parameters for the application code
    - And https://docs.gunicorn.org/en/stable/settings.html#dogstatsd-tags for Gunicorn

**Comment by dabeeeenster** [comment]
Yep this looks good - a vendor neutral solution is best I think. So not having any Datadog specific code is the right way forward. Should be only a few LOC addition?! Lets do it?!

**Comment by dabeeeenster** [comment]
https://github.com/Flagsmith/flagsmith/pull/1552 is in `main` now - so we should be able to get this into helm now?
