### ISSUE TITLE
Add option to prevent flag defaults being set in all environments

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1450]
At the moment, users with create feature permissions are able to create a feature with a default state / value which will then be applied to all other environments. 

This issue relates to the ability to prevent defaults set when creating a feature in one environment being used in other environments. 

The specific use case here is to prevent users that only have access to a development environment being able to create features that are enabled / have a truthy value in production.

**Comment by kyle-ssg** [comment]
The frontend of this is live under the feature flag **prevent_flag_defaults**

**Comment by kyle-ssg** [comment]
I think we can close this @matthewelwell ?
