### ISSUE TITLE
Add date equality / inequality operators to segment engine

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1458]
e.g. 
<img width="751" alt="image" src="https://user-images.githubusercontent.com/14089968/190655587-b55a9f6a-752d-4073-a0d2-c0b39a5ccbe6.png">

We should be able to do: equals, not equals, greater than, greater than equals, less than, less than equals. 

We would need to also capture the date format as part of the segment rule.

**Comment by dabeeeenster** [comment]
You can do this at the moment by just dealing in epoch time. Avoids both time zones and date string formatting! Maybe we should just tell people to do that? Or maybe add an epoch time converter UI element?

**Comment by matthewelwell** [comment]
Ah yes, that's a much better solution!
