### ISSUE TITLE
Segment flag change sends Slack notification for every segment on the flag

### ISSUE THREAD

**Issue by Jaribeau** [SolidStateGroup/bullet-train-api#1466]
Changing the flag state of a segment override sends 1 Slack notification for every segment on the flag, whether that segment is impacted by the change or not. 

Example:
`example_feature` : off
with segment overrides:
`segment_a` : on
`segment_b` : on
`segment_c` : on

Changing the flag state of `segment_a` override may impact  `segment_b` and `segment_c`, and so based on the current slack notifications I would expect 3 slack notifications:

> Flag state / Remote config value updated for feature `example_feature` and segment `segment_a/b/c`
> Environment: production

However, changing the flag state of `segment_b` should not impact `segment_a`, so:

Expected behaviour: 2x notifications.
Current behaviour: 3x notifications. (in our use case its ~15 for every change, which makes it harder to get an at-a-glance idea of what was changed).

Not critical, but a nice to have if its an easy change 🙂

**Comment by dabeeeenster** [comment]
Thanks! We're working on a big backend overhaul of this entire component which I've added to the Milestone.

**Comment by matthewelwell** [comment]
Hey @Jaribeau, this should be resolved for you now.
