### ISSUE TITLE
Add Access-Control-Max-Age to CORS preflight Edge API respones

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1478]
As per https://stackoverflow.com/questions/40731465/access-control-max-age-vs-cache-control - add this to the default headers in Edge API.

**Comment by gagantrivedi** [comment]
Needs to find a way to do this through application load balancer.
PS: Adding those headers directly breaks the alb (probably)

**Comment by dabeeeenster** [comment]
This is implemented in Edge-API And waiting to go live

**Comment by dabeeeenster** [comment]
This is now live!
