### ISSUE TITLE
Invite Members API call fails

### ISSUE THREAD

**Issue by Nihir10dec** [SolidStateGroup/bullet-train-api#1480]
I am trying to add new members to the Organisation. I have the admin rights.
But every time I try to invite any new user, it shows failed to invite.
We have self-hosted the Flagsmith.
I checked the API call and it fails with 500 status code with no particular error message. 
The endpoint it hits is `https://(my_domian)/api/v1/organisations/5/invite/`
The body it has passed is like this
`{"invites":[{"email":invitor_email,"role":"ADMIN"}],"frontend_base_url":"(my_domain)/invite/"}`
Can someone please help me out with this?

**Comment by dabeeeenster** [comment]
Hi,

Can you confirm the version of the platform you are running, and how you are running it? If the API is throwing a 500 it should be generating a stack trace in the server logs - can you find that? 

Thanks!
Ben

**Comment by Nihir10dec** [comment]
Can you please help me out in where can I find out which version of the platform I am using?
I'm working on checking the logs and will let you know if I find something substantial.

**Comment by dabeeeenster** [comment]
How are you installing the application?

**Comment by Nihir10dec** [comment]
It has been installed by my seniors quite long ago when it was bullet train. The backend API code was lat update in May 2021 when it was updated to Flagsmith.
I've recently started using it after my seniors left and facing this issue.
Can you guide me with the next steps of how should I go ahead in resolving this issue?
Everything else seems to work fine. I can create flags, users, segments and environments. Just the invite member feature isn't working.

**Comment by dabeeeenster** [comment]
We would recommend upgrading to the latest version!

**Comment by Nihir10dec** [comment]
Should I just follow [this](https://docs.flagsmith.com/deployment/locally-api ) and I am good to go?

**Comment by dabeeeenster** [comment]
It depends entirely on how you are running the platform - we don't have that info I'm afraid!
