### ISSUE TITLE
Issue with test webhook functionality when using basic authentication

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1495]
Based on a report from a customer, it seems that the test webhook functionality in the UI doesn't work when using basic authentication, however, the webhook itself subsequently does work.

**Comment by EdsnLoor** [comment]
We always get either the message of "There was an error posting yo your webhook"  or no message at all after we click on "Test Your Weebhook".

<img width="522" alt="Screen Shot 2022-10-03 at 12 41 55 PM" src="https://user-images.githubusercontent.com/85133779/193643366-6e14a71f-2499-422f-b5da-11cbfd34a637.png">

But even if we get the error message the webhook does work .

If we try the "Test Your Weebhook" again I got no message at all.

Maybe @kyle-ssg could give us some hint  to solve this bug.

**Comment by matthewelwell** [comment]
To add to the above, the steps to reproduce are: 
 
 - Try to create a webhook with the URL: https://user:password@example.com (it doesn't matter that the URL doesn't exist)
 - Click 'Test your webhook' 
 - The modal will close and save the webhook, regardless of the fact that the test failed or succeeded
