### ISSUE TITLE
Allow for case sensitive flags to be defined

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1513]
# Overview

Currently, all flags are lower-cased in the Dashboard when created. For various reasons (see below), some users want to be able to store case sensitive flags.

We originally decided to store and evaluate flags without caring for their case, as we thought it could introduce bugs, but we have had several requests for this.

# Implementation

Have a per _Project_ boolean (that defaults to off) that defines whether flags are to be stored in a case-sensitive way. 

# Q&A

- In the dashboard, you would not be able to create both`flag_a` and `FLAG_A` or indeed `flag_A` as they are all equivalent
- Our API would return case-sensitive flag names, in the manner that they were originally entered when created
- If a flag is saved via our API with any upper case characters, and the project is set as "Case Insensitive" the API would return an error and the flag would not be saved. 
- SDKs evaluate flags in a *case sensitive* manner. 

## Reasons why case sensitive flags are helpful

- When unmarshalling flagsmith JSON into an in-memory data structure, it can be beneficial for case sensivity to be preserved. 
- From another user: _"When we sync the toggles back from Flagsmith to our on-prem sites, we need the toggles with the appropriate upper/lower cases.This ensures other consumers of the toggles in our system will work properly."_

**Comment by smashkovich** [comment]
Hi
1. in our case we should not distinguish between flag_a and FLAG_A, for us its the same feature toggle.
2. flagsmith.getFlagValue("FLAG_A") should return the same result as flagsmith.getFlagValue("flag_a").

**Comment by dabeeeenster** [comment]
Suggest that flags are _stored_ in a case sensitive manner, but _evaluated_ ignoring the case. As examples:

- In the dashboard, you would not be able to create both`flag_a` and `FLAG_A` or indeed `flag_A` as they are all equivalent
- In the SDKs, getFlagValue("FLAG_A") would be equivalent to getFlagValue("flag_a")

**Comment by gagantrivedi** [comment]
Front end can use the field named `only_allow_lower_case_feature_names`  on project to control this. 
ps: this is available in staging

**Comment by kyle-ssg** [comment]
Will be live under the flag **case_sensitive_flags**

**Comment by kyle-ssg** [comment]
Keeping open now until we decide to enable the flag.
