### ISSUE TITLE
Add task to prune processed tasks table

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1523]
The number of days before pruning record should be configurable by an env var, and default to 7 days.

**Comment by matthewelwell** [comment]
Analysing the impact from the job that ran on staging to clear out ~1M tasks, we can see a small spike in RDS CPU usage. 

![image](https://github.com/Flagsmith/flagsmith/assets/14089968/8f20fb8b-36e8-496e-99dc-cb0d49b6421a)

This is with a batch size of 2000 records.

**Comment by gagantrivedi** [comment]
Implemented here: https://github.com/Flagsmith/flagsmith/pull/2095
