### ISSUE TITLE
Add ability to add users to default user groups on signup

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1527]
When users sign up we should allow admins to configure a list of default user permission groups they should be added to in the organisation. This is particularly useful for LDAP / SAML where users are automatically added to organisations but it would also be useful when users accept invites with the 'USER' role.

**Comment by gagantrivedi** [comment]
Adds `is_default` to mark a group as default user permission group

![delete_me](https://user-images.githubusercontent.com/18366226/195769355-5ce5f0e9-5bc3-476f-a502-ee0e997fc7b2.png)

**Comment by kyle-ssg** [comment]
FE is live under the flag **default_user_groups**

**Comment by matthewelwell** [comment]
BE is released. I've tested in staging. Need to confirm whether we're happy for this to be available on all plans.

**Comment by kyle-ssg** [comment]
Tested in production - enabling the flag and will mark the flag as stale
