### ISSUE TITLE
Unable to use OAuth login with invite links if `ALLOW_REGISTRATION_WITHOUT_INVITE=false`

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1563]
The issue is here: https://github.com/Flagsmith/flagsmith/blob/main/api/custom_auth/serializers.py#L54

If `ALLOW_REGISTRATION_WITHOUT_INVITE` is disabled, we check to see if there is a valid invite, however, this only works for email invites. We need a way to determine if the user landed on the page from an invite link.

**Comment by mvrhov** [comment]
It's not just OAuth is normal sign-up too

**Comment by matthewelwell** [comment]
> It's not just OAuth is normal sign-up too

Sorry, I don't quite follow. Can you elaborate on the issue you're facing please? Please provide screenshots too.

**Comment by mvrhov** [comment]
I have set the ALLOW_REGISTRATION_WITHOUT_INVITE to **false** and copy pasted the invite link to a few persons so they could create accounts. They get an error stating that they cannot create account without invite link. They got to signup form from invite link.
