### ISSUE TITLE
More intelligent edge and core identity POST DB writes

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1585]
Currently both Core and Edge API naively write to the database when receiving a request like:

```
## Get Flags With Identifier and Traits
curl -X "POST" "https://edge.api.flagsmith.com/api/v1/identities/?identifier=YYY" \
     -H 'X-Environment-Key: XXX' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -H 'Accept-Encoding: gzip' \
     -d $'{
  "traits": [
    {
      "trait_value": "this_value",
      "trait_key": "this_key"
    },
    {
      "trait_value": "this_value2",
      "trait_key": "this_key2"
    }
  ],
  "identifier": "YYY"
}'
```

We should only write to the database if the identity trait data has changed. We do a read anyway as we need to augment traits with whatever is currently in the db. We should effectively do a diff against that data and if there are no changes, don't do a write.

**Comment by dabeeeenster** [comment]
Pretty sure this is costing us quite a bit of money on Dynamo and replication - needs priroitising @gagantrivedi !

**Comment by gagantrivedi** [comment]
https://github.com/Flagsmith/edge-api/pull/120

**Comment by dabeeeenster** [comment]
We should do this in core too, right?

**Comment by matthewelwell** [comment]
In testing this, we've realised that actually this is only a partial optimisation. In the case where an identity has the following traits in dynamo: 

```json
{
  "trait_key": "foo",
  "trait_value": "bar"
},
{
  "trait_key": "foofoo",
  "trait_value": "barbar"
},
```

and sends the following request: 

```
POST /api/v1/identities/

{
  "identifier": "identifier",
  "traits": [
    {
      "trait_key": "foo", 
      "trait_value": "bar"
    }
  ]
}
```

this will still result in a write to dynamo which is technically unnecessary.

**Comment by matthewelwell** [comment]
On reviewing the code, I'm not convinced that [the above](https://github.com/Flagsmith/flagsmith/issues/1585#issuecomment-1310042334) is true. We should write a test to verify this and (hopefully) close this issue.

**Comment by gagantrivedi** [comment]
Test was added here: https://github.com/Flagsmith/edge-api/pull/231
