### ISSUE TITLE
Setting an Identity flag override to the Environment default doesn't trigger a webhook

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1589]
1. Add a feature webhook to an environment
2. Create a flag `A`. Default to false.
3. Create an identity. 
4. Override the flag `A` to true for the identity.
5. Webhook triggers. 
6. Reset the user override by clicking the 'Reset' button
7. No webhook triggers. It should.

**Comment by matthewelwell** [comment]
Duplicate of #148

**Comment by nihaha** [comment]
Any progress on this issue?

**Comment by matthewelwell** [comment]
Hi @nihaha, this issue is closed. Please keep the discussion to the open issue #148.
