### ISSUE TITLE
Segments should support the 'IN' keyword

### ISSUE THREAD

**Issue by sw-tracker** [SolidStateGroup/bullet-train-api#1595]
Hi @dabeeeenster ,

Our developers would like to be able to create a segment in which they can select an `IN` option from the drop-down and in the `value` they could enter a comma-separated list of strings/numbers.

<img width="952" alt="image" src="https://user-images.githubusercontent.com/15125668/199696797-b1e0df8d-38a8-4603-9cbc-deb64827187e.png">

Cheers,
Olga

## Acceptance Criteria

 - [ ] Users are able to add a segment condition using the IN operator in the dashboard 
 - [ ] Flags with a segment override using a segment with the IN operator are evaluated correctly via the Core API
 - [ ] Flags with a segment override using a segment with the IN operator are evaluated correctly via the Edge API
 - [ ] Flags with a segment override using a segment with the IN operator are evaluated correctly via local evaluation mode in all server side SDKs

**Comment by matthewelwell** [comment]
This needs to be completed in the following places: 

 - [x] Core API 
 - [x] Flagsmith engine
 - [x] Python SDK
 - [x] PHP SDK
 - [x] Java SDK
 - [x] Node.js SDK
 - [x] Elixir SDK
 - [x] C# SDK
 - [x] Ruby SDK
 - [x] Go SDK
 - [x] Rust SDK

**Comment by khvn26** [comment]
UI warning task: https://github.com/Flagsmith/flagsmith/issues/2543
