### ISSUE TITLE
Add meta data fields to core entities

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1610]
# Overview 

Larger teams often require the ability to add their own meta-data to the following entities:

- Flags
- Segments
- Environments

Examples of the meta data that they might add:

- JIRA ticket code (e.g. `FLAGSMITH-152`) to a Flag
- URL for Infra overview for an Environment
- Link to Amplitude for a Segment

These data could be optional or required. For example, engineers should be required to add a JIRA ticket against a new Flag when the flag is created

# Implementation

Administrators should be able to define fields that they want associated with an entity, and whether it is required or optional.

To begin with the administrator should be able to define with the field is single line or multi-line. For v1, just allow any text. 

gz#40

**Comment by matthewelwell** [comment]
Create a new model that can be linked to any entity using the `django_content_type` table (there is probably a model in the django lib that powers this).  

Something like: 

```python
class FieldType(ModelChoices):
    INTEGER = "int"
    ...


class ModelMetadataField(Model):
    organisation = models.ForeignKey(Organisation)
    field_name = models.CharField()
    field_type = models.CharField(choices=FieldType.choices)


class ModelMetadata(Model):
    object_type = models.ForeignKey(DjangoContentType)
    object_id = models.BigIntegerField()
    metadata_field = models.ForeignKey(ModelMetadataField)
    field_data = models.TextField()

    class Meta:
        index_together = (("object_type", "object_id"), ("object_type", "field_name")  # TODO: are there more indexes needed?
```

**Comment by gagantrivedi** [comment]
Needs UI work

**Comment by gagantrivedi** [comment]
@novakzaballa The related endpoints are included as part of the description in the linked pull request

**Comment by novakzaballa** [comment]
Here are some designs

![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/6f050dd0-b68f-420c-adcf-913f350ea555)



![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/fd660172-a545-4dbd-b038-9ee7b04df60f)



![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/8c6fe900-c261-41b1-b663-bf41893695c7)



![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/52b83085-ced7-4f3a-9d86-702d5e57adaa)

**Comment by matthewelwell** [comment]
Looks good to me. I wonder if, rather than using text in this matrix, we could use symbols? Maybe a green tick, a red cross, and a green padlock (for required) or something? 
<img width="964" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/14089968/3fcbfc20-d9c2-4df6-a681-5df8749c6a64">


Also, rather than multiple toggles here, we could use a single drop down, right? 
<img width="693" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/14089968/c5a85f04-a9ae-4106-b626-0bc4162001c3">

**Comment by novakzaballa** [comment]
Yes, we could. that was my first option but I decided to align with the backend here since it is split there. Should I switch to a single dropdown-down list?
![image](https://github.com/Flagsmith/flagsmith/assets/41410593/1231fe1c-b211-430f-8281-d28368a27ce2)

**Comment by novakzaballa** [comment]
@matthewelwell for enabled/disabled we could use the icons of the regular toggles we use 
![image](https://github.com/Flagsmith/flagsmith/assets/41410593/6a9fb553-3587-45df-b736-b28409f91d2e)
and for required we could use this one ![image](https://github.com/Flagsmith/flagsmith/assets/41410593/8dee84bf-7bc1-48e1-8bb9-661ceb3101ce)

**Comment by novakzaballa** [comment]
Or maybe these

![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/d2e9f746-d456-4632-b71c-ef391f556dbb)



![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/04f444b0-1906-4ab8-b4e6-5fe9f903590c)

**Comment by matthewelwell** [comment]
@gagantrivedi can you take a look at these designs from a functionality point of view?

**Comment by matthewelwell** [comment]
> Yes, we could. that was my first option but I decided to align with the backend here since it is split there. Should I switch to a single dropdown-down list?
> ![image](https://user-images.githubusercontent.com/41410593/275562102-1231fe1c-b211-430f-8281-d28368a27ce2.png)

Maybe this is ok as long as 'required' is greyed out until 'enabled' is checked. I guess let's keep it simple for now as Akveo might want to tweak it anyway.

**Comment by novakzaballa** [comment]
@gagantrivedi Could you give me an example of how to use the is_required_for field for the segments and flags entities in a request?

**Comment by gagantrivedi** [comment]
> @gagantrivedi Could you give me an example of how to use the is_required_for field for the segments and flags entities in a request?

Here is how you create a field with `is_required_for`: https://github.com/Flagsmith/flagsmith/blob/main/api/tests/unit/metadata/test_views.py#L270
Here is how you can use that with an objet: https://github.com/Flagsmith/flagsmith/blob/main/api/environments/tests/test_views.py#L553
