### ISSUE TITLE
UI: Expose external_id on user permission groups to support group sync 

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#1612]
Endpoint `​/api​/v1​/organisations​/{organisation_pk}​/groups​/` now takes an additional argument named `external_id` that can be used by the user to create a one to one mapping between the SAML user groups(in external system) and flagsmith user groups. 
PS: this is only available in staging for now.

**Comment by gagantrivedi** [comment]
Related SAML issue: https://github.com/Flagsmith/flagsmith-saml/issues/14

**Comment by kyle-ssg** [comment]
Will be live under the feature flag **group_external_ids**

**Comment by kyle-ssg** [comment]
Tested in production - enabling the flag and will mark the flag as stale
