### ISSUE TITLE
Hide disabled flags per environment

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1616]
At the moment, it's only possible to hide disabled flags on a per project basis. For organisations that are using our REST API, or are particularly sensitive to changes, we should allow this to be applied per environment so that the changes can be tested in a given environment before being applied to the whole project.

**Comment by dabeeeenster** [comment]
This needs implementing in Edge too.

**Comment by gagantrivedi** [comment]
https://github.com/Flagsmith/edge-api/pull/131

**Comment by matthewelwell** [comment]
@kyle-ssg environments now have a new field 'hide_disabled_flags' so that the setting (which currently exists at the project level) can be set at the environment level. 

The one difference is that it can be (and is by default) `null` at the environment level. This signifies that it should 'inherit from the project'. If it's set at the environment level (whether true or false) it will override whatever is set at the project level.
