### ISSUE TITLE
Add functionality to hide traits from identities endpoint reponses

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1617]
The consideration here is that, since traits can be used to store arbitrary data, a malicious attacked could use the traits endpoint as a way to store malicious data and retrieve it again using the GET endpoint. If we add the functionality to prevent traits being returned then this will close this vulnerability.

**Comment by matthewelwell** [comment]
In final testing, it looks as though this change would break our kotlin and swift clients as they both have strict schemas that expect the traits to be provided. Lines of code linked below. 

https://github.com/Flagsmith/flagsmith-kotlin-android-client/blob/main/FlagsmithClient/src/main/java/com/flagsmith/entities/IdentityFlagsAndTraits.kt#L14
https://github.com/Flagsmith/flagsmith-ios-client/blob/main/FlagsmithClient/Classes/Identity.swift#L20

The way I see it, we have 2 options: 

 1. Replace the `traits` key in the API but simply return an empty array in all scenarios. 
 2. Update the kotlin and swift clients to handle the attribute missing. 

I am strongly in favour of option (1), what are your thoughts @gagantrivedi ?

**Comment by gagantrivedi** [comment]
> 



> In final testing, it looks as though this change would break our kotlin and swift clients as they both have strict schemas that expect the traits to be provided. Lines of code linked below.
> 
> https://github.com/Flagsmith/flagsmith-kotlin-android-client/blob/main/FlagsmithClient/src/main/java/com/flagsmith/entities/IdentityFlagsAndTraits.kt#L14 https://github.com/Flagsmith/flagsmith-ios-client/blob/main/FlagsmithClient/Classes/Identity.swift#L20
> 
> The way I see it, we have 2 options:
> 
>     1. Replace the `traits` key in the API but simply return an empty array in all scenarios.
> 
>     2. Update the kotlin and swift clients to handle the attribute missing.
> 
> 
> I am strongly in favour of option (1), what are your thoughts @gagantrivedi ?

Yeah, I'd prefer 1 as well
