### ISSUE TITLE
Add ability to rotate personal access tokens

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1618]

**Comment by matthewelwell** [comment]
@gagantrivedi I think this got closed automatically when your PR was merged. We'll need to get some FE done for this too though - can you brief Kyle on it?

**Comment by gagantrivedi** [comment]
![delete](https://user-images.githubusercontent.com/18366226/204181675-3a6512af-21db-4f01-8964-27d318db4e15.png)

We should add a button(in the user settings page?) that allows the user to delete their token(with a tooltip message(?) saying that the user will be logged out)
