### ISSUE TITLE
Add UI indication that a feature has at least one segment / identity override on overview page

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1619]
Example in the form of a mock up: 

<img width="1176" alt="Screenshot 2022-11-07 at 15 42 21" src="https://user-images.githubusercontent.com/14089968/200352789-7286bc31-bb67-4270-921f-dea42f831b9b.png">

**Comment by kyle-ssg** [comment]
@matthewelwell I'm not too sure where I'd get this information from as part of the list?

**Comment by matthewelwell** [comment]
Yeah, sorry, I meant to add to the ticket that I wasn't sure if you'd have this information up front or not. If you don't think you do, then feel free to assign back to me and add the API label. 

Thinking about it, this might rely on #1675 too.

**Comment by kyle-ssg** [comment]
Ok, so essentially I need a count of feature segments and identity feature states against each paged feature.

So either :

- A way to get a paged list of feature segments / identity feature states for a particular environment and I just page through them all when fetching features
- A variation of the projects/14/features/?page=x that takes an environment id and adds the above information in addition to the feature

If I'm not mistaken, I don't think there are any current endpoints that can do either of the above

**Comment by gagantrivedi** [comment]
> A way to get a paged list of feature segments / identity feature states for a particular environment and I just page through them all when fetching features

@kyle-ssg  Do you mean an endpoint that returns them together? 

Because separate endpoint exists for both of them

**Comment by kyle-ssg** [comment]
Yeah, a way to get them all together - they are paged so I can't really rely on 2 separate endpoints.

**Comment by matthewelwell** [comment]
Surely we should just handle this on the API though? A boolean attribute or an integer count against each feature?

**Comment by kyle-ssg** [comment]
Yep that'd be even better

**Comment by kyle-ssg** [comment]
> A variation of the projects/14/features/?page=x that takes an environment id and adds the above information in addition to the feature

Ah @matthewelwell, this is what I was getting at with this point. Unless you mean integer/boolean attributes against the feature state, we'd have to add the environment id to the above endpoint.

**Comment by matthewelwell** [comment]
Right, yep, good point! I think it would need to be against the Feature yeah, so we can add an environment id parameter to that endpoint - makes sense to me.

**Comment by matthewelwell** [comment]
@kyle-ssg you can now pass `environment` as a query parameter to `/projects/:id/features/` (this should be the numeric id of the environment). Two new values have been added to the feature json: `"num_segment_overrides"` and `"num_identity_overrides"`. This will provide an integer value for the number of each type of override for that feature in the given environment. 

Notes: 

 - If you don't provide an environment parameter, these values will return as `num_segment_overrides=0` / `num_identity_overrides=null`. 
 - `num_identity_overrides` will always return `null` for projects that have dynamodb enabled (as we don't currently have a mechanism of determining identity overrides for a feature in this state)
