### ISSUE TITLE
Return the segment name in the feature-segments endpoint

### ISSUE THREAD

**Issue by kyle-ssg** [SolidStateGroup/bullet-train-api#1645]
https://github.com/Flagsmith/flagsmith/issues/1575 will make it so that segments are paged, currently, the frontend needs to hit this endpoint when viewing segment overrides since we show the name.

![image](https://user-images.githubusercontent.com/8608314/200835417-881a4981-e736-4704-b3f1-d69314f79446.png)

This means that in order to allow segment paging we need the feature-segments endpoint to return the segment name.

**Comment by matthewelwell** [comment]
@kyle-ssg linked PR adds a new `"segment_name"` attribute to the list of feature segments.
