### ISSUE TITLE
Brave browser blocks flagsmith/react requests to api

### ISSUE THREAD

**Issue by ozanbatuhanceylan** [SolidStateGroup/bullet-train-api#1651]
When shields up in Brave, flagsmith cannot fetch the features from api. So that i cannot use the feature flagging properly.

![image](https://user-images.githubusercontent.com/13339915/201045601-c9bc6f56-b247-47f0-9c4a-844c53d7a07b.png)

I searched docs and issues but cannot find anything about network blocking issue. I am expecting feature flag operations should not be blocked by any adblocker.

Is there any option to prevent blocked by ad blockers or is it just a bug? 

gz#70

**Comment by dabeeeenster** [comment]
This looks like brave is blocking requests to `localhost` - there's nothing we can do about this. You will need to allow that in your browser.
