### ISSUE TITLE
Can't finalize Slack integration 

### ISSUE THREAD

**Issue by SonnyAD** [SolidStateGroup/bullet-train-api#1690]
Hi, 

I am self-hosting Flagsmith via Docker and having troubles with Slack integration.
I made a Slack app, and added a redirect url https://myflagmisth.com/api/v1/ 

But whenever I try to run the integration when landing on Slack page normally to allow the app, I get a message 
```
redirect_uri did not match any configured URIs. Passed URI: http://myflagmisth.com/api/v1/...
```

Looking at Slack app config, http is not possible for a redirect uri.

FYI I have AWS CloudFront in front of my unique Flagsmith instance. myflagsmith.com is certified by CloudFront, and it's using IP:8000 as origin. So it's directly connecting to the Flagsmith app. 

I tried a couple of combinations with SECURE_PROXY_SSL_HEADER_NAME and SECURE_PROXY_SSL_HEADER_VALUE
and in CloudFront I also added custom header to the request to origin: 
- HTTP_X_FORWARDED_PROTO: https
- X-Forwarded-Proto: https

But no luck, it's always somehow creating a redirect url with http. 

Do you have any idea why? 

I tried to look at the source code. I saw a call to `get_current_site()` from Django, which should return the host with the http/https so not sure where the http is added. 

Thanks!

**Comment by dabeeeenster** [comment]
In our ECS config we have: `SECURE_PROXY_SSL_HEADER_NAME` set to `HTTP_CLOUDFRONT_FORWARDED_PROTO` but your configuration might be different.

**Comment by SonnyAD** [comment]
I swapped flagsmith with a just a debug tool to export the headers received by flagsmith, and I got that: 

```
{"host":"myflagsmith.com","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36","x-amz-cf-id":"B_BiWZdy5MEkmaRSs60sOOaELWDbOrt1jLFzQF99KcriQFTZpt68kQ==","connection":"Keep-Alive","via":"2.0 4582a1c2d6f2ede6721e6bf1997ded3e.cloudfront.net (CloudFront)","cookie":"G_ENABLED_IDPS=google; _delighted_web={%22fUdwqs6kdjJQFU4c%22:{%22_delighted_fst%22:{%22t%22:%221632291975772%22}%2C%22_delighted_lst%22:{%22t%22:%221633939599279%22%2C%22m%22:{%22token%22:%22MfEj0AQdvPGYkOk2eezbPurN%22}}%2C%22_delighted_lrt%22:{%22t%22:%221633939659018%22%2C%22m%22:{%22token%22:%22MfEj0AQdvPGYkOk2eezbPurN%22}}}}; _ga=GA1.2.1922105981.1612426246; csrftoken=8s08VILzGEnxJqp4uVad5YvDyT8XskUod0n32flIpfEY3CphSD3AUE55vr6BJtiT; marketing_consent_given=false; sessionid=a1tb7oyipmtcufvurzlv6tfbuuuiaqx5; t=2df952ab1560aa03e018555baf0955c61c2cdb02","x-forwarded-for":"160.202.160.104","accept-language":"en-US,en;q=0.9,fr-FR;q=0.8,fr;q=0.7,zh-CN;q=0.6,zh;q=0.5,ja;q=0.4","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","accept-encoding":"gzip, deflate, br","sec-ch-ua":"\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","dnt":"1","upgrade-insecure-requests":"1","purpose":"prefetch","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","cloudfront-forwarded-proto":"https","http_cloudfront_forwarded_proto":"https"}
```

To make it short, there are these two headers: 
```
...
  "cloudfront-forwarded-proto":"https",
  "http_cloudfront_forwarded_proto":"https"
}
```

I tried both in `SECURE_PROXY_SSL_HEADER_NAME`. But no luck. The redirect URI received by Slack is still prefixed with http. 

Thanks!

**Comment by dabeeeenster** [comment]
Sorry - we cant provide further support for this in our open source product. You would have to do some analysis within the code/infra platform to figure out what is going on.

**Comment by SonnyAD** [comment]
Ok, no problem, I understand. I will dig around, and see if I can propose a PR eventually.
