### ISSUE TITLE
Document monitoring capabilities

### ISSUE THREAD

**Issue by zamazan4ik** [SolidStateGroup/bullet-train-api#1696]
Hi!

After reading the documentation it is not clear to me, what is the proper way to monitor the self-hosted Flagsmith installation. Is there any Prometheus endpoints and ready-to-use Grafana dashboard based on it?

Thanks in advance!

**Comment by dabeeeenster** [comment]
We have `statsd` support - https://docs.flagsmith.com/deployment/locally-api#statsd-integration
