### ISSUE TITLE
Document Highly-Available (HA) setup

### ISSUE THREAD

**Issue by zamazan4ik** [SolidStateGroup/bullet-train-api#1697]
After reading the documentation it is not clear to me, how could I perform Flagsmith HA setup. I have questions like:

- Could I install Flagsmith in cluster mode (multiple nodes in one installation)?
- If yes, how Flagsmith works if one node goes down? is there any (semi)automatic failover or not?

Would be awesome to read about it directly in the documentation.

**Comment by dabeeeenster** [comment]
This depends on your orchestration setup. The platform is stateless so you can run as many API nodes as you like.
