### ISSUE TITLE
Document backup/restore procedures

### ISSUE THREAD

**Issue by zamazan4ik** [SolidStateGroup/bullet-train-api#1698]
Hi.

Backup and restore are important operations in such a system as Flagsmith. Could you please describe in the documentation, how backup and restore should be performed for Flagsmith?

Thanks in advance!

**Comment by dabeeeenster** [comment]
https://docs.flagsmith.com/deployment/migrating-from-self-hosted-to-cloud#what-is-exported

Or back up and restore the postgres database.
