### ISSUE TITLE
Add clear labelling for sensitive environments

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1720]
Administrators should be able to define a banner, per Environment, made up of:

- A colour definition
- Text copy 
- Whether to show the banner or not

The banner should look like the existing butter bar, but with the colour and text as defined above.

**Comment by dabeeeenster** [comment]
@kyle-ssg We arent specifying the text colour - just the banner background - could we make the text black or white depending on the background colour?

**Comment by kyle-ssg** [comment]
Building under the flag tag_environments
