### ISSUE TITLE
Terraform provider documentation missing

### ISSUE THREAD

**Issue by siraj-mx51** [SolidStateGroup/bullet-train-api#1739]
- Terraform provider documentation doesn't show how to create features using the provider, instead it directs the user to only import existing features.
  - It is possible to create a feature using the provider (critical to us), however you need to find the `project_uuid`. I am not sure if its a knowledge gap on my behalf, but i could only find it by inspecting HTTP requests in my browser active session on _app.flagsmith.com_
- The import command `terraform import flagsmith_feature.some_feature <feature_uuid>` requires `feature_uuid` and it is not clear how to obtain that ?

gz#183

**Comment by gagantrivedi** [comment]
Hi, @siraj-mx51
> It is possible to create a feature using the provider (critical to us)

Yes, it is possible to create the feature using the terraform provider. Here is one example: https://registry.terraform.io/providers/Flagsmith/flagsmith/latest/docs/resources/feature

> however you need to find the project_uuid.

Yes, that is correct, to create a feature you will need `project_uuid` 

> I am not sure if its a knowledge gap on my behalf, but i could only find it by inspecting HTTP requests in my browser active session on app.flagsmith.com

Yes, this is also correct currently there is no way to get these UUID apart from inspecting the requests, but I have created an issue for that here: https://github.com/Flagsmith/flagsmith/issues/1740 and we will have a fix out for that very soon.

>The import command terraform import flagsmith_feature.some_feature <feature_uuid> requires feature_uuid and it is not clear how to obtain that ?

To get the feature_uuid you need to inspect the following call on feature page

![feature_uuid](https://user-images.githubusercontent.com/18366226/205539630-e6483513-18bf-461a-a23a-7e6e370d1edf.png)

**Comment by dabeeeenster** [comment]
Link to issue to add docs: https://github.com/Flagsmith/flagsmith-docs/issues/244

**Comment by dabeeeenster** [comment]
Fixed in https://github.com/Flagsmith/flagsmith-docs/pull/269
