### ISSUE TITLE
UI: show UUID of objects 

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#1740]
Objects like Projects, feature, feature-states, multivariate options and segment have associated `uuid` that are needed to interact with them using the terraform provider. Right now there is no other way to but to inspect the http request to get these `uuid`, we should find a way to accommodate them in the UI

gz#184

**Comment by kyle-ssg** [comment]
Is there a possibility to start generating / interacting these with these things via slugs? I don’t think we should start showing uuids everywhere.

**Comment by kyle-ssg** [comment]
I guess another possibility is to start allowing users to copy or switch to a json view of different elements e.g features via a button, or a tab to switch to a json view. I’d probably need to understand what people using terraform would want to do.

**Comment by gagantrivedi** [comment]
Yeah, I think adding a JSON view would be prefect.
> I’d probably need to understand what people using terraform would want to do.

So if you want to import (in order to update or delete it) an object like feature/segment/feature states in terraform, you are going to need the UUID of the object. Does that help?

**Comment by kyle-ssg** [comment]
Ok yep I understand, I think a json tab is ideal for this. I'll take a look at this for features initially and share an example.

**Comment by dabeeeenster** [comment]
Once this is done we can modify the docs here https://docs.flagsmith.com/integrations/terraform#using-the-flagsmith-terraform-provider and remove the warning/screengrab about how to get UUIDs

**Comment by kyle-ssg** [comment]
My gut feel is that this JSON tab is opt in via account settings, I can just make this an identity trait. I basically want to keep the main UI as simple as possible, do people agree?

**Comment by dabeeeenster** [comment]
Agh! I'm almost exactly 50/50 on that! Maybe have it as an option yeah.

**Comment by kyle-ssg** [comment]
https://user-images.githubusercontent.com/8608314/208403578-9f7eb8f0-764f-43d5-af07-f2b0044baaf9.mov

Something like this for the JSON ?

**Comment by gagantrivedi** [comment]
> ids.mov
> 
> Something like this for the JSON ?

Yeah, this looks prefect
