### ISSUE TITLE
Segments redirecting to projects in self hosted version

### ISSUE THREAD

**Issue by pjerryhu** [SolidStateGroup/bullet-train-api#1803]
Self hosted version. Clicking on the segment will redirect to project page. The router is problematic

gz#236

**Comment by pjerryhu** [comment]
Cross-verified with hosted web-version. The web-version has the correct UI, and is different from self-hosted version

**Comment by matthewelwell** [comment]
Hi @pjerryhu, can you please confirm how you're running the self hosted version to replicate this? Ideally, please provide a docker-compose file to exhibit the issue.

**Comment by matthewelwell** [comment]
I have been able to reproduce this when running the frontend and API directly on my laptop locally. It seems that the issue is that the call to get the segments for a project is using the URL for the staging API. Possibly it's using the flagsmith on flagsmith API url rather than the actual API url?
