### ISSUE TITLE
Free / Startup environments should not try to load change requests

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1809]
Currently using e.g. the `flagsmith/flagsmith` environment, the application shows the Change Requests option in the environment navigation. This will not load since the change requests endpoints are not included in the open source API. We should prevent this option from showing in the navigation in Open Source self hosted installations. 

gz#239

**Comment by kyle-ssg** [comment]
Depends on https://github.com/Flagsmith/flagsmith/issues/646. As far as I know, there's no defined approach to detect on prem, ee etc
