### ISSUE TITLE
Create change request calls PUT on features

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1836]
When creating a change request in the dashboard, the front end makes a call to PUT /projects/:id/features/:id which seems unnecessary and creates an audit log record unnecessarily. It might be that the answer to this issue is "it has to do it because ..." and that's fine, but I'd like to understand so I can alter the API accordingly regarding the Audit Log. 

gz#284

**Comment by kyle-ssg** [comment]
After looking into this it looks like this is no longer necessary due to the mv-options endpoint and the frontend now separating saving per tab.

PR linked
