### ISSUE TITLE
Implement Dynamo DAX on Edge

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1838]

**Comment by matthewelwell** [comment]
Due to the time based in-memory caching that was recently added to our Edge API, we are putting this on hold to gather more information about what benefits we would still gain from using DAX. 

We also want to discuss the possibility of using redis here instead of DAX.

**Comment by matthewelwell** [comment]
No longer relevant because extensions can be used with dynamodb streams instead.
