### ISSUE TITLE
Open Source version user limit reached

### ISSUE THREAD

**Issue by dmarlow** [SolidStateGroup/bullet-train-api#1844]
I'm testing things out with the docker container version and am seeing the following when trying to add another user:

![image](https://user-images.githubusercontent.com/2000510/212180087-cfe1526d-e51e-47c9-8490-1c32d5402326.png)

Here's what it shows under the General tab:
![image](https://user-images.githubusercontent.com/2000510/212180216-9e5a39db-8050-4b0b-9c8d-7ed932a27ac5.png)

I thought the Open Source version didn't have a limit for the number of users. Is that correct?

gz#301

**Comment by dabeeeenster** [comment]
Yep - this is a bug - we're looking into it!
