### ISSUE TITLE
Enviroment level permissions are not working as expected

### ISSUE THREAD

**Issue by turgaygulmez** [SolidStateGroup/bullet-train-api#1848]
We are setting user permission both on project and enviroment level. 

One of the user has the fallowing permission settings.

On project level:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/9077136/212359378-9e8e893b-8958-4a40-961a-eb5df979fd74.png">

On enviroment level: 

<img width="613" alt="image" src="https://user-images.githubusercontent.com/9077136/212359450-44f23774-2a96-4b88-ba5e-fe148f5bf518.png">

Even though the permission are being set properly, the user still has delete access. 

<img width="460" alt="image" src="https://user-images.githubusercontent.com/9077136/212359544-e365f66d-a5d5-4aed-bc38-16c955eaf3fe.png">

<img width="647" alt="image" src="https://user-images.githubusercontent.com/9077136/212359594-032df499-a3e3-4800-8ac5-8cf30fcc271b.png">

**Comment by matthewelwell** [comment]
Hi @turgaygulmez, can you help us investigate this please by providing information about whether you're self hosting Flagsmith or using app.flagsmith.com? If you're self hosting, please can you confirm the version(s) of the flagsmith image(s) you're using?

**Comment by turgaygulmez** [comment]
hi @matthewelwell ,

We do self-host flagsmith with enterprise account. The versions are as fallow

![image](https://user-images.githubusercontent.com/9077136/212631989-3bb1aadf-a8b8-4477-85e5-5c9345fd3ba2.png)


Version: v2.39.1
Frontend: 8fb8f7f97fef6dba0a3728d3766b342496068b79
Backend SHA: 8fb8f7f97fef6dba0a3728d3766b342496068b79

**Comment by matthewelwell** [comment]
Hi @turgaygulmez, thanks for this. Since you're on our enterprise plan, could I ask you to send an email with this information to your Flagsmith support email address so we can prioritise it accordingly?

**Comment by dabeeeenster** [comment]
Hi - please can you contact support@flagsmith.com to continue discussions - thanks!
