### ISSUE TITLE
See when a user was last logged in

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1854]
As an organization administrator, I want to be able to see when a user was last logged in in order to find stale user accounts that could potentially be removed.

gz#321

**Comment by kyle-ssg** [comment]
Please assign to me when there's API available

**Comment by matthewelwell** [comment]
@kyle-ssg API was added in the PR here: https://github.com/Flagsmith/flagsmith/pull/1906

New `last_login` field has been added to `GET /api/v1/organisations/:id/users/`. This is available in the staging API.
