### ISSUE TITLE
Unable to create or update segments

### ISSUE THREAD

**Issue by HariWarshan** [SolidStateGroup/bullet-train-api#1862]
Hi Team,

from dashboard when trying to create a segment with a simple rule, getting the below error

![Screenshot 2023-01-24 at 12 27 40 AM](https://user-images.githubusercontent.com/48403240/214127420-dd544abb-9e45-4b30-aec8-00b42b94057f.png)

more info, we're self hosting Flagsmith and not using app.flagsmith.com

while writing up this issue, i got to know that even updating the segments is also not working, which responds 500.

gz#328

**Comment by dabeeeenster** [comment]
What version are you running?

**Comment by gagantrivedi** [comment]
Also, @HariWarshan  can you share the logs generated by the API? It would be pretty hard to tell what is going on without that

**Comment by dabeeeenster** [comment]
Going to close this issue - please reopen with version details and logs.
