### ISSUE TITLE
Add the ability to configure admins within a group who can manage the membership of other users in that group

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1886]
Organisation admins should be able to define multiple admins in a user group that can then control the membership of other users in that group.

Along with this, there should be a setting that allows all members of the group to add other members to the group.

**Comment by matthewelwell** [comment]
@kyle-ssg I've added new endpoints to add / remove admins from a group. New endpoints are: 

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/14089968/227916914-c1fc8446-6c0a-4e23-b7c9-7f731d68ac85.png">

Also, the detail endpoint for retrieving a group now also returns the `"group_admin"` attribute to confirm if the user is already an admin or not.

**Comment by kyle-ssg** [comment]
@matthewelwell and maybe @gagantrivedi, from what I can see, posting to make-admin with a 200 response is not affecting the group_admin boolean that's coming back. Also I think after the first post to make-admin, following group creations are failing with a 500 and the org gets stuck with the inability to add groups.


Step 1: Post to the make-admin endpoint

![image](https://user-images.githubusercontent.com/8608314/230274474-ff0f8c76-5f95-44d4-9d3e-a0483b0d290a.png)

Step 2: get groups again

![image](https://user-images.githubusercontent.com/8608314/230274533-4085d651-7a6c-4a5d-8939-c5986a68d78c.png)



I'd expect group_admin to be true for the above user. Though it could be I'm making a bad request to make-admin?


A deployment of this can be found at https://flagsmith-staging-chores-manage-groups.vercel.app/

**Comment by kyle-ssg** [comment]
Note, this is managed on the FE with the flag **group_admins**
