### ISSUE TITLE
Paging audit log just increases length of the page rather than changing to new page

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1887]
Note that I can't reproduce this in production but I can reproduce it using the main branch on my local machine. 

gz#376

**Comment by matthewelwell** [comment]
https://user-images.githubusercontent.com/14089968/216367360-f4899834-179c-43b9-afff-7971ece62e59.mov

**Comment by kyle-ssg** [comment]
Can't replicate this, however, I've updated the audit log UI so may as well associate the issue with that.
