### ISSUE TITLE
Upgrade RDS to Postgres 12

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1891]
You can initiate an upgrade of your database instance either immediately or during your next maintenance window to a newer major version of Amazon Aurora PostgreSQL using the AWS Management Console or the AWS Command Line Interface (CLI). The upgrade process will shut down the database instance, perform the upgrade, and restart the database instance. The database instance may be restarted multiple times during the upgrade process. While major version upgrades typically complete within the standard maintenance window, the duration of the upgrade depends on the number of objects within the database. To avoid any unplanned unavailability outside your maintenance window, we recommend that you first take a snapshot [3] or a fast database clone [4] of your database and test the upgrade to get an estimate of the duration. To learn more about upgrading PostgreSQL major versions in Aurora, review the Amazon Aurora updates Documentation [5].  

gz#377

**Comment by matthewelwell** [comment]
Upgrade to pg15 completed on 14/02/2024.
