### ISSUE TITLE
Bad request (status code 400) is not really representative of the error 

### ISSUE THREAD

**Issue by ghost** [SolidStateGroup/bullet-train-api#1895]
Hi,
I tried using Direct API and targeted "Create a Feature" API.

I point that adding a "feature_1" works fine, adding a second feature "feature_2" works fine, but adding the same existing feature "feature_1" returns 
> django.request WARNING  Bad Request: /api/v1/projects/1/features/

I think this is misleading, probably same "Bad Request error, 400" but better with an message about "duplicates".
https://stackoverflow.com/a/3290198

Thanks :)

gz#380

**Comment by matthewelwell** [comment]
Hi @bacloud23, you can see the detail of the error message in the response from the API (as per screenshot below). This warning message in the logs is regarding the request itself. As it's a handled error message, and a response is provided to the client, I don't see the need to provide more information in the server logs. I'm going to go ahead and close this issue based on this. 

<img width="772" alt="image" src="https://user-images.githubusercontent.com/14089968/217772965-6ed1ce92-1cf3-441d-85d3-34bc36b1a780.png">

**Comment by ghost** [comment]
100% my bad, I didn't pay attention to the response object .
