### ISSUE TITLE
create feature fails with wrong error

### ISSUE THREAD

**Issue by prubinVI** [SolidStateGroup/bullet-train-api#1915]
Go to create feature.
Enter an id
Paste a block of text larger than 32k or about into the value
click save
you get an error that the feature id already exists
I believe the correct error should be that the data is too large in the value field.
If you delete parts of the value and keep shrinking it eventually it saves fine.

gz#400

**Comment by dabeeeenster** [comment]
OK sounds like it's just sending the wrong error message - @gagantrivedi to investigate!

**Comment by matthewelwell** [comment]
The API is sending the correct value, the FE needs to inspect the response.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/14089968/217865277-7935476d-02ea-4ff5-aa4f-3d457f34ad6b.png">
