### ISSUE TITLE
Add logic to override sites URL with an environment variable

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1916]
For sending email invites, the application uses the django sites framework to retrieve the base URL it should provide in the URL to accept the invite. It should be possible to override this with an environment variable.

**Comment by Nike682631** [comment]
is this issue available to work on?

**Comment by matthewelwell** [comment]
Yes! We'd love to receive a PR if you're keen to work on it.

**Comment by khvn26** [comment]
Flagsmith now supports `FLAGSMITH_DOMAIN` environment variable – see [docs](https://docs.flagsmith.com/deployment/hosting/locally-api#application-environment-variables).
