### ISSUE TITLE
Unable to import Models types, adding a segment using a plain HTTP request is not working

### ISSUE THREAD

**Issue by ghost** [SolidStateGroup/bullet-train-api#1922]
Hi,
I'm targeting `[POST] ​/api​/v1​/projects​/{project_pk}​/segments​/` api, and for this, I tried constructing a segment using plain JS object as the following:

```js
const segment = {
      id: 3,
      name: 'business team',
      description: 'business users team',
      rules: [
        {
          type: 'ALL',
          conditions: [
            {
              operator: 'EQUAL',
              property: 'licenseClass',
              value: 'business',
            },
          ],
        },
      ],
      project: this.PROJECT_ID,
    };
```

I picked something like the example here 
https://github.com/Flagsmith/flagsmith-nodejs-client/blob/6789a6737d8918c11489a1fdfd0aeb0e633c94cb/tests/engine/unit/segments/util.ts#L16

Unfortunately because I cannot import properly types in my setup (under TS Nest compiler and `import` along with `"esModuleInterop": true,` ( already raised this issue here https://github.com/Flagsmith/flagsmith-nodejs-client/issues/105)

but anyway, the API should work, according to https://api.flagsmith.com/api/v1/docs/

It does work only when I mess with the `conditions` sub-object, and then the segment is added to the project but without the conditions, so somehow my conditions object is not correctly formed.

For instance putting:

```js
conditions: [
                {
                    operator: EQUAL,
                    property_: traitKey1, // <-- Underscore
                    value: traitValue1
                }
            ]
```

Never works, but putting
```js
conditions: [
                {
                    operator: EQUAL,
                    property: traitKey1,
                    value: traitValue1
                }
            ]
```
inserts the segment without any condition.

Final small note along the way, `id` seem not to have any effect, even with a same existing `id` it is just posted incrementally.

Kindly.

gz#419

**Comment by dabeeeenster** [comment]
Moved this to the flagsmith project as it's API related.

**Comment by gagantrivedi** [comment]
> to sum up: the condition working format is conditions[].property_ and not conditions[].property like in the API docs, and the working one doesn't add the conditions altogether for that particular API endpoint

Working format should not be `property_` can you maybe post a curl request?

**Comment by ghost** [comment]
yes indeed, it is simply 
```js
const segment = {
      id: 20,
      name: 'business team jesus',
      description: 'business users team',
      rules: [
        {
          type: 'ALL',
          conditions: [
            {
              operator: 'EQUAL',
              property: 'licenseClass',
              value: 'business',
            },
          ],
        },
      ],
      feature: 4,
      project: this.PROJECT_ID,
    };
    
 const createSegmentUrl = `projects/${this.PROJECT_ID}/segments/`;
 const promise = this.httpService.post(createSegmentUrl, segment).toPromise();
```
I will try to workout a curl request.

**Comment by ghost** [comment]
@gagantrivedi 
```bash
curl -X "POST" "http://localhost:9000/api/v1/projects/1/segments/"  -H 'Authorization: Token ######################'  -H 'Content-Type: application/json; charset=utf-8'  -d '{ "id": "20", "name": "business team jesus", "description": "business users team", "rules": [{"type": "ALL", "conditions": [{"operator": "EQUAL", "property": "licenseClass", "value": "business"}]}], "feature": "4", "project": "1"}'
```

I'm sorry for the format, this is the exact posted object:

```js
{
   "id":"20",
   "name":"business team jesus",
   "description":"business users team",
   "rules":[
      {
         "type":"ALL",
         "conditions":[
            {
               "operator":"EQUAL",
               "property":"licenseClass",
               "value":"business"
            }
         ]
      }
   ],
   "feature":"4",
   "project":"1"
}
```
It  does work without adding a condition.

**Comment by gagantrivedi** [comment]
thanks, @bacloud23,  I will have a look

**Comment by matthewelwell** [comment]
Hi @bacloud23, the UI expects the rules where your conditions live to be nested under a parent `ALL` rule, as you can see from the requests made by inspecting the network tab when using app.flagsmith.com. 

You should modify your request to look as follows: 

```json
{
  "id": "20",
  "name": "business team jesus",
  "description": "business users team",
  "rules": [
    {
      "type": "ALL",
      "rules": [
        {
          "type": "ANY",
          "rules": [],
          "conditions": [
            {
              "operator": "EQUAL",
              "property": "licenseClass",
              "value": "business"
            }
          ]
        }
      ],
      "conditions": []
    }
  ],
  "feature": "4",
  "project": "1"
}
```

**Comment by ghost** [comment]
@matthewelwell ok thanks a lot. 
Meanwhile is it possible to "Associat Features" to a newly created segment ? not only one, creating a "Feature specific" segment, but inherit all the features in an environment and set new values. 
I couldn't spot this in the API.

**Comment by matthewelwell** [comment]
>Meanwhile is it possible to "Associat Features" to a newly created segment ? not only one, creating a "Feature specific" segment, but inherit all the features in an environment and set new values. I couldn't spot this in the API.

Please get in touch with our support team support@flagsmith.com to discuss this. Thanks.
