### ISSUE TITLE
AND and OR buttons in Segment rules UI are confusing

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1923]
It might be better to put them next to each other? Or maybe investigate how other platforms do this sort of thing

gz#421

**Comment by haszankauna** [comment]
hello @dabeeeenster Can I work on this?

**Comment by dabeeeenster** [comment]
Yep sure! This would need some UX work to try and come up with a better/more logical button layout.

**Comment by haszankauna** [comment]
Hello @dabeeeenster can I please get an image of this UI for better clarification?

**Comment by dabeeeenster** [comment]
We havent designed this yet! Happy for suggestions or some research into how other rules builders work

**Comment by kyle-ssg** [comment]
This was picked up during the redesign.
