### ISSUE TITLE
Manage Segments permission does not allow users to create segments

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#1940]
**Describe the bug**
Giving a user / group permissions to Manage Segments does not allow them to create new segments. They see a disabled button and an error message that reads: "To use this feature you need the Manage Segments permission for this project."

**To Reproduce**
1. Log in as a user with Manage Segments permission
2. Attempt to create a new Segment

**Expected behavior**

Able to create a new segment. 

**Screenshots**

<img width="794" alt="image" src="https://user-images.githubusercontent.com/14089968/220168600-2477f393-a56f-4b80-870e-a2616f637052.png">

<img width="613" alt="image" src="https://user-images.githubusercontent.com/14089968/220168915-298c08f5-4fb3-448c-bf56-2ea5c518d269.png">

<img width="579" alt="image" src="https://user-images.githubusercontent.com/14089968/220168892-d8470987-c1cc-4492-b4a8-c59b01da69c1.png">

gz#434

**Comment by kyle-ssg** [comment]
I don't think the frontend work was ever started for manage segments as I can't see reference to it in the codebase. Will add a PR

**Comment by dabeeeenster** [comment]
@kyle-ssg this is not fixed - have just reproduced.

**Comment by kyle-ssg** [comment]
@dabeeeenster I think this can be closed now?
