### ISSUE TITLE
Audit log environment filter doesnt alter UI filter buttons

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1964]
**Describe the bug**
Audit log environment filter doesnt alter UI filter buttons

**To Reproduce**

1. Go to audit log
2. Filter on environment 
3. Button doesnt change appearance

**Expected behavior**
The filter is applied and the filter button changes colour to show it is enabled

**How are you running Flagsmith?**
- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

gz#455

**Comment by alceil** [comment]
Can i work on this? @dabeeeenster

**Comment by kyle-ssg** [comment]
Duplicate of https://github.com/Flagsmith/flagsmith/issues/1920, solved in https://github.com/Flagsmith/flagsmith/pull/1956
