### ISSUE TITLE
Invite URL allows free saas users to break the 1 user limit

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1969]
**Describe the bug**
Create a free saas org, send the invite URL to someone else, they can sign in and join the org.

**To Reproduce**
Create a free saas org, send the invite URL to someone else, they can sign in and join the org.

**Expected behavior**
They are told they are at the seat limit and need to upgrade

**How are you running Flagsmith?**
- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

gz#461

**Comment by kyle-ssg** [comment]
I think assign this to me when this is protected on the API, I may or may not be showing the relevant error when it's implemented.

**Comment by matthewelwell** [comment]
@dabeeeenster this is not just a question for free saas users. This is also a question for paid saas users that are at their seats limit. Do we want to handle it the same way that we handle email invites and simply charge them for a new seat once a user registers via the invite link?

**Comment by dabeeeenster** [comment]
> @dabeeeenster this is not just a question for free saas users. This is also a question for paid saas users that are at their seats limit. Do we want to handle it the same way that we handle email invites and simply charge them for a new seat once a user registers via the invite link?

Yes - charge them as per the email invite
