### ISSUE TITLE
Where's the identity overrides list?

### ISSUE THREAD

**Issue by Roeefl** [SolidStateGroup/bullet-train-api#1972]
![image](https://user-images.githubusercontent.com/10502198/221837499-6cb61f97-29ec-48b8-adc2-3eb698cb5c3b.png)

We used to be able to see for each featureToggle, the list of users that we're overriding the value for in this modal.

We need it badly.

Where's it gone?

Thanks in advance.

gz#464

**Comment by dabeeeenster** [comment]
We don't provide this list in Edge I'm afraid. We are working on improvements to this here https://github.com/Flagsmith/flagsmith/issues/1762

**Comment by Roeefl** [comment]
@dabeeeenster What do you mean by `in Edge`? where did I mention that we were using Edge? 

Plus, If you could please not automatically close my issue 10 seconds after I opened it after giving an unhelpful response? 
We've been paying customers since day 1 of flagsmith for 5 years.

Thanks.

**Comment by Roeefl** [comment]
Anyway what do you mean by don't provide? we've had this feature for years, we use it daily and we still need it.

**Comment by dabeeeenster** [comment]
Sorry! Are you guys running on Edge or Core API? https://docs.flagsmith.com/advanced-use/edge-api

**Comment by Roeefl** [comment]
@dabeeeenster Core AFAIK

**Comment by matthewelwell** [comment]
Hi @Roeefl, just to confirm here - this has now been re-added for Core projects. 

As @dabeeeenster mentioned earlier, this view will not be available on any Edge projects that you might have until we complete the work [here](https://github.com/Flagsmith/flagsmith/issues/1762). 

Feel free to let us know if you have any other questions on this.

**Comment by thalida** [comment]
Could the (current) inability to access the Identity Overrides View for edge projects be added or clarified in the "Things You Should Know" section? 
https://docs.flagsmith.com/advanced-use/edge-api#things-you-should-know

I just completed the migration to edge, and may not have if I'd known it was unavailable.

**Comment by dabeeeenster** [comment]
Thanks @thalida - will add that. We are working on a long term fix for this here https://github.com/Flagsmith/flagsmith/issues/1762 which is on a immediate roadmap
