### ISSUE TITLE
Audit log paging is slow and feels broken

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1993]
1. The audit log generally on first load is slow - maybe an API issue?
2. The paging feels broken due to 1. But we should maybe show a spinner when waiting for a page of results
3. I'm not sure if when turning off/on a filter the list is showing the first page or not? Seems like its not? 

gz#490

**Comment by kyle-ssg** [comment]
I think whatever was causing the api lag has stopped. It seems instant for me, will PR the above though

**Comment by dabeeeenster** [comment]
Its still slow here - try going to Production in Flagsmith Website.

**Comment by kyle-ssg** [comment]
Ah yep, is taking a while. Bit only when filtering on the prod env for the Flagsmith project for me, others seem ok I guess due to fewer logs.

**Comment by kyle-ssg** [comment]
Added PR to address 2/3

**Comment by dabeeeenster** [comment]
@gagantrivedi @matthewelwell for some reason the first load of the audit log in Production in Flagsmith Website project under the Flagsmith org takes ~1.5s to return - it shouldnt I don't think. Are we indexing on date etc?

**Comment by dabeeeenster** [comment]
ahh - maybe we don't have an index on the timestamp? 
<img width="969" alt="image" src="https://user-images.githubusercontent.com/173290/223113385-bda6b485-f44d-49a5-b533-cc031ed98c0c.png">
