### ISSUE TITLE
Frontend email validation preventing password reset

### ISSUE THREAD

**Issue by kagia** [SolidStateGroup/bullet-train-api#2004]
**Describe the bug**
On the frontend email validation fails for valid emails resulting in the inability to reset a password.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Sign-In
2. Click on Forgot Password
3. Enter `user@company.fashion`

**Expected behaviour**
Send button should be active

**Screenshots**
Send button is inactive

**How are you running Flagsmith?**
- [x] Self Hosted with Docker
- [x] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**
I want to propose changing the regex to [this](https://www.regextester.com/115911) which is RFC 5322 complaint.

I'll be happy to make the PR.

gz#504

**Comment by dabeeeenster** [comment]
Yep PR would be great thanks!
