### ISSUE TITLE
XSS issue using butter bar feature

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2013]
Using the `butter_bar` flag available as a flag for the Flagsmith dashboard, it is possible to exercise an XSS vulnerability. 

By giving the flag a value of, e.g. `"><img src=x onerror=alert(document.domain)>.txt`, the dashboard will run the malicious code. 

We can resolve this in the flagsmith dashboard where it renders the value of the butter bar, but it begs the question whether there should be a generic solution available in the flagsmith JS client to sanitise the value of the flag.

**Comment by dabeeeenster** [comment]
I think in the JS SDK it would be nice to have a convenience method that returns an HTML sanitised flag value

**Comment by kyle-ssg** [comment]
RE last comment, should be a separate issue and even then I think that it's probably outside the scope of Flagsmith, if people are using SDKs to render HTML (probably a small percentage) I think it should be down to them to use an appropriate library to interpret remote config data, just like any other language using Flagsmith for SSR.

If we wanted to prevent people from getting into an XSS situation we could probably warn people at the point of saving remote config values.
