### ISSUE TITLE
Offline mode in server side SDKs

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2024]
Each of the Flagsmith server side SDKs should offer a way to have them function in 'offline mode'. By providing a JSON document of flags / an environment, the SDK should behave exactly as it does in local evaluation mode, however, using the static JSON document that should be bundled in the SDK itself. 

This will need to be implemented in all of our serverside SDKs. 

To implement:

- [x] Python (Kim)
- [x] Java
- [x] Go (Gagan)
- [x] Rust (Gagan)
- [x] PHP (Matt)
- [x] NodeJS (Novak)
- [x] Ruby (Zach)
- [ ] Elixir (Kim)
- [x] .NET (Novak)

**Comment by matthewelwell** [comment]
This logic has been implemented already in the client side JS SDK but here we're specifying that we only want to add it to the server side SDKs. 

The question, I guess, is whether we want to implement this in more SDKs than server side SDKs. Would this functionality be useful for e.g. Kotlin, Swift, Flutter? 

Related issue #1655

**Comment by matthewelwell** [comment]
Once question here is whether, for server side SDKs, they should be able to handle segmentation as well in offline mode. I would argue that they should be able to. This would mean that this change could simply be that the environment document should be able to be read from the file system, rather than only from the API. 

Thoughts @khvn26 @gagantrivedi @dabeeeenster ?

**Comment by dabeeeenster** [comment]
Yep this seems like a simple approach that would work

**Comment by matthewelwell** [comment]
2 implementation approaches here: 

https://github.com/Flagsmith/flagsmith-python-client/pull/50
https://github.com/Flagsmith/flagsmith-python-client/pull/51

I think the single client class is slightly neater, but does technically break certain software engineering rules about only having a single purpose. A lot of the arguments passed to the constructor become redundant when using offline mode. 

There is perhaps an argument to say, however, that the offline handler shouldn't be restricted to 'offline mode' and that it should be possible to use it instead of the default handler. In which case, the single client class is certainly the correct approach.

**Comment by dabeeeenster** [comment]
How about making `api_url` optional and configuring the file path in the handler instance, and adding an option to fall back to offline not just when `api_url` is `None` but e.g. in case of network errors?

**Comment by matthewelwell** [comment]
Python reference implementation is here: https://github.com/Flagsmith/flagsmith-python-client/pull/50

**Comment by matthewelwell** [comment]
@novakzaballa @gagantrivedi @zachaysan can you add the docs for the SDKs that you worked on for this. Reference PR for the docs is [here](https://github.com/Flagsmith/flagsmith/pull/3622).

**Comment by zachaysan** [comment]
@matthewelwell Added the ruby ones in this PR: https://github.com/Flagsmith/flagsmith/pull/3677

**Comment by matthewelwell** [comment]
This is now complete in all repositories except Elixir. I have created a separate issue in the repository [here](https://github.com/Flagsmith/flagsmith-elixir-client/issues/37).
