### ISSUE TITLE
Analytics raw data should be pruned after a certain age

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2031]
We should have an Env Var called something like `ANALYTICS_RAW_DATA_PRUNE_AFTER_DAYS` which takes number (in days). Any raw data that is older than the set number of hours should be deleted from the database.  

Suggest default setting is `168` (1 week) and setting value to 0 persists data forever. 

## Acceptance Criteria

 - [ ] Analytics data after configured age is no longer stored in the `_raw` DB tables
 - [ ] Changing the value of the environment variable increases / decreases the retention period
 - [ ] No data is removed from the database when the retention period is set to 0 or not set

**Comment by gagantrivedi** [comment]
Implemented here: https://github.com/Flagsmith/flagsmith/commit/8c8ce1f60478de197b95fc148abcaed680f2c5e5
