### ISSUE TITLE
Fix common create account E2E failure

### ISSUE THREAD

**Issue by kyle-ssg** [SolidStateGroup/bullet-train-api#2056]
**Describe the bug**

Currently the E2E keeps failing at create account with PR. At the moment I think this is due to a network request that's timing out.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/8608314/226620728-4cc8ab1a-eb40-4508-b242-a963fcc82dab.png">

**To Reproduce**

1. Run E2E
2. E2E Fails

**Expected behavior**

1. it passes

**Suggested resolution**

- @matthewelwell or whoever can, create a PR where the server logs out requests to a place I can see in GH actions
- @kyle-ssg Diagnose issue based on E2E failure 
- Fix on FE or BE (wherever it happens to be)

**Comment by dabeeeenster** [comment]
No idea how we would get server logs into GH - any ideas @matthewelwell @gagantrivedi ? Maybe in Sentry?

**Comment by matthewelwell** [comment]
I guess really we just want timings here? So just logging the access logs will probably be sufficient. We can log those to stdout and just look at the logs in the workflow run I think. I'll have a go at doing this.

**Comment by kyle-ssg** [comment]
I've dug deeper into this and have found the following:
When it fails, it seems that at the point of trying to register the API is unreachable causing rest calls to fail and the browser error "failed to fetch". I've listed endpoint calls that don't result in a response in 2 failing tests here:

https://github.com/Flagsmith/flagsmith/actions/runs/4980790447/jobs/8915013414#step:3:2342

https://github.com/Flagsmith/flagsmith/actions/runs/4980790447/jobs/8916257546#step:5:596 

The user registers then calls the following endpoints prior to trying to accept an invite, it looks like any (maybe all) of these fail because the API is unreachable:

- organisations
- users/me/
-auth/mfa/user-active-methods/

Since it always happens in this test, I can't think of anything except that a prior test (maybe sending the invite) is causing the API to go down?
