### ISSUE TITLE
Implement a JS client side OpenFeature provider

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2066]
As per https://docs.openfeature.dev/docs/reference/technologies/client/web/

Related SDK issue: https://github.com/Flagsmith/flagsmith-js-client/issues/156

**Comment by luk355** [comment]
@dabeeeenster, what about other languages? Are there any plans adding OpenFeature support there too? I am mainly interested in [.NET](https://github.com/Flagsmith/flagsmith-dotnet-client) & [Flutter](https://github.com/Flagsmith/flagsmith-flutter-client).

**Comment by dabeeeenster** [comment]
Flutter doesnt have an OpenFeature SDK just yet but I will add an issue for .Net! Happy for contributions too!

Related: https://github.com/Flagsmith/flagsmith/issues/2361

**Comment by matthewelwell** [comment]
@kyle-ssg I think you added a PR for this, can you link here?

**Comment by kyle-ssg** [comment]
Closing this given we now have a JavaScript Provider
https://www.npmjs.com/package/@openfeature/flagsmith-client-provider
