### ISSUE TITLE
API - Include tags in flags responses

### ISSUE THREAD

**Issue by alexg-axis** [SolidStateGroup/bullet-train-api#2075]
**Is your feature request related to a problem? Please describe.**

We're exposing a couple of types of flags, meant for different types of identities. Let's say we've got identities prefixed with `user-` and `organization-` and tagged flags `user` and `organization` in order to easily be able to filter them.

It can be cumbersome to perform extra requests to retrieve this information and correlate it on your own.

**Describe the solution you'd like**

When performing an API request to retrieve flags, one only retrieves all of the flags with no way of telling what tags they have. It would be nice to be able to retrieve the flags and their tags from a single request to more easily filter them in the client.

It would be even nicer to be able to provide the tag(s) one wish to filter by in a query parameter and have the filtering done server-side.

**Describe alternatives you've considered**

1. Using existing APIs.

It's currently possible to retrieve tags and feature flags with two separate requests, correlate them to arrive at what flags have what tags and then, once an identity requests its flags, add the tags. Unfortunately this involves either storing and invalidating a cache, or performing three request per client request.

2. Using an environment per identity type.

Unfortunately this can scale poorly (in terms of flag management) depending on how many environments you normally have. Say you have three environments, by creating one for users and one for organizations, you've now got six.

**Additional context**

In our case, retrieval of flags is done via an authenticated gateway to flagsmith.

**Comment by matthewelwell** [comment]
Hi @alexg-axis, thanks for submitting this issue. We already have a similar issue in our backlog here: #430 so I'm going to go ahead and link this one to it and close it as a duplicate.
