### ISSUE TITLE
Move environment document serialization out of engine to Core API

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2079]
Currently a lot of the serialization for environment documents lives in the django engine. This should be moved to the Core API to make testing / optimisations easier.

**Comment by khvn26** [comment]
The refactoring steps will be as follows:

### 1. Breaking `flag_engine` release

Draft PR here: https://github.com/Flagsmith/flagsmith-engine/pull/167

- Remove `flag_engine.api` module
- Move dataclasses to Pydantic, export them to library's `__init__`/`__all__`
- Remove marshmallow schemas and document 

### 2. Edge API release

- Bump `flag_engine`
- Decouple Edge API schemas from `flag_engine`'s schemas

### 3. Core API release

- Bump `flag_engine`
- Add logic from `flag_engine.api` module to `map_environment_to_document` interface
