### ISSUE TITLE
Switch dark_mode doesn't work while using flagsmith-on-flagsmith

### ISSUE THREAD

**Issue by mlunax** [SolidStateGroup/bullet-train-api#2085]
**Describe the bug**

The user's trait `dark_mode` doesn't impact on front-end.
The dark mode switch doesn't switch and only works until refresh.

**To Reproduce**

1. Use [flagsmith-on-flagsmith](https://docs.flagsmith.com/deployment/overview#running-flagsmith-on-flagsmith)

**Expected behavior**

The dark_mode flag/trait changes front-end dark mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/11018865/229014430-23dae360-6d10-4907-a700-ec95bf0717c4.png)
![Screenshot_20230331_052038](https://user-images.githubusercontent.com/11018865/229014609-d88b518b-6e99-4b83-b371-e4583179fb75.png)
(e-mail trait was erased by me on the screenshot)

**How are you running Flagsmith?**

Self Hosted with Docker

** Additional Notes **
When the whole environment has set `dark_mode` flag then page loads with dark styles but dark mode switch cannot change it to back.

**Comment by matthewelwell** [comment]
Hi @mlunax there are instructions for getting dark mode working here: https://docs.flagsmith.com/deployment/overview#dark-mode. Let me know if you are still having issues after you have followed the instructions here.

**Comment by mlunax** [comment]
Yes, I done it.
