### ISSUE TITLE
Investigate re-implementing key SDK endpoints using Django Ninja

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2112]
I'd like to run a test to see what performance improvements could be achieved by replacing the DRF class based views currently in use for the core SDK endpoints (e.g. `/flags`, `/identities`, etc.) with Django Ninja. 

Some other considerations here: 

 1. Should we consider splitting these endpoints out to a separate service, even for self hosted? Can we do this without complicating the self hosted setup? 
 2. This could link well with #1954 as well, since retrieving the data from a shared cache would allow us to implement the requests async (although vanilla django views technically also allow this now)

**Comment by khvn26** [comment]
Django-Ninja does a great job marrying Pydantic models with Django's routers and ORM, and it's fair to expect significant performance gains from replacing DRF's serializers with Pydantic. However, one thing I've noticed about Django-Ninja's [benchmarks](https://github.com/vitalik/django-ninja-benchmarks) is that they don't include the usual meat of Django views, ORM operations. 

I decided to profile `/v1/identities` and `/v1/flags` to determine the percentage of request time spent on serialization. It amounts to ~7% of the total request time. We can assume that the ~90% performance gain attributed to Pydantic will shave off ~3% of total request time. This deems the proposed refactor impractical.

When profiling I did identify a low-hanging fruit in terms of performance optimization: #2165 

I think, however, that it's not fair to approach Django-Ninja exclusively from a performance standpoint. In my opinion there are other gains to consider:

- Transition from the bulky class-based views to function-based views. Less Django-specific code.
- Mandatory type annotations, Pydantic dataclass schemas and automatic API documentation.

What I'd love to see in Flagsmith is lean views and models, with business logic encapsulated in a service layer. This should vastly improve code readability, maintainability and testability, and Django-Ninja's approach could help maintain the transition.
