### ISSUE TITLE
Soft deleted Integration key can not be added again

### ISSUE THREAD

**Issue by novakzaballa** [SolidStateGroup/bullet-train-api#2129]
Seems like there is a bug here caused by the fact that we have added SoftDelete to the integrations model but not updated the unique constraint. So, since there are entities in the SegmentConfiguration model table still (although they've been deleted), it is not possible to add any new ones. We need to update the unique constraint to only check for entities that do not have a value for deleted_at.

**Comment by khvn26** [comment]
Alternatively we might want to use upsert with undelete when adding integration keys. This way we won't have to migrate the constraint. I don't think we need to store the deleted keys indefinitely.

**Comment by dabeeeenster** [comment]
@matthewelwell can we close this?

**Comment by matthewelwell** [comment]
Closed by https://github.com/Flagsmith/flagsmith/pull/2217.
