### ISSUE TITLE
Migrate to Poetry

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#2150]
Python packaging [isn't solved yet](https://github.com/mitsuhiko/rye/discussions/6) but [Poetry](https://python-poetry.org/docs/) is the most popular closest-to-the-solution thing out there.

With Poetry, we'll get:

- Dependency locks.
- Automatic venvs.
- Python version pinning.
- Runtime and dev dependencies managed in `pyproject.toml`.
- Neat build targets in a future `Makefile`.

## Migration checklist

- [ ] `api` project is Poetry-installable.
- [ ] Build isn't broken for both `Dockerfile`s.
- [ ] All `api-` and `platform-` workflows are not broken.
- [ ] Update documentation

**Comment by tushar5526** [comment]
Hi folks, I am interested to solve this one. Should this be a one big PR or broken into multiple small PRs?

**Comment by dabeeeenster** [comment]
I don't think there are TOO many things to change here? So I would go for 1 PR.

**Comment by tushar5526** [comment]
I think I forgot to add the documentation updates with the PR.

**Comment by matthewelwell** [comment]
> I think I forgot to add the documentation updates with the PR.

Ah yes, could you submit a separate PR with that?

**Comment by tushar5526** [comment]
I can't seem to find any docs for it, where should I put it ? 

I think basic instructions to setup the project, and running tests is enough

**Comment by dabeeeenster** [comment]
https://docs.flagsmith.com/deployment/hosting/locally-api 
and
https://docs.flagsmith.com/platform/contributing 

Thats all I think!

**Comment by dabeeeenster** [comment]
hey @tushar5526 - just checking to see if you are still planning on working on the docs? No problem if not, but we don't want to duplicate your work - thanks!

**Comment by tushar5526** [comment]
I would love to do it, but I won't be able to do it till the weekend.

**Comment by dabeeeenster** [comment]
OK sure no problem - thanks for the reply
