### ISSUE TITLE
On/Off switches overlap large feature flag names on Compare Environments view

### ISSUE THREAD

**Issue by novakzaballa** [SolidStateGroup/bullet-train-api#2184]
**Describe the bug**

In the Compare Environments view, used to compare feature flag changes across environments, the On/Off switch icon, overlaps the very large feature flag names.

**To Reproduce**

1. Create a feature flag with a very large name like `this_is_an_example_of_a_very_large_feature_flag_name`
2. In the Project left menu, Click on 'Compare'
3. Select two environments
4. See that the On/Off switch icon overlaps the large feature flag name.

**Expected behavior**

In the Compare Environments view, the On/Off switch icon should not overlap large feature flag names. Instead, large names should be cropped and an ellipsis should be shown at the end. Another alternative is to break the large names into new lines.

**Screenshots**

![image](https://user-images.githubusercontent.com/41410593/236306307-b135a686-0b8a-4e2f-a529-ff3dc59473ac.png)

**How are you running Flagsmith?**

- [X] Self Hosted with Docker
- [X] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way

**Comment by novakzaballa** [comment]
@kyle-ssg we would like your opinion on how to address this issue. So far we think we could re-layout the screen so we can take advantage of some unused space. Even with that fix, we need to determine how to proceed when the text is large enough to overlap the switch icons. We could truncate the text, show ellipsis and show the full text in a tooltip, however, the current behavior shows a tooltip on mouseover containing the feature flag description. @matthewelwell suggested that we could add a search textbox in that panel so the user can be sure we are displaying the right flag. What do you think?

**Comment by kyle-ssg** [comment]
@novakzaballa We can push the 2 switches right up to the end and allow for the text to wrap to 2 lines in the rare case it’s long enough. We are in the process of creating a design system and this page has been highlighted so I think if we are to address this now we should not spend too long dwelling on how to do so.

**Comment by matthewelwell** [comment]
@kyle-ssg we also need to consider values here as well, not just toggles. 

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/14089968/236460972-a38b0739-52db-4fa0-9e33-577127c8f668.png">

I agree that we shouldn't spend too much time here, but I'm keen not to add in further degradations. we can push things over a little bit but we'd want to try and make sure that the toggles are all still aligned I guess? As opposed those features with values being aligned differently. 

I guess regardless, the text wrapping is probably the best solution here and, if we can without too much trouble, squeeze the toggles and values over towards the right had side of the screen as much as possible.

**Comment by novakzaballa** [comment]
What if we always display the toggles in the first line and values in the second line, and if the text is too long we wrap it into 2 lines? In that way, we would keep a standard height and we will gain some horizontal space, but of course, we would lose some vertical space and we would display fewer feature flags.

**Comment by matthewelwell** [comment]
@novakzaballa I think that makes sense. Could you implement that and share a screenshot here?
