### ISSUE TITLE
Enforce unique tags

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#2189]
**Is your feature request related to a problem? Please describe.**

Currently, tags are not unique:

![image](https://user-images.githubusercontent.com/979078/236812614-fdcce801-9fd9-4ef6-af05-6566755485c2.png)

Since we intend to provide the ability to filter flags by tag labels for #430, we need clearer UX for setting tags in the Flagsmith UI.

**Describe the solution you'd like**

1. Enforce a unique `label` constraint in the Django model.
2. Add a data migration to merge existing duplicate tags.

**Describe alternatives you've considered**

Filtering by tag ID in SDK would require UI changes to communicate the tag IDs to user and overcomplicate the user experience.

**Comment by matthewelwell** [comment]
A quick query on the production database shows that there are only 5 instances where we have non-unique labels in a project. 3 of which are clearly test data.
