### ISSUE TITLE
Add a diff viewer for feature values in change requests

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2191]
**Is your feature request related to a problem? Please describe.**

When creating a change request for a feature that has a large JSON value, it's hard to see what's changed in the Flagsmith UI. 

**Describe the solution you'd like**

A diff viewer for the value of a feature in a change request. 

**Describe alternatives you've considered**

N/a

**Additional context**

N/a

**Comment by kyle-ssg** [comment]
@matthewelwell I've closed this as it got merged a while back, feel free to re-open if it's not working as expected.
