### ISSUE TITLE
Add a "Compare Identities" tab to our Compare page

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2196]
**Is your feature request related to a problem? Please describe.**

It would be good to compare flag values for two different Identities.

**Describe the solution you'd like**

Add a tab in the Compare area that allows you to select 2 identities and see the difference in flag states between the two Identities.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by khvn26** [comment]
Based on feedback from Crisp:

1. Could we not have the view limited to 2 identities?
2. Could we add an ability to compare specific features?
