### ISSUE TITLE
When a paid SaaS account is cancelled, we should remove all but the first user from the account

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2197]
Currently cancelling a paid SaaS account doesnt remove any of the users/seats from the Organisation. Upon receiving the Account Cancelled webhook from Chargebee, we should remove all but the first Flagsmith user associated with the Organisation.

## Acceptance Criteria

 - [x] When a subscription that is linked to a Flagsmith organisation is cancelled in Chargebee, all but one users should be removed from the organisation in Flagsmith
 - [ ] (To verify if possible) Warning text is displayed with the cancel account logic to confirm that all but one users will be removed from the account in Flagsmith

**Comment by matthewelwell** [comment]
Related to [#1822](https://github.com/Flagsmith/flagsmith/issues/1822)
