### ISSUE TITLE
Multivariate value UI issues - values don't wrap after exceeding character limit

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2243]
See video demonstration of the issue:

https://github.com/Flagsmith/flagsmith/assets/14089968/cf12f059-dcbc-4725-88c3-59bd771e34b8

Ideally, values should wrap onto the next line, allowing users to define more complex JSON structures in their multivariate features. Some other alternatives would be: 

 1. Fix the width and height and add scroll bar(s). This is not ideal as it makes JSON management very difficult. 
 2. Add a secondary modal to edit the value (maybe overkill?)

**Comment by khvn26** [comment]
If we go with option 1, we could think of user-controlled line wrapping which should not be hard to implement.

Additionally, we could integrate something like [CodeMirror](https://codemirror.net/) to fully off-load things like format linting, highlighting, etc.

**Comment by dabeeeenster** [comment]
Modals on our modals? 
![image](https://github.com/Flagsmith/flagsmith/assets/173290/eb2327af-5516-4e55-b49c-b47ded81958b)

**Comment by dabeeeenster** [comment]
> If we go with option 1, we could think of user-controlled line wrapping which should not be hard to implement.
> 
> Additionally, we could integrate something like [CodeMirror](https://codemirror.net/) to fully off-load things like format linting, highlighting, etc.

Yep might be time for a proper widget for this?

**Comment by matthewelwell** [comment]
Next steps here would be to investigate the issue and determine a feasible solution as per the options suggested in the description (or another option).
