### ISSUE TITLE
Cache invalidation upon updates / 2nd level caching

### ISSUE THREAD

**Issue by gabfssilva** [SolidStateGroup/bullet-train-api#2248]
**Is your feature request related to a problem? Please describe.**

Hibernate offers a very similar feature referred to as '2nd level caching'. Since I haven't come across a more appropriate term, I'll use it from now on.

That said, I'd like to clarify that not having it is definitely not problem, but rather a missing feature: there's no cache invalidation upon saving.

Currently, invalidations are time-based. For instance, if changes occur in the flags endpoint, the API will continue to return the outdated value until the timeout expires. This is mostly bad because it forces the developer to set a short timeout value. The issue with short-lived cache entries is that they aren't useful in all the scenarios. In scenarios where I need to check a single feature flag against thousands of unique identities, not having these identities cached can significantly reduce performance, especially when compared to relying only on environment flags rather than identity-based ones.

**Describe the solution you'd like**

2nd level caching essentially acts as a caching layer for both get and update operations. Invalidating the cache upon an update, for instance, makes it possible to set higher timeouts for all the cache entries, making it less likely to miss a key in the cache upon later retrieval. This would provide a **_huge_** performance boost in exchange for a most likely larger cache instance.

**Describe alternatives you've considered**

Using the default cache is sure very useful for lots of scenarios and that's what I've been using, but it lacks to solve those specific situations I mentioned before.

**Additional context**

I'm not an expert in Python or Django, so I may be recommending something not very suitable for this situation, but it seems that [django-cacheops](https://github.com/Suor/django-cacheops) would possibly solve this, except the fact it uses Redis exclusively, so I understand it could be a deal-breaker if the idea of Flagsmith is to be cache-provider agnostic as it is today.

**Comment by dabeeeenster** [comment]
Hi @gabfssilva - can you elaborate on which exact endpoints you are talking about here?
