### ISSUE TITLE
Protected features UI

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#2250]
**Is your feature request related to a problem? Please describe.**

UI for #430 does not exist.

**Describe the solution you'd like**

When creating, updating, and viewing features, we need an ability to view and modify a feature's `is_server_key_only` value.
I propose we call the checkbox "Protected feature".
The help text should be something like: "Prevent this feature from being accessed with client-side environment keys."
 
**Additional context**

`is_server_key_only` is available to the following endpoints:

- `/api/v1/projects/{project_id}/features/`

**Comment by kyle-ssg** [comment]
Will be live under the feature flag **is_server_key_only**
