### ISSUE TITLE
Alert on long Edge API lambda duration 

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#2260]
**Is your feature request related to a problem? Please describe.**

Currently, customers are reporting high latency before we know about it. This can and should be changed by setting up proper alerts.

**Describe the solution you'd like**

Set an alert to detect maximum lambda duration growth and spikes.

**Comment by dabeeeenster** [comment]
Hmm - this is actually very hard to achieve with regular cloudwatch - maybe impossible? Would this be better dealt with in Sentry? @khvn26
