### ISSUE TITLE
Allow webhooks to be created even if they use a domain like https://benisskill/webhook

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2262]
Currently you have to have a webhook service up and running in order to create the actual webhook on the Flagsmith side. We should change this to allow users to create the webhook, but warn them on creation that the service is currently not reachable on their side. 

<img width="633" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/7e54192b-2341-4093-aba5-d4897995849a">

**Comment by haszankauna** [comment]
hello @dabeeeenster could you please expand on this. I'll love to work on this

**Comment by dabeeeenster** [comment]
Thanks @haszankauna ! I'm actually not sure if this is something that needs API work too or can be achieved purely from the front end javascript - maybe either @kyle-ssg or @matthewelwell can provide additional input here?

**Comment by haszankauna** [comment]
Hello @kyle-ssg Could you please provide some input o this?

**Comment by kyle-ssg** [comment]
If I'm not mistaken, the only reason why the screenshot in the issue description throws an error is because it's an invalid URL syntactically. The error is coming back from the API.

If I were to try this with a valid URL that doesn't exist I believe this works fine unless I'm missing something?

![image](https://github.com/Flagsmith/flagsmith/assets/8608314/f7c9cdd0-9b8f-4c80-81b3-ca1083a33d8d)

**Comment by haszankauna** [comment]
Hello @dabeeeenster could you please look to this?

**Comment by matthewelwell** [comment]
Hi @haszankauna thanks for the interest here. As @kyle-ssg mentioned, there is actually no issue here. I am closing this issue based on that.

**Comment by dabeeeenster** [comment]
Hmm - so its validating the actual DNS name, so things like this `https://null/213123` are not allowed. But there might be setups/networks where that domain resolves. So I think the UI is being over-eager here?

**Comment by haszankauna** [comment]
what will you suggest @dabeeeenster 
cc: @matthewelwell

**Comment by kyle-ssg** [comment]
![image](https://github.com/Flagsmith/flagsmith/assets/8608314/ad1b8595-c2fa-4c36-b2d7-9aafc4369356)

Trying the above out I can see that the FE attempts no form of validation before sending the request and the error comes back from the API(attached). If we have to adjust any URL validation then a change would have to be made on the API.
