### ISSUE TITLE
Permissions and session tokens have different lifetime

### ISSUE THREAD

**Issue by Myroslav-mint** [SolidStateGroup/bullet-train-api#2292]
**Describe the bug**

After some time of inactivity, instead of the list of projects, you see the message 
```
Oops!
It looks like you do not have permission to view this environment. Please contact a member with administrator privileges.
```

**To Reproduce**

1. Go to any page with the admin privileges
2. Wait until the permissions token expires 
3. See the error

**Expected behavior**

The user can see the list of projects or you need to re-login

**Screenshots**
![Знімок екрана 2023-06-12 о 11 38 52](https://github.com/Flagsmith/flagsmith/assets/113365388/d2008102-8d13-4914-9a6f-e36ba4576f42)

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

The browser's page reload won't fix the problem but after you navigate to a different route and come back everything is fine

**Comment by dabeeeenster** [comment]
Thanks for the report - we will take a look!

**Comment by kyle-ssg** [comment]
@Myroslav-mint, are you able to provide perhaps different replication steps? We only have 1 token, there's no concept of a permissions token.

**Comment by Myroslav-mint** [comment]
No, the steps are the same. I have seen the error today, so it's still there

**Comment by matthewelwell** [comment]
@Myroslav-mint can you confirm what you mean by 'permissions' and 'session tokens'? Where are you obtaining these tokens from? If you could also provide example curl requests / screenshots to illustrate the issue, that would be a great help. Thanks!

**Comment by Myroslav-mint** [comment]
I didn't dig into the codebase, so maybe the problem is in a different place, but all steps to reproduce and a screenshot with the result are on the first message.

**Comment by matthewelwell** [comment]
@Myroslav-mint I'm sorry, but we are unable to reproduce with the information you have provided. It is not clear what you mean by 'permissions token' or 'any page with the admin privileges'. If you can provide further information about exactly how you are reproducing this issue as per my previous message then we can continue to investigate this. I'm sorry, but without these clarifications we cannot investigate any further. Hope you understand. Thanks!

**Comment by Myroslav-mint** [comment]
Ok, let's try one more time. I have full admin privileges and then I go to any project's page and I can use it as normal. After some amount of inactive time I see this screen, but I still logged in and I still have all privileges as before. Why I see this screen? My suggestion was that something wrong with auth tokens, but you say it's not, so please, try to figure out what is going on. 
![Знімок екрана 2023-08-10 о 11 00 32](https://github.com/Flagsmith/flagsmith/assets/113365388/d1811e5e-8b85-4a7b-a63b-5a37740d986b)

**Comment by matthewelwell** [comment]
'some amount of inactive time' - can you be any more specific here? Is this a few minutes? A few hours? A few days? 

Could you also confirm if you experience this issue using an incognito browser window?

**Comment by matthewelwell** [comment]
@Myroslav-mint if it's a short enough amount of time, a video of your screen to exhibit the issue would be very helpful too.

**Comment by Myroslav-mint** [comment]
Not minutes and neither days. IDK the exact amount of time, but it happens during a workday

**Comment by Myroslav-mint** [comment]
I don't think that incognito mode will affect the behavior because several teammates reported the same issue

**Comment by matthewelwell** [comment]
@Myroslav-mint I'm really sorry but, since we are not able to reproduce it ourselves and no other customers have reported any similar issues, for us to be able to investigate this effectively, we will need your cooperation here.

Please could you try using an incognito browser to access flagsmith for a day. Also, since you mentioned it happens to other teammates, perhaps it is a corporate network issue? Could you try using a mobile network for example instead, or perhaps confirm if this happens when you are not working from an office environment / a VPN? 

Also, please could you confirm how you are able to resolve the issue when this happens? Does it kick you back to the login screen?

**Comment by Myroslav-mint** [comment]
I'll try it in the incognito mode. 

No, this isn't a corporate network issue because we are a full-remote team w/o the corporate network. 

After it happens, I can resolve the issue only by clicking on the logo because it keeps me in a 404 redirection loop on other pages.

**Comment by dabeeeenster** [comment]
Are you able to provide a debug console log with any requests that are returning something other than `2XX`?

**Comment by Myroslav-mint** [comment]
![Знімок екрана 2023-08-16 о 13 32 22](https://github.com/Flagsmith/flagsmith/assets/113365388/3beac013-61ef-4153-bf14-ab34e1d9d674)
here is an example of an error

**Comment by matthewelwell** [comment]
This error is totally irrelevant. Please let us know if there are any non 2XX responses in the network tab of the developer console.

**Comment by Myroslav-mint** [comment]
Is this a reason?
![Знімок екрана 2023-08-17 о 17 02 45](https://github.com/Flagsmith/flagsmith/assets/113365388/119a03e9-fbf9-4ef1-b687-b4f3d0689374)

**Comment by matthewelwell** [comment]
No, that shouldn't be related - but it does indicate to me that something is perhaps happening to your network connection around the time that those requests start failing which _could_ be related. 

Are there any other failing requests?

**Comment by Myroslav-mint** [comment]
No, I don't think so. The tab was idle

**Comment by matthewelwell** [comment]
Hi @Myroslav-mint, I have tried to reproduce this by logging in as your user and leaving a browser tab running all day and I have not experienced the issue you have raised. 

I would recommend trying an incognito window, a different browser and/or a different network. 

Since we're unable to reproduce this issue and this is the only report we've had, I am going to close this issue but, since you have a paid account on our SaaS platform, please feel free to reach out via our support chat widget if you'd like further assistance.
