### ISSUE TITLE
Environment clone overrides other cloned environments

### ISSUE THREAD

**Issue by lcardosol** [SolidStateGroup/bullet-train-api#2299]
**Describe the bug**

When creating a new environment cloned from an existing one, all changes added to the previous existing environment will be reflected into the new one.

**To Reproduce**

1. Click on '+'
2. Select a name for the new environment and an environment to clone from
3. Add a new feature to the previous environment or change one of the existing features.

**Expected behavior**

The value for that feature will be changed only for that environment, and will not be reflected on any environment cloned from the changed one.

**Screenshots**

In the following screenshots, both feature "test_on_dev" and "test_on_dev_2" were added to the Development environment after the Test environment was created, and yet changing them on Development also changes/adds the values to Test

![Screenshot 2023-06-13 at 12 04 19](https://github.com/Flagsmith/flagsmith/assets/125990562/d9d34b99-7feb-48ed-b5aa-928308cad3fb)
![Screenshot 2023-06-13 at 12 04 39](https://github.com/Flagsmith/flagsmith/assets/125990562/d299ca45-f480-4189-9ecc-1d2f06bfebda)

**How are you running Flagsmith?**

- [x] Self Hosted with Docker

**Comment by matthewelwell** [comment]
Hi @lcardosol thanks for getting in touch. I'd like to split your issue into 2 items: 

1. Adding a new feature in the original environment

The features live at the project level. When you create a new feature, it is replicated to all environments with the defaults that you provide. Note that there is a setting in the Project Settings to prevent defaults from being set in other environments called 'Prevent flag defaults'. You can also familiarise yourself a little more with the Flagsmith data model in the docs [here](https://docs.flagsmith.com/basic-features/overview).

2. Updating a feature in the original environment

I am unable to reproduce this. I have attached a screen recording below which shows this does not happen for me. Are you able to provide more evidence here? 

https://github.com/Flagsmith/flagsmith/assets/14089968/c31fa66f-23af-4825-9c7f-bf0cd15b08a9

**Comment by lcardosol** [comment]
> As you said the value doesn't change, I did my test deleting a feature, so I took that as a value change, I'm gonna try disabling the Prevent flag defaults and see if it works

**Comment by lcardosol** [comment]
> Hi @lcardosol thanks for getting in touch. I'd like to split your issue into 2 items:
> 
> 1. Adding a new feature in the original environment
> 
> The features live at the project level. When you create a new feature, it is replicated to all environments with the defaults that you provide. Note that there is a setting in the Project Settings to prevent defaults from being set in other environments called 'Prevent flag defaults'. You can also familiarise yourself a little more with the Flagsmith data model in the docs [here](https://docs.flagsmith.com/basic-features/overview).
> 
> 2. Updating a feature in the original environment
> 
> I am unable to reproduce this. I have attached a screen recording below which shows this does not happen for me. Are you able to provide more evidence here?
> 
>  2299.mov

As you said the value doesn't change, I did my test deleting a feature, so I took that as a value change. I tried enabling the Prevent flag defaults, but it still creates a feature in every environment and if I delete from one i deletes for all others. I guess I need to dig into the docs to understand better. Thank you :)
