### ISSUE TITLE
Unable to delete an organisation if it has committed change requests

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2304]
**Describe the bug**

Organisations that have any committed change requests in them cannot be deleted. 

**To Reproduce**

1. Switch to an organisation that has at least 1 committed change request (or create and commit a CR)
2. Navigate to organisation settings and attempt to delete the organisation
3. Notice that nothing happens and the organisation is not deleted. 

**Expected behavior**

The organisation should be deleted from the platform

**Screenshots**

N/a

**How are you running Flagsmith?**

N/a

**Additional context**

The request to delete the organisation returns a 400 error with `"Cannot delete change request that has been committed."` in the body. This is caused by the code [here](https://github.com/Flagsmith/flagsmith/blob/main/api/features/workflows/core/models.py#L125-L131). We should either find a way to determine if the delete is a cascade delete here, or move this logic to the view.

**Comment by khvn26** [comment]
Looks like the same applies to environments too.
