### ISSUE TITLE
Regenerate action delete 'User' invite links

### ISSUE THREAD

**Issue by luciantimar** [SolidStateGroup/bullet-train-api#2306]
Regenerate invite link action deletes user invite link event if Organization Administrator is selected 

1. Go to 'Organization Setting->Members.'
2. Select "User"
3. Click on 'Regenerate'
4. Confirm the action
5. After this operation the 'Organization administrator' invite link is re-generated but the "User" link disappears.

The expectation is that only the "Organization administrator' link to be regenerated.

Looking at API requests sent from the browser, I have observed that the DELETE request is sent with the user's invite id (OK), but then the POST request is sent with {role:ADMIN} instead of {role:USER} (NOK) and this is causing the creation of a second invite link for ADMIN instead of USER.
And then the GET request returns two ADMIN invite links.

**How are you running Flagsmith?**

- [x] Self Hosted with Docker

**Comment by matthewelwell** [comment]
Thanks @luciantimar, we'll take a look into this.

**Comment by matthewelwell** [comment]
Closed by #2307
