### ISSUE TITLE
Implement bulk Identity Create/Update in Core API

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2315]
https://docs.flagsmith.com/api/bulk-insert-identities-update

Currently exists in Edge API. We should implement it in the core API too. Related to https://github.com/Flagsmith/flagsmith/issues/1667

**Comment by matthewelwell** [comment]
Closing as duplicate of https://github.com/Flagsmith/flagsmith/issues/1212
