### ISSUE TITLE
Helm Charts for Scoutflo

### ISSUE THREAD

**Issue by annaredbond** [SolidStateGroup/bullet-train-api#2330]
Message from [Scoutflo](https://atlas.scoutflo.com/) (who are going to do some content about us and have Flagsmith listed in their directory):

We want to work with your team to build a Sandbox and Deploy solution for Flagsmith in the directory.

Scoutflo Sandbox offers users a free, demo-able version of a COSS product running on a Kubernetes cluster. This can help them visualize the tool and connect to the use case right away. 

Example: [Airbyte](https://demo.airbyte.io/workspaces/55c39a0b-037d-406c-a1ac-00393b055f18/connections).

(Since your team does offer a free trial, this may not be quite relevant at the moment)

All we would need from you would be your Helm Charts (for us to automate it)

Contact Anna for questions

CC: @dabeeeenster

**Comment by khvn26** [comment]
Hi Anna!

We can direct them to https://github.com/Flagsmith/flagsmith-charts!
