### ISSUE TITLE
An actual open source license 

### ISSUE THREAD

**Issue by tomdavidson** [SolidStateGroup/bullet-train-api#2338]
**Is your feature request related to a problem? Please describe.**

Flagsmith is advertised as Open Source, but the license is not open source.  This gives potential users a bait and switch type of experience. In my case, the bait & switch is the end of an evaluation even if ti wasn't about something as important as the license and Open Source. Perhaps this is more of a bug than a feature request.

**Describe the solution you'd like**

Use an existing OSI recognized license. If for some reason that is not possible, make sure the new license meets the fundamental qualifiers of Open Source https://opensource.org/osd/

**Describe alternatives you've considered**

Use the Apache 2 Unleash for feature flag management: https://github.com/Unleash/unleash

**Additional context**

Heard about Flagsmith on SED podcast where the host and Ben also said it was Open Source.

**Comment by dabeeeenster** [comment]
Our license is derived from BSD-3. The only change we have made is in making the RBAC component proprietary.
