### ISSUE TITLE
LaunchDarkly importer

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2348]
Implement a Launch Darkly importer:

- This would ideally be a local script/app that can be run with an LD API key and a FS API key. 
- Read core data from LD
- Write it to FS

It would be nice if we could add this to the FS front end so we just put in an LD key and the importer runs

## Things to figure out

- Mismatch between core entities between the 2 platforms
- LD has a different flag value model to FS - how to manage this? 
- What language to write this in? Maybe javascript?

## Entities to Migrate

- Projects
- Environments
- Flags

## For later
- Segments./Segment rulesets
- Identities
- Identity data

## UX

1. Create an LD API token in LD (not clear what creds are required here)
2. Go to the Flagsmith Import page
3. Paste in the LD key and hit next
4. UI shows a list of LD projects with checkboxes for the list
5. User selects the projects to import and hits next
6. Flagsmith creates an async task to import the selected projects

**Comment by ajhelsby** [comment]
For Launch Darkly's boolean flags the enabled toggle can be used in 2 ways. The default is to have the `on`/`off` toggle set to `true` and `false` respectively as seen in the screenshot below:
![image](https://github.com/Flagsmith/flagsmith/assets/16365948/5865a98f-3d02-4de8-9901-139ced7a9506)

However by changing the default variation you can actually reverse the functionality, like seen below:
![image](https://github.com/Flagsmith/flagsmith/assets/16365948/10478ad0-c6ca-49c9-a11f-54cefe78f9a9)

We need to determine how are most users using the boolean flag and how we'd like it to be represented in Flagsmith

**Comment by novakzaballa** [comment]
![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/14ebf9c7-c04d-422f-98b4-03270253dd38)
![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/5441878f-0794-49fc-8714-b126df317d3b)
![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/d0220eee-b5f3-4112-a7f3-8eca85ddde38)

@dabeeeenster here are the designs

**Comment by dabeeeenster** [comment]
Could we use this widget? 
<img width="1114" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/53251515-8631-4111-9ea5-1c7694cca67b">

**Comment by novakzaballa** [comment]
@khvn26 is it possible to include the project creation as part of the BE work? We can send the new project name. Also, I've seen that the PR says that existing environments will be overridden, however, that's not the case, currently, if the project has existing environments with the same name, like the default Development and Production environments, new environment(s) with the same name will be created.

**Comment by khvn26** [comment]
As discussed internally, to keep things neat, we're keeping project creation out of the LD importer endpoint.

The environments will be _merged_ in the backend during import.

**Comment by novakzaballa** [comment]
Do we have an ETA to have the BE part merged? I can see at least one change request still standing from Gagan in the PR.

**Comment by khvn26** [comment]
Yep Gagan's off today and that thread requires some discussion/alignment so no earlier than Monday.

**Comment by khvn26** [comment]
FYI, @novakzaballa: https://github.com/Flagsmith/flagsmith/pull/2530 has been merged.

I'll open a PR later today re: https://github.com/Flagsmith/flagsmith/issues/2838 which will extend the `LaunchDarklyImportRequest.status` schema but keep the changes backwards compatible.

**Comment by novakzaballa** [comment]
> FYI, @novakzaballa: #2530 has been merged.
> 
> I'll open a PR later today re: #2838 which will extend the `LaunchDarklyImportRequest.status` schema but keep the changes backwards compatible.

Great @khvn26, The UI is ready for review https://github.com/Flagsmith/flagsmith/pull/2837
