### ISSUE TITLE
Adding values and percentage to already existing Feature flag does not work/resolve appropriately (open source helm chart version)

### ISSUE THREAD

**Issue by nishant-shah-social** [SolidStateGroup/bullet-train-api#2353]
**Describe the bug**

I have an open source self hosted flagsmith instance running. I used helm charts to deploy. The version I am running is 2.42.1
I first created a simple feature flag without any values.
I then went ahead editing the feature flag and added two, values:- `off`(control Value) with 0% and `on` with 100%
For all users SDK keeps on returning the control value off, inspite it is 0% exposure

**To Reproduce**

1. Create a feature flag and keep it disabled
2. Edit the feature flag with:-
* Enabled toggle :- ON
* Control Value:- off with 0%
* Add another value:- on with 100%
3. Create a new identity. Retrieve FF's for this identity and verify the data returned for the above flag
4. It returns enabled:true and value: off

**Expected behavior**
It should return value: on because on has 100%

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [x] Self Hosted with Kubernetes:- v2.42.1
- [ ] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

This is critical as it can cause unintended behaviour to the end user and cause business impact
I tried it on SaaS and did not notice this issue

**Comment by matthewelwell** [comment]
Hi @nishant-shah-social, can you please confirm how you're retrieving the flags? Which SDK are you using and which version?

Please provide code to reproduce your issue from the client side. 

Please can you also confirm what the result is if you call the API directly? Something like:

```bash
curl --header "X-Environment-Key: <your key>" "https://flagsmith.yourdomain.com/api/v1/identities/?identifier=an-identity"
```

**Comment by nishant-shah-social** [comment]
@matthewelwell thanks for responding..
This is what is returned by the above API call :-
```
{
            "id": 132,
            "feature": {
                "id": 44,
                "name": "nishant_test_flag2",
                "created_date": "2023-06-27T21:34:58.866353Z",
                "description": null,
                "initial_value": null,
                "default_enabled": false,
                "type": "STANDARD"
            },
            "feature_state_value": "off",
            "environment": 1,
            "identity": null,
            "feature_segment": null,
            "enabled": true
        }
```


Below is the screenshot of the Feature flag definition
<img width="955" alt="Screenshot 2023-06-28 at 09 28 05" src="https://github.com/Flagsmith/flagsmith/assets/4332758/103a238d-3813-4dda-8f06-745c3428b50e">

Also, there is no user or segment override present for this FF
So we are expecting the feature_state_value to be `on` for all users

Hope this helps

**Comment by gagantrivedi** [comment]
By default, features are created with `STANDARD` type, when a user converts the `standard` flag to `multivariate`(by Adding variations to it) or converts a `multivariate` flag back to `standard` (by removing all the variations) Front-end should make a put call (endpoint: `api/v1/projects/3/features/<feature_id>/`) to update the feature type

**Comment by nishant-shah-social** [comment]
@gagantrivedi Thanks for responding. Is there any updates on the bug? 
Also, it seems to be working fine on the SaaS side. So, I was wondering how come the issue is only present on the open source?

**Comment by matthewelwell** [comment]
Hi @nishant-shah-social, this was resolved in 2.57.0 that was released earlier today. 

Regarding your question about why it worked in SaaS and not in your open source version is likely actually down to the fact that the bug was related to the way in which the multivariate feature was created. If you created the feature without any variations first, then added the variations. Those variations were not always picked up in the evaluations. If you created the feature with the variations to start with, those variations would always be evaluated correctly. 

As mentioned, I recommend that you upgrade to v2.57.0 of the flagsmith image to resolve this issue.

**Comment by nishant-shah-social** [comment]
Thanks alot @matthewelwell 
One last question. I see the helm chart here:- https://artifacthub.io/packages/helm/flagsmith/flagsmith still points to 2.42.1. Are there plans to upgrade to that as well to the latest version?

**Comment by matthewelwell** [comment]
@nishant-shah-social , I've opened a PR for this here: https://github.com/Flagsmith/flagsmith-charts/pull/140
