### ISSUE TITLE
Track usage of SDKs

### ISSUE THREAD

**Issue by novakzaballa** [SolidStateGroup/bullet-train-api#2354]
**Is your feature request related to a problem? Please describe.**
We need to collect data about the usage of our different SDKs in order to prioritize, assign resources, and better support them.

Currently, we don´t have usage data about our different SDKs, which makes it difficult to make data-driven decision-making when it comes to prioritizing, assigning resources for maintenance, and better supporting each of them.

**Describe the solution you'd like**
As a technical decision-maker at Flagsmith, I would like to have a usage dashboard/report of all (or various) of our SDKs. Metrics should include total API calls in a period of time, active clients in a period of time, and any other relevant metrics that indicate the overall adoption of SDKs. The data should be displayed in numeric and graphical formats and should include:

- Number of calls from every SDK to the API in a period of time (at least monthly).
- The percentage of every SDK calls regarding the total API calls in a period of time (at least monthly).
- Active customer accounts in a period of time per SDK.
- The history of the number (and percentage) of monthly calls during a period of time of various SDKs (or at least a particular SDK), in order to appreciate its evolution over time.

**Describe alternatives you've considered**
As an alternative, we have collected some usage/download data from different sources including GitHub and package managers associated with the different SDKs, however, those alternatives do not offer the accuracy of the proposed solution, since the different package managers use different metrics for measuring the usage.

**Additional context**

**Comment by dabeeeenster** [comment]
It would be mega useful to be able to name SDKs on Init and send that data - ideally people would send the name of the app and possibly the local environment and version too. We can store this and then slice data to show which apps are generating the most traffic.

**Comment by novakzaballa** [comment]
Is there a way we can extract the client, project, and environment IDs from the Auth Token? Maybe we can somehow pre-process the request to extract that data in the ALB or other layer before the request reach the Influx capture point?

**Comment by dabeeeenster** [comment]
Think we can close this in favour of https://github.com/Flagsmith/flagsmith/issues/2479
