### ISSUE TITLE
Newsletter signup shouldn't show in self hosted version

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2360]
**Describe the bug**

As per screenshot below, newsletter signup option shouldn't show when running the flagsmith self hosted application and registering as a new user. 

**To Reproduce**

1. Run the `flagsmith/flagsmith` image (e.g. 2.56.1)
2. Click on 'Sign up'

**Expected behavior**

The checkbox asking if the user wants to sign up to the twice monthly newsletter should not be shown. 

**Screenshots**

<img width="511" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/14089968/8a641e77-840b-4bb2-a137-12ce26d2fe16">

**How are you running Flagsmith?**

- [x] Self Hosted with Docker
- [x] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

The checkbox is pointless for self hosted installs as it will not be able to make the request to PIpedrive to set the user's marketing information / status anyway.

**Comment by kyle-ssg** [comment]
Closing based on https://github.com/Flagsmith/flagsmith/pull/2494#issuecomment-1655271575
