### ISSUE TITLE
Review whether we need both husky and pre-commit

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2387]
Currently the repository has configuration for both [husky](https://typicode.github.io/husky/) and [pre-commit](https://pre-commit.com/). We should review whether both of these are necessary. As far as I know, `pre-commit` can do everything that `husky` is currently doing but husky [seems to be a JS only package](https://github.com/typicode/husky/discussions/1094).

Some things to consider here: 

 * Would a global makefile be useful? 
 * Can we run a single version of this in a GH action to verify that the changes are conforming to the pre commit rules? e.g. `pre-commit --check`

**Comment by dabeeeenster** [comment]
I think we can remove husky - its not needed any more since we merged FE and BE repos. 

Having a global makefile that runs linting on all the sub folder projects would be good yes.

**Comment by dabeeeenster** [comment]
I think all linting that is driven by actions should be in makefiles rather than split across different runtimes. Will add a new issue and keep this related just to Husky.

**Comment by dabeeeenster** [comment]
ah - there is work committing here which we should all sync on I think https://github.com/Flagsmith/flagsmith/pull/2397

I agree makefiles are maybe the best route here
