### ISSUE TITLE
Test: Roles (permissions) e2e tests

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#2401]
Test that are now run manually before/after deploying roles but should ideally be added to e2e pipelines

Test 1: User permissions check
Step 1: Add a user to the organisation without any permissions
Step 2: observe that user can't view project/view environment(or anything else that needs permissions)
Step 3: Add `VIEW_PROJECT` permission directly to the user
Step 4: observe that the user can view project
Step 5: remove the view project permission and make the user admin
Step 6: user can view the project and create segment

Test 2: Repeat Test 1 with user group instead of adding permissions directly on the user

Test 3: Repeat Test 1 with Role attached directly to the user

Test 4: Repeat test 1 with Role attached to a group 

Test 5: Repeat all the above tests for environment and organisation

**Comment by matthewelwell** [comment]
Superseded by #3854
