### ISSUE TITLE
Screen flickers when searching 

### ISSUE THREAD

**Issue by AphonicChaos** [SolidStateGroup/bullet-train-api#2406]
**Describe the bug**

When using the search functionality, if you search for a term with no matches, the whole page flickers to defender empty results. Furthermore, editing becomes slow, as we refresh the page on each key press. This persists until you clear out the search field.

**To Reproduce**

1. Go to the features page in any environment 
2. Start typing nonsense, such as "assfdsa"
3. Notice that the whole content area flashes before showing no results 
4. Further notice that editing the search text further is slow

**Expected behavior**

Searching should remain responsive regardless of the validity of a search. 

**Screenshots**

https://github.com/Flagsmith/flagsmith/assets/93686/e3380c12-3524-4574-b0e3-b5b37ff82ffe

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [x] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

I intend to contribute a fix for this myself this weekend. Reporting the issue for visibility.

**Comment by AphonicChaos** [comment]
Got *very* busy the last couple of weeks. Working on this now.

**Comment by kyle-ssg** [comment]
This looks to have been fixed as part of https://github.com/Flagsmith/flagsmith/pull/3136. Please reopen if there is replication for this.
