### ISSUE TITLE
Linting coverage is inconsistent between CI and pre-commit

### ISSUE THREAD

**Issue by plumdog** [SolidStateGroup/bullet-train-api#2457]
**Is your feature request related to a problem? Please describe.**

The pre-commit linting applies rules to different files (and maybe different rules entirely) compared to what CI enforces. This means that `main` may well not be "pre-commit clean" as this is not checked on PRs.

This means when I run `pre-commit run --all-files` locally, per https://docs.flagsmith.com/platform/contributing#pre-commit, I see lots of linting changes to files I haven't touched.

**Describe the solution you'd like**

Consistency between the linting coverage and rules locally and in CI.

Eg, either:
- remove pre-commit, change https://docs.flagsmith.com/platform/contributing to instruct to do whatever CI does
- have CI run pre-commit and fail if there are changes

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by matthewelwell** [comment]
https://github.com/Flagsmith/flagsmith/pull/2446 that should be solved by this PR

**Comment by plumdog** [comment]
I think this might be covered by #2446, though that might just be moving the existing linting rules around. Not immediately clear to me if it will make local and CI equivalent.

**Comment by dabeeeenster** [comment]
I think they are equivalent - time will tell I think in this case.
