### ISSUE TITLE
Edit feature Modal goes into recursive open modal loop when clicking `Update Settings` after adding a tag

### ISSUE THREAD

**Issue by Roeefl** [SolidStateGroup/bullet-train-api#2459]
**Describe the bug**

Edit feature Modal goes into recursive open modal loop when clicking `Update Settings` after adding a tag

Video is attached.

**To Reproduce**

1. Click on any feature toggle in the list
2. Go to Settings tab
3. Click `Add Tag` and select any tag
4. Click `update settings
5. See modal re-opening about 10 times loop

**Screenshots**

[Screencast from 18-07-23 14:33:19.webm](https://github.com/Flagsmith/flagsmith/assets/10502198/de33b736-b9b4-4c7c-ba72-fe6930c9decd)

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way

**Comment by matthewelwell** [comment]
@Roeefl - I am not able to reproduce this on any feature. Could you confirm if this is happening for all tags / features? Could you perhaps also confirm if it happens in all browsers?

**Comment by dabeeeenster** [comment]
Can you also try in an incogntio/no plugins browser window.

**Comment by Roeefl** [comment]
Will do and update thank you guys.

**Comment by Roeefl** [comment]
@matthewelwell @dabeeeenster This has stopped happening to me on the same machine & browser. Weird. might've been something interfering I suppose but no idea what.

Thank you for looking into it

**Comment by dabeeeenster** [comment]
Maybe a browser extension or network weirdness
