### ISSUE TITLE
Front End for Edge: Styling is not responsive at sub-full-screen widths

### ISSUE THREAD

**Issue by amark-axcient** [SolidStateGroup/bullet-train-api#2463]
**Describe the bug**

Reducing the width of the browser window to where the Flagsmith instance is rendered to half screen or smaller (if, for instance, you wished to compare multiple instances or environments side-by-side) can cause some elements to overlap and become unreadable

**To Reproduce**

1. Open an instance of an Edge version of Flagsmith that has features or configs populated within an environment
2. Drag the browser narrower until such time as either the user icons or the garbage can icons drop to the next line
3. Find that feature name elements now occupy the same space as the feature meta data elements and it is difficult to read the text in either element.
4. By comparison, the earlier version of Flagsmith from the "Bullet Train" days did not have that problem and was fully responsive to screen size.

**Expected behavior**

As a user I would like the option to set two instances side by side on a screen and still be able to read the data for both, without text elements rendering on top of each other.

**Screenshots**

![Screen Shot 2023-07-18 at 5 10 12 PM](https://github.com/Flagsmith/flagsmith/assets/60012476/24d18f0c-2a36-4c97-8263-b9ddd9c8bb8e)

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com v2.61.0
- [ ] Some other way

**Additional context**

Running in current version of Chrome

**Comment by kyle-ssg** [comment]
These panels are going to be completely revamped in an upcoming PR for our design system epic. I'll close this but reference it just to double check responsiveness (which is part of our process for the epic anyway).
