### ISSUE TITLE
Allow Amplitude integration to communicate with Amplitude's EU API

### ISSUE THREAD

**Issue by macbem** [SolidStateGroup/bullet-train-api#2521]
It's currently impossible to use Flagsmith's Amplitude integration if you're using Amplitude EU.

`https://api.amplitude.com/` API URL [(which is used in Flagsmith)](https://github.com/Flagsmith/flagsmith/blob/main/api/integrations/amplitude/amplitude.py#L16) doesn't share credentials with `https://api.eu.amplitude.com/`. Because of this, using Amplitude via Flagsmith throws `invalid_api_key` when used with EU credentials.

It would be great to have a switch for EU / global Amplitude support.

**Comment by dannydtk** [comment]
Exact reference:

https://github.com/Flagsmith/flagsmith/blob/6541f695dfe8ced8cd4aa6eb3052900e9a473334/api/integrations/amplitude/amplitude.py#L16

**Comment by dabeeeenster** [comment]
Closing in favour of https://github.com/Flagsmith/flagsmith/issues/2522 - please track that issue!
