### ISSUE TITLE
Removing Amplitude integration causes any subsequent additions to fail

### ISSUE THREAD

**Issue by dannydtk** [SolidStateGroup/bullet-train-api#2525]
**Describe the bug**

The first time you add Amplitude integration for a particular Flagsmith environment it's added successfully. **If you try to remove it and add it again by clicking Save nothing happens and the underlying request `POST https://api.flagsmith.com/api/v1/environments/<env_id>/integrations/amplitude/` fails with 500 Server error**.

If you use a fresh environment it works until you try to remove and re-add the integration.

**To Reproduce**

1. Go to `https://app.flagsmith.com/project/<project_id>/integrations` (Integrations tab)
2. Add Amplitude integration
3. Select environment `A`
4. Provide valid Amplitude API key
5. Click on Save
3. Remove the integration you've just added by clicking the red trash bin icon next to it
6. Repeat points 3-5 for the same `A` environment (re-add the integration)
7. Observe how the Save button is getting disabled and nothing happens. You can see in the network tab `POST https://api.flagsmith.com/api/v1/environments/<env_id>/integrations/amplitude/` failing with 500 Server error.

**Expected behavior**

You can successfully re-add Amplitude integration for the same Flagsmith environment.

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Comment by dabeeeenster** [comment]
Related: Sentry Issue: [FLAGSMITH-API-37S
](https://flagsmith.sentry.io/issues/4341518212/?referrer=github_integration) and closed related PR which was merged [#2217](https://github.com/Flagsmith/flagsmith/pull/2217)

**Comment by dannydtk** [comment]
Looks like it was fixed in [v2.54.0](https://github.com/Flagsmith/flagsmith/releases/tag/v2.54.0) but we're still experiencing the issue using the latest v2.63.2 SaaS.

**Comment by dannydtk** [comment]
I can also see the changes to serializers from #2217 omitted Amplitude integration. https://github.com/Flagsmith/flagsmith/blob/da2b4a7128a7b40605eed04774a703839777a841/api/integrations/amplitude/serializers.py#L6
