### ISSUE TITLE
Environment Flag Webhooks show the current date rather than the created date

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2554]
**Describe the bug**

Environment Flag Webhooks show the current date rather than the created date

**To Reproduce**

Go to an environment with an existing webhook (Environment > Settings > Webhooks)

**Expected behavior**

Created date should show created date. Currently shows todays date

**Screenshots**

<img width="280" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/edae9e17-9a27-4cda-9ad2-d5830cb72b6b">

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

**Comment by dabeeeenster** [comment]
Looks like a Frontend error. Getting this:

`https://api.flagsmith.com/api/v1/environments/XXX/webhooks/`

```json
[
    {
        "id": 342,
        "url": "https://fa07-77-101-228-115.eu.ngrok.io",
        "enabled": true,
        "created_at": "2022-11-02T11:38:44.502187Z",
        "updated_at": "2022-11-02T11:38:44.502201Z",
        "secret": ""
    }
]
```

Which was when I created the hook. But the UI is showing https://user-images.githubusercontent.com/173290/257459337-edae9e17-9a27-4cda-9ad2-d5830cb72b6b.png

**Comment by matthewelwell** [comment]
Sorry, how does that make it a backend error? Those dates don't look like the current date to me...

**Comment by dabeeeenster** [comment]
oh actually...
