### ISSUE TITLE
import/export configuration to transfer between  Flagsmith instances.

### ISSUE THREAD

**Issue by laurencefass** [SolidStateGroup/bullet-train-api#2577]
**Is your feature request related to a problem? Please describe.**

I am evaluating Flagsmith running the self-hosted docker container. Writing source code against your SDK's and I would like an easy way import/export all of my configuration state that I have created via the UI to either reimport for repeatable tests against your SDKs, or to be able to transfer some/all configuration state into a paid version of the software either cloud or on-premises.

**Describe the solution you'd like**

To rephrase the above: Add a feature to export snapshots either of entire configuration state, or partials of it, to be able to move configuration between instances, and to be able archive and reimport it on restart of self-hosted container, or to transfer state between self-hosted (evaluation) and paid versions of your software.

My immediate requirement is that I would like to store configuration alongside my source code so I can use it to test my business logic in a repeatable manner without repeating manual setup tests. However I think that being able to setup locally and transfer to either on-prem paid or cloud could benefit others.

Storage in either YAML or JSON seem like most obvious choices.

**Describe alternatives you've considered**

I have only recently started evaluation and don't know what alternatives to share configuration between instances exist. i.e. I don't know if I could achieve this through an existing API, though I would expect it would be a rather complex set of requirements to be able to do this.

**Additional context**

**Comment by dabeeeenster** [comment]
The best place to start here would be https://docs.flagsmith.com/deployment/configuration/importing-and-exporting - would this fulfill your requirements?

**Comment by zachaysan** [comment]
Hey @laurencefass! We're in the midst of creating an import and export tool that should be launched within a month or so. If you're available to prototype the feature early please let us know so we can have you as an early access beta tester.

We're going to close this comment soon, but feel free to send me a message like @zachaysan to get in my feed.

**Comment by hamishhossack** [comment]
@zachaysan we would happily take part in a beta access program for this feature if it's still in development. We are also happy to contribute where possible.

We have a similar set of requirements to this issue.

The current import/export does work but it doesn't provide a full solution as would have hoped.

**Comment by zachaysan** [comment]
@hamishhossack It's taken a little longer to test and get ready that we'd hoped, but it should be released in the next week or two. If you're still interested at that point feel free to ping us here and we'll point you in the right direction.

**Comment by zachaysan** [comment]
@hamishhossack We just launched it live this morning, so please let us know if there are any problems with it. If you go to the project settings you should find the import and export tabs to bring in features across different environments.

<img width="1190" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/222715/115fea38-1177-438d-8328-16952c42270e">
