### ISSUE TITLE
Configurate API to keep flag analytics data but drop API traffic.

### ISSUE THREAD

**Issue by landonjs** [SolidStateGroup/bullet-train-api#2580]
**Is your feature request related to a problem? Please describe.**

All of our API requests to Flagsmith come from internal dapr calls so all the requests are the same. The data isn't useful and generates millions of requests a day. 

**Describe the solution you'd like**
We would like the ability to not keep API requests but still track features and audits. This would keep the DB table smaller and free up cycles in the task processor. 

**Additional context**

https://discord.com/channels/517647859495993347/517647859966017541/threads/1136724109103992912

![image](https://github.com/Flagsmith/flagsmith/assets/17443851/1d61994e-c782-46f8-8b9d-44e7206873c8)

**Comment by dabeeeenster** [comment]
I'm not sure what the best way to configure this is? Maybe as a ENV VAR configurable list that defaults to `[tasks.track_request, tasks.track_feature_evaluation,...]`

**Comment by landonjs** [comment]
That would work 👍

**Comment by matthewelwell** [comment]
> I'm not sure what the best way to configure this is? Maybe as a ENV VAR configurable list that defaults to `[tasks.track_request, tasks.track_feature_evaluation,...]`

We would need to do the configuration at a slightly higher level as there is more logic than just the tasks here, but an env var to control which pieces of analytics are enabled would likely be the best option, yes.

**Comment by sumit-158** [comment]
Can I work on this?

**Comment by matthewelwell** [comment]
@sumit-158 yes, please feel free!

**Comment by sumit-158** [comment]
Can you guide more about the problem and the file location?

**Comment by matthewelwell** [comment]
There should be enough information in the description and the comments already? Perhaps you can make sure you've read and understood those and ask any specific questions you might have? 

Here are some files that will likely need modification: 

https://github.com/Flagsmith/flagsmith/blob/main/api/app_analytics/tasks.py
https://github.com/Flagsmith/flagsmith/blob/main/api/app_analytics/middleware.py
https://github.com/Flagsmith/flagsmith/blob/main/api/app_analytics/views.py

**Comment by SD-13** [comment]
Hey @sumit-158 , are you still working on this issue. If not, please let me know, I want to give it a try

**Comment by sumit-158** [comment]
@SD-13 sure  go ahead!
