### ISSUE TITLE
Unable to authorise list of environments from swagger interface api/environments.

### ISSUE THREAD

**Issue by laurencefass** [SolidStateGroup/bullet-train-api#2594]
**Describe the bug**

I dont know what keys to use to get environments from /api/environments in the swagger interface.

This is probably not a bug but I can't work out the correct combination of keys and its not intuitive from the interface.

I can get flags from /api/flags authorising the swagger page with the following combination which as expected inserts headers into requests.

```
Authorisation = { account Key } 
X-Environment-Key = { environment key }
```

but  this wont authorise  /api/environments as Im trying to use one of the environment keys to get details of all the environments.

Do I need an environment key to get a response from /api/environments? If so wnat would it be? If not, the Account key is not authorising the request properly.

**To Reproduce**

Steps to reproduce the behaviour:

Go to localhost:8000 swagger interface
Authorise page using Private and Public Keys (using account key for private, and a server key for private.
Select swagger: http://localhost:8000/api/v1/environments/
Use swagger interface to GET /api/flags and note correct response 

e.g. 

```
[
  {
    "id": 2,
    "feature": {
      "id": 1,
      "name": "microservice_cache",
      "created_date": "2023-08-01T13:03:05.680252Z",
      "description": null,
      "initial_value": null,
      "default_enabled": false,
      "type": "STANDARD"
    },
    "feature_state_value": null,
    "environment": 2,
    "identity": null,
    "feature_segment": null,
    "enabled": true
  },
]
```
Use swagger interface to GET /api/environments and note error:

```

401Undocumented 
Error: UnauthorizedResponse bodyDownload{   "detail": "Authentication credentials were not provided." }

``` 

**Expected behavior**

With correct combination of authorisation and environment headers I want to be able to get a list of environments from /api/environments

**Screenshots**

**How are you running Flagsmith?**

- [ x ] Self Hosted with Docker (evaluating)
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

**Comment by matthewelwell** [comment]
Please ensure that you're providing the full authorization string, as per the example given in the swagger documentation. You must prefix your api key with `Token `. 

<img width="604" alt="Screenshot 2023-08-07 at 15 26 04" src="https://github.com/Flagsmith/flagsmith/assets/14089968/9cdc0a45-86d3-4268-80df-b1df487f19c6">

**Comment by laurencefass** [comment]
Thank you for your advice. I inserted the Account Token prefixed with 'Token ' and this worked, but not quite as expected. 

e.g.:
```
curl -X 'GET' \
  'http://localhost:8000/api/v1/environments/' \
  -H 'accept: application/json' \
  -H 'Authorization: Token 0d721b71079842e961ce06c0b48f74005c3de4dc' \
  -H 'X-Environment-Key: dRikx3Kj2dopXPJqcrSWEx' \
  -H 'X-CSRFToken: lx1PT5nuQtTmLnnNJHzbUxNtLj7kaO5AL840XPFTUdyWNgk2HOWDOcworqKDstIQ'
```
I can get a result by adding an ID but the results do not make sense and do not fit any REST API contract Ive encountered:

If I set id param to 1, I get a full list of environments  (not filtered by id) , keyed from id=1.

If I change the id param to 2, i get a full list of environments (not filtered by id) , keyed from id=3,

If I change to id=3 I get 


```
[
  "Invalid or missing value for project parameter."
]
```


I don't think the filter on a get should change the id of the response items.

Please note also that the Authorisation token worked without prefixing it for /api/flags but fails for api/environments.

**Comment by matthewelwell** [comment]
I'm not sure that I follow the description of your issue. The swagger documentation shows the query parameters that you can pass. For example, I have added the id of one of my projects here:

<img width="1448" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/14089968/cb1e3c48-a823-42e6-b099-958d2ba81aed">

and got the result as I expect: 

<img width="1324" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/14089968/531c275a-ad74-4bcc-919a-814cbf106d3b">

If you're still having issues, could you provide cURL requests that are failing? Or screenshots from the swagger UI that illustrate the problem. 

To answer your final point, there is more documentation on authentication [here](https://docs.flagsmith.com/clients/rest) which explains the differences between endpoints like `/api/v1/flags` and `/api/v1/environments`.

**Comment by dabeeeenster** [comment]
Ive added https://github.com/Flagsmith/flagsmith/pull/2596 which will hopefully help people understand this a bit better

**Comment by dabeeeenster** [comment]
https://github.com/Flagsmith/flagsmith/pull/2597
