### ISSUE TITLE
Swagger authentication key references are confusing, as is the implicit instruction to prefix keys with 'Token '

### ISSUE THREAD

**Issue by laurencefass** [SolidStateGroup/bullet-train-api#2595]
**Describe the bug**

I have had some issues selecting the correct keys to access swagger endpoints through the authorisation dialog I think due to labelling mismatch between swagger descriptions and the actual key terms used in the Flagsmith app.

I learned [here](https://github.com/Flagsmith/flagsmith/issues/2594#issuecomment-1667966069) that its necessary to manually insert the prefix 'Token ' to get authorisation to work correctly.  If the 'Token ' prefix is required, would it be useful to include it in the Flagsmith application Token string? It is not obvious from the dialog that it needs to be manually inserted.

Regarding my misunderstanding of Private/Account/Public/Environment keys:

I added my Flagsmith account key (not a key for a specific environment) into the private key field, though the descriptive text indicates that it should be an environment key. Is this correct? Would the instruction for the private key be more appropriate to direct the user to the Account key, and prefix with Token, because it is not automatically inserted?  

Regarding private vs public keys: The app starts with multiple default environments (Development and Production) but only one Application key for them both. I assume that there will only be one account key regardless of the number of environments I create.  The private key description states: 'Every time you create a new Project Environment, an environment API key is automatically generated for you. This is all you need to pass in to get access to Flags etc.'. The implication here is that an environment API key should be used as. a private key, but the key format in the example more closely resembles the Account Key, not either of the server or client environment keys. I have found that private key = account key, NOT environment key.

I had initial difficulty trying to copy/paste the the Account key and learned I need to prefix with with 'Token ' [here](https://github.com/Flagsmith/flagsmith/issues/2594#issuecomment-1667966069) and it worked, so I assume that this is not the correct place to enter an environment key.

**To Reproduce**

**Expected behaviour**

Summary: I am assuming 

(i) the Private key is the Account Key and the Public Key is whatever Environment I need write access to, is that correct?
(ii) I have to manually prefix only the Account (Private) key with "Token " to get application authorisation
(iii) I dont have to prefix the environment keys with "Token " to get environment access.

**Screenshots**

**How are you running Flagsmith?**

- [ x] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

**Comment by matthewelwell** [comment]
It's not clear to me what you are raising as a bug here, please can you clarify?

**Comment by matthewelwell** [comment]
@laurencefass please take care to keep your issues on topic. You have created 2 very similar issues and are mixing up the comments across the two now. Please move these latest comments to the correct issue and I will respond to them there.

**Comment by laurencefass** [comment]
ah yes, my apologies, I mixed up responses. Wasnt expecting a response to this one so soon! Ill move the comments across.

For clarity this one is ALL about terms using for public/application/private/environment keys and where to use them.

**Comment by laurencefass** [comment]
To simplify:

1.  If 'Token ' is part of the Account API token, why not include it in the Account API Token here: 
http://localhost:8000/project/2/environment/nGePuVTPasxUTxtvAcTTJu/account

btw if the API token is the same for all environments (which it appears to be) why not just simplify it to: 

http://localhost:8000/account

instead of going through an environment path?

3.  If 'Private key' expects the Account API key prefixed with 'Token ', why not say that and not imply that the environment key is required with the description: 'Every time you create a new Project Environment, an environment API key is automatically generated for you. This is all you need to pass in to get access to Flags etc.'

Thats it I think. I apologise if these are noob questions and I am missing some vital logic.

**Comment by dabeeeenster** [comment]
Fixed by https://github.com/Flagsmith/flagsmith/pull/2597
