### ISSUE TITLE
Add self-hosted docker environment variables for user login credentials to support automated testing

### ISSUE THREAD

**Issue by laurencefass** [SolidStateGroup/bullet-train-api#2601]
**Is your feature request related to a problem? Please describe.**

I am trying to incorporate flagsmith into my integration tests using testcontainers and I would like to be able to programmatically login so that I can obtain an App key to run various REST requests and SDK functions.

The docs suggest I need to manually create a user everytime i run a new docker container instance. I cant rely on volumes for persisting user data. https://docs.flagsmith.com/deployment/hosting/docker

I can see there are a variety of env vars supported: https://github.com/Flagsmith/self-hosted/blob/main/docker-compose.yml, would it be possible to add FLAGSMITH_USER, FLAGSMITH_PASSWORD in a similar fashion to postgres to give a predictable user to login with?

**Describe the solution you'd like**

Include FLAGSMITH_USER and FLAGSMITH_PASSWORD environment variables on the Flagsmith container to create a default user without having to manually register on startup.

**Describe alternatives you've considered**

Doing a postgres DB dump and pulling out the API key. This is obviously less than ideal.

**Additional context**

**Comment by khvn26** [comment]
Fixed by https://github.com/Flagsmith/flagsmith/pull/2205
