### ISSUE TITLE
Tweaks to new side navigation 

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2637]
## Add some padding on Edge button:

<img width="369" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/8ffb798a-e931-491e-a537-158f57fd17a4">

## Reduce vertical padding a little on ALL the nav elements:

<img width="393" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/76f8e8a9-3ffb-458a-b4c2-343afb76b422">

## Add icons back in:

<img width="320" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/b441e191-7c3d-4144-be69-88fd18cc70f8">

## Make this a project switcher (needs desiging I think?)

<img width="487" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/64084247-baa3-44eb-9394-1fb1d992c0d8">

**Comment by OmAximani0** [comment]
Hey, I want to contribute on this issue. Is anyone working on this ?

**Comment by dabeeeenster** [comment]
This is being worked on yes! Sorry!
