### ISSUE TITLE
Broken link on Deployment Overview Docs page

### ISSUE THREAD

**Issue by annaredbond** [SolidStateGroup/bullet-train-api#2651]
https://docs.flagsmith.com/deployment/overview 

Link on "Deploy on Railway" button brings up a 404 page

Creating this issue here because the docs repository is archived and read only

**Comment by dabeeeenster** [comment]
OK I've made a new style Railway template but for some reason it's not building the Dockerfile. Have asked in the Railway Discord.

**Comment by matthewelwell** [comment]
This seems to be working for me now.
