### ISSUE TITLE
Add the ability to assign a feature to a user group

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2666]
Functionality should be as per the current functionality to assign a feature to a user, but for groups. A feature should be able to be assigned to multiple users and multiple groups. 

## Acceptance Criteria

 - [x] When creating a feature via the UI or the API, multiple groups can be assigned to the feature
 - [x] When updating a feature via the UI or the API, groups can be removed or changed
 - [ ] Users can filter the list of features by assigned group

**Comment by zachaysan** [comment]
The third criteria was moved into a new ticket by @dabeeeenster the remaining functionality is here:

https://github.com/Flagsmith/flagsmith/pull/2908

**Comment by zachaysan** [comment]
The API endpoints are in the following format.

To list the groups in an organisation to retrieve the group `id` and `name` pair.
```
HTTP GET
/api/v1/organisations/<organisation_id>/groups/summaries/
```
```json
[
    {
        "id": 1,
        "name": "TestGroup",
    },
    {
        "id": 2,
        "name": "TestGroup2",
    }
]
```


Adding a group to an assigned feature:

```
HTTP POST
/api/v1/projects/<project_id>/features/<feature_id>/add-group-owners/
```
```json
{"group_ids": [1, 2]}
```

Removing a group from being assigned to a feature:
```
HTTP POST
/api/v1/projects/<project_id>/features/<feature_id>/remove-group-owners/
```
```json
{"group_ids": [1, 2]}
```

For both endpoints, the **response body** looks the same, which represents all the now-existing group owners for the feature.

```json
{
  "group_owners": [
    {
      "id": 1,
      "name": "GroupName1"
    },
    {
      "id": 2,
      "name": "GroupName2"
    }
  ]
}
```

To pre-load the group owners for a list of features, find the existing URL structure for the following pattern, with an abbreviated response body for brevity:

```
HTTP GET
/api/v1/projects/<project_pk>/features/
```
```json
{
  "count": 2,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 77,
      "name": "test_feature_empty",
      "group_owners": [],
    },
    {
      "id": 78,
      "name": "test_feature",
      "group_owners": [
        {
          "id": 6,
          "name": "Test Group"
        },
        {
          "id": 7,
          "name": "Second Group"
        }
      ],
    }
  ]
}
```

**Comment by matthewelwell** [comment]
@kyle-ssg just noticed that (unless I'm missing something) this isn't using the new endpoint to retrieve the groups, which will mean that only organisation admins can use this feature. 

```
GET /api/v1/organisations/<organisation_id>/groups/summaries/
[
    {
        "id": 1,
        "name": "TestGroup",
    },
    {
        "id": 2,
        "name": "TestGroup2",
    }
]
```

Please use the above endpoint for this purpose. All users of an organisation will have access to this data.
