### ISSUE TITLE
Badge UI element is too large

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2698]
**Describe the bug**

UI element is too large - the flag value badge and text should be smaller

**To Reproduce**

Create a Multivariate flag. View an identity with a different flag state. 

**Expected behavior**

Font should be the same size

**Screenshots**

<img width="1111" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/ff733eed-924b-4a1d-b66d-9863da55e4e8">

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

**Comment by sebzz2k2** [comment]
Hii,
I am interested in it can you please assign it to me

**Comment by sebzz2k2** [comment]
Hii is anyone working in it.
Can i take it up?

**Comment by hritikkhurana10sm** [comment]
Hi @dabeeeenster can I work on this issue

**Comment by dabeeeenster** [comment]
Just submit a PR thanks!
