### ISSUE TITLE
Comparing values in a Change Request is unclear

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2723]
It's unclear to me which value is the new one and which is the old one. Both values are labelled 'Scheduled Change' which is not true, since the change I have screenshotted below, is not scheduled for the future. 

<img width="223" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/14089968/4285e05f-aadf-446d-a385-989e58dba254">

**Comment by dabeeeenster** [comment]
This is being redesigned

**Comment by matthewelwell** [comment]
@dabeeeenster is there an update on when this redesign is going to happen?
