### ISSUE TITLE
Additional seats not being summed correctly

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2729]
I added 2 additional monthly seats to a SaaS Scale up plan:

<img width="758" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/c2f68dec-7745-4a6b-b7c8-e007750a65c9">

Seats are set to 6:

<img width="833" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/5bdba50d-86cc-4704-b369-a4f5473c4870">

This number should be 7

**Comment by novakzaballa** [comment]
@matthewelwell this one has been tackled by you right?

**Comment by matthewelwell** [comment]
Yep.
