### ISSUE TITLE
Update Webhook button not working

### ISSUE THREAD

**Issue by novakzaballa** [SolidStateGroup/bullet-train-api#2752]
**Describe the bug**

Clicking on the Update Webhook button does nothing.

**To Reproduce**

1. Go to the "Manage" option at the top menu bar
2. Click on the "Webhooks" tab
3. Create a new Webhook or skip this step if you already have a Webhook
4. Edit the Webhook
5. Make changes to the Webhook and try to save the changes by clicking the "Update Webhook" button
6. See that nothing happens. NO call to the API nor related console error.

**Expected behavior**

Clicking the "Update Webhook" button while editing a Webhook should save the changes to the BE.

**Screenshots**

![image](https://github.com/Flagsmith/flagsmith/assets/41410593/ef55f9fd-1a64-4642-812a-3f4cc459ae67)

**How are you running Flagsmith?**

- [] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [X] Some other way (Local dev env)

**Comment by gagantrivedi** [comment]
@novakzaballa  This issue still exists for environment webhooks
