### ISSUE TITLE
FE changes to add/remove User/Groups to/from Roles

### ISSUE THREAD

**Issue by novakzaballa** [SolidStateGroup/bullet-train-api#2754]
**Is your feature request related to a problem? Please describe.**
Currently, the API supports adding users and groups to roles however in the frontend we don't have a way to do it.

**Describe the solution you'd like**

In the management option of the top bar, when the admin goes to the members tab, we should display a roles sub-tab,
When an admin edits a role, a modal is shown, and in the first tab, where the name and description of the role are shown, we need to allow the admin to add and remove users and/or groups to the role.

**Additional context**
Initially, the ability to add and remove users/groups will reside only on the roles sub-tab of the members tab, in the screen shown when an admin clicks on the `Management` top menu option

**Comment by novakzaballa** [comment]
![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/67acad36-eed9-42c5-be07-1728f51ef46a)



![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/e2631155-b912-4e19-8d7d-9122f8f2d902)



![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/db9172c1-dc18-4079-aef2-34219817d1d2)



![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/61048f6f-6956-4ccc-906b-5105c87ecea8)

@kyle-ssg @matthewelwell

**Comment by matthewelwell** [comment]
I think this is fine for now, but might get a bit cluttered for larger teams. We may need to rethink it at that point but, for the initial release, I think this is fine.

**Comment by matthewelwell** [comment]
We'll also need to implement the functionality from the other side - adding roles directly to a user or a group.

**Comment by novakzaballa** [comment]
![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/4c73c8e4-483f-4a01-b12b-599750995b44)



![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/3f272ced-65c1-41fd-9d15-a03c62c19231)

**Comment by novakzaballa** [comment]
The above designs show how we would add roles to users and groups

**Comment by matthewelwell** [comment]
@novakzaballa @dabeeeenster I think this might need a bit more thought from a design perspective. Can you guys organise?

**Comment by novakzaballa** [comment]
@dabeeeenster new designs show how we would add users to roles and manage roles in project and environment

![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/50745369-2b26-41da-98ee-38a0bfd3fc21)
![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/8d7fe893-1da9-444b-a240-e2649f5d1805)
![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/b74a18b1-bf5e-41e8-b072-b5c76547c63f)
![Image](https://github.com/Flagsmith/flagsmith/assets/41410593/d9fb788d-4431-43ca-b4b6-f6c7e3987f1d)

**Comment by dabeeeenster** [comment]
@novakzaballa are these pushed to the PR? Can you link this issue to the PR too?

**Comment by novakzaballa** [comment]
@dabeeeenster this is the PR: https://github.com/Flagsmith/flagsmith/pull/2791

**Comment by kyle-ssg** [comment]
This issue was closed but I believe the "show_role_management" feature should be enabled?
