### ISSUE TITLE
Flags modal shifts main page layout

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2755]
As per video. Note the size of the main table padding. This seems to happen with longer list of features. 

https://github.com/Flagsmith/flagsmith/assets/173290/7d5640cb-b0e2-403d-ae6f-4bfe2a4370ad

**Comment by novakzaballa** [comment]
@dabeeeenster  I couldn't reproduce the issue in any browser.

**Comment by dabeeeenster** [comment]
Looks like it got fixed!
