### ISSUE TITLE
Toggling Archived tag refreshes/flashes page

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2776]
As per video

https://github.com/Flagsmith/flagsmith/assets/173290/e209aeb2-0831-4958-bca4-89765cbdb533

**Comment by matthewelwell** [comment]
I can't reproduce this @dabeeeenster. If you can still reproduce, please let me know.

**Comment by dabeeeenster** [comment]
Yep this was fixed somehow
