### ISSUE TITLE
Embed Albacross script into app.flagsmith.com

### ISSUE THREAD

**Issue by annaredbond** [SolidStateGroup/bullet-train-api#2779]
Please can you help us embed this script in app.flagsmith.com:

[app.flagsmith.com](http://app.flagsmith.com/):
<script>window._nQc="89389862";</script>
<script async src="https://serve.albacross.com/track.js"></script>

More info on embedding: https://help.albacross.com/en/collections/54036-tracking-code-installation

Ask Anna/Mike if you have any questions

**Comment by matthewelwell** [comment]
@novakzaballa I thought something had been done on this, can you confirm?

**Comment by novakzaballa** [comment]
Yes, I can confirm that I made 2 PRs for this. The first one was using our existing tag injection logic, and the second was to use the scripts only when the user is in the signup page, by dynamically injecting and removing it. We merged the latter. We still need to review the privacy policy to ensure Albacross is covered.

**Comment by novakzaballa** [comment]
Closing the issue after attaching the corresponding PR
