### ISSUE TITLE
Logged out of Flagsmith when testing Webhook 

### ISSUE THREAD

**Issue by aleoyakas** [SolidStateGroup/bullet-train-api#2790]
**Describe the bug**

When using the "Test Webhook" functionality for an environment, if the Webhook response has a status code of 401, Flagsmith will log you out. The Webhook settings will still be displayed on the screen.

**To Reproduce**

1. Log on to the [Flagsmith website](https://app.flagsmith.com/projects)
2. Navigate to the Webhook Settings of an environment
3. Click "Create feature webhook"
4. Supply a URL that will return a 401 response
5. Click "Test your webhook"

**Expected behavior**

An error message displays you were unauthorized to access the API, but you remain logged in to Flagsmith.

**Screenshots**

_Before request is sent_
![image](https://github.com/Flagsmith/flagsmith/assets/34274606/e846ac7a-c040-43e2-ba3b-ae621cfe44b1)

_After request is sent_
![image](https://github.com/Flagsmith/flagsmith/assets/34274606/aa0c8e5d-7d4e-40b5-845d-dd4e0d27b2aa)

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

Same issue is present when updating Webhooks

**Comment by novakzaballa** [comment]
Thank you for bringing our attention to this issue @aleoyakas . We will add it to our backlog and prioritize it in our next grooming.
