### ISSUE TITLE
"Stop serving flags" org setting doesnt do anything in Edge

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2804]
<img width="738" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/59836c83-82fe-4a08-8bc9-b050a6f11daf">

Setting this works in core but not in edge

```
❯ ## Get Flags
  curl "https://edge.api.flagsmith.com/api/v1/flags/" \
           -H 'X-Environment-Key: ja9bAnBAtNgHskjf8unsW9'

[{"feature": {"type": "STANDARD", "id": 58028, "name": "test"}, "feature_state_value": null, "enabled": false}]⏎

❯ ## Get Flags
  curl "https://api.flagsmith.com/api/v1/flags/" \
           -H 'X-Environment-Key: ja9bAnBAtNgHskjf8unsW9'
```

**Comment by gagantrivedi** [comment]
It's because stop serving flags toggle on organisation is not updating dynamo document

**Comment by matthewelwell** [comment]
We should add an `AFTER_SAVE` hook on the organisation to rebuild all the environment documents when this flag changes.
