### ISSUE TITLE
Bug: Flagsmith returning 502 on /identities API

### ISSUE THREAD

**Issue by vivonk** [SolidStateGroup/bullet-train-api#2806]
**Describe the bug**
We have integrated the `/identities` API and we are trying to call it with the following payload but there seems some issue with this data - 
Here when identifier is `68385f9726ad05c8e551a8d5be5cd8213f1e733346a9eb00e86f83df94639555`, API returns 502 but when it's any other test identifier it works.
Also, I tried to replicate it with a different env key, there we don't see 502. This is only happening with the env key that we are using.

-> Request
```
curl --location 'https://edge.api.flagsmith.com/api/v1/identities' \
--header 'X-Environment-Key: <key>' \
--header 'Content-Type: application/json' \
--data '{
    "identifier": "68385f9726ad05c8e551a8d5be5cd8213f1e733346a9eb00e86f83df94639555",
    "traits": [
        {
            "trait_key": "instanceId",
            "trait_value": "650c79f77ade126caf5852fa"
        },
        {
            "trait_key": "isTelemetryOn",
            "trait_value": false
        },
        {
            "trait_key": "tenantId",
            "trait_value": "650c79fa7ade126caf585309"
        },
        {
            "trait_key": "type",
            "trait_value": "user"
        },
        {
            "trait_key": "email",
            "trait_value": "68385f9726ad05c8e551a8d5be5cd8213f1e733346a9eb00e86f83df94639555"
        },
        {
            "trait_key": "defaultTraitsUpdatedAt",
            "trait_value": 1695316874
        }
    ]
}'
```

**To Reproduce**

1. Make a request from the above-shared curl with the env key we are using, you will be able to see 502.
2. Now change the `identifier` to any test value and API will work (no 502)

**Expected behavior**
When we are sending the above payload with our env key, we expect it to return 200OK with the right response instead of a 502.

**How are you running Flagsmith?**

- [x] SaaS at flagsmith.com

**Additional context**
Discord conversation link - https://discord.com/channels/517647859495993347/917719343930957846/1154656436220076084

**Comment by khvn26** [comment]
Hi! We've noticed an incorrect trait value is stored for a bunch of your identities under the `"instanceId"` key. Can you share how did you set those initially — e.g., via UI or using a specific API endpoint? Thanks!

**Comment by vivonk** [comment]
@khvn26  we use APIs only to store traits. Although what's the incorrect value that;s being stored? Is it any special char or something like that? Do you mind sharing it?
cc: @NilanshBansal

**Comment by khvn26** [comment]
> we use APIs only to store traits

Would you mind sharing which specific endpoints you use?

> Do you mind sharing it?

Sure. We have the numeric value `65096277351152464000000000000000000000000000000000000000000000000000000000000000000000000000000000` stored in our database. This is likely a result of an erroneous deserialisation, but I could not reproduce it with the `instanceId` value you've provided with the curl. Was there any other value you set earlier?

**Comment by vivonk** [comment]
@khvn26 thanks for sharing this. Let me check both things and get back to you by tomorrow morning IST time.

**Comment by dabeeeenster** [comment]
@vivonk can you describe exactly how you are setting the identities and traits? Are you using an SDK? Are you hitting our API directly?

**Comment by NilanshBansal** [comment]
@dabeeeenster @khvn26 we are using the Flagsmith Java SDK (v6.1.0). The method being invoked is `getIdentityFlags(identifier, traits)`

Ref: https://docs.flagsmith.com/clients/server-side#get-flags-for-an-identity  
cc: @vivonk

**Comment by NilanshBansal** [comment]
> > we use APIs only to store traits
> 
> Would you mind sharing which specific endpoints you use?
> 
> > Do you mind sharing it?
> 
> Sure. We have the numeric value `65096277351152464000000000000000000000000000000000000000000000000000000000000000000000000000000000` stored in our database. This is likely a result of an erroneous deserialisation, but I could not reproduce it with the `instanceId` value you've provided with the curl. Was there any other value you set earlier?

@khvn26 can you please share the unique flagsmith identifier that has this instanceId? 
We only set instanceId which is mongo objectId and always has a 24-character limit. 
cc: @vivonk

**Comment by NilanshBansal** [comment]
@khvn26 @dabeeeenster I believe this is some internal issue within flagsmith, with this unique identifier `68385f9726ad05c8e551a8d5be5cd8213f1e733346a9eb00e86f83df94639555`
Making a request to the flagsmith api with this identifier and our `env key` returns 502 error, but if we change the identifier a bit, the request is successful.
Please check the below screenshots for reference.

<img width="857" alt="SCR-20230926-epr" src="https://github.com/Flagsmith/flagsmith/assets/25542733/69fe8691-4807-48a6-b506-35694eaf11f8">




<img width="1004" alt="SCR-20230926-euc" src="https://github.com/Flagsmith/flagsmith/assets/25542733/a7a72461-c830-4c1a-a12f-33ee368fc9ba">

cc: @vivonk

**Comment by dabeeeenster** [comment]
OK we're looking into this further.

**Comment by gagantrivedi** [comment]
> > > we use APIs only to store traits
> > 
> > 
> > Would you mind sharing which specific endpoints you use?
> > > Do you mind sharing it?
> > 
> > 
> > Sure. We have the numeric value `65096277351152464000000000000000000000000000000000000000000000000000000000000000000000000000000000` stored in our database. This is likely a result of an erroneous deserialisation, but I could not reproduce it with the `instanceId` value you've provided with the curl. Was there any other value you set earlier?
> 
> @khvn26 can you please share the unique flagsmith identifier that has this instanceId? We only set instanceId which is mongo objectId and always has a 24-character limit. cc: @vivonk

@NilanshBansal  every identity that is giving 502 for you have this instanceId. e.g: `68385f9726ad05c8e551a8d5be5cd8213f1e733346a9eb00e86f83df94639555`

**Comment by gagantrivedi** [comment]
Now, we are still trying to figure out how it was ever allowed for that value to reach our DB

**Comment by NilanshBansal** [comment]
> every identity that is giving 502 for you have this instanceId. e.g: 68385f9726ad05c8e551a8d5be5cd8213f1e733346a9eb00e86f83df94639555

@gagantrivedi this is the unique identifier that we are sending not the instanceId right?
Also, is there any limitation on the char limit for a particular trait in flagsmith?

**Comment by gagantrivedi** [comment]
> > every identity that is giving 502 for you have this instanceId. e.g: 68385f9726ad05c8e551a8d5be5cd8213f1e733346a9eb00e86f83df94639555
> 
> @gagantrivedi this is the unique identifier that we are sending not the instanceId right? Also, is there any limitation on the char limit for a particular trait in flagsmith?

Yes, but this identifier has some traits associated with it - one of them is the instanceID with that value

**Comment by gagantrivedi** [comment]
> Also, is there any limitation on the char limit for a particular trait in flagsmith?

Yes, it's 2000

**Comment by gagantrivedi** [comment]
@vivonk @NilanshBansal when was the last time you were able to fetch those identities successfully (if you can recall)?

**Comment by vivonk** [comment]
@gagantrivedi Before 19th Sep, we were able to fetch these identities successfully and no errors were coming from Flagsmith side

**Comment by gagantrivedi** [comment]
> @gagantrivedi Before 19th Sep, we were able to fetch these identities successfully and no errors were coming from Flagsmith side

That's interesting because our last release was on 12th September. Nothing changed on our side after that

**Comment by gagantrivedi** [comment]
@vivonk  apart from `68385f9726ad05c8e551a8d5be5cd8213f1e733346a9eb00e86f83df94639555`, is there any other identity you can't fetch flags for?

**Comment by gagantrivedi** [comment]
@vivonk  we have removed the instaceID trait from `68385f9726ad05c8e551a8d5be5cd8213f1e733346a9eb00e86f83df94639555`, you should be able to access it now

**Comment by NilanshBansal** [comment]
Thanks @gagantrivedi the issue is fixed for the above identifier. 
Can you please help me with answers to the following questions: 

- What was the root cause of this issue?
- How can we ensure this issue doesn't occur for the other identifiers? Are there any measures we can take to avoid this in future?
- You mentioned, the char limit is 2000 for a trait, but we sent the instanceId trait with 64 chars, how could that cause this to happen?  

> Now, we are still trying to figure out how it was ever allowed for that value to reach our DB
- Also, is the flagsmith team planning to do a systemic fix here, which will not allow this to happen? 

cc: @vivonk

**Comment by dabeeeenster** [comment]
Hi @NilanshBansal Just to add - we're still actively working on this issue, trying to recreate it and understand how this data got to be in the state that was in. We're not closing this ticket and will add detail as we find it.

**Comment by gagantrivedi** [comment]
> What was the root cause of this issue?

We are not sure yet because we can't reproduce this

> How can we ensure this issue doesn't occur for the other identifiers? Are there any measures we can take to avoid this in future?

Not really, no. in fact, I would like you to do whatever you did earlier. See if you can reproduce it? 

>    You mentioned, the char limit is 2000 for a trait, but we sent the instanceId trait with 64 chars, how could that cause this to happen?

That's the character limit for string we also support other data types

**Comment by vivonk** [comment]
@gagantrivedi Can you please do the same for this identifier as well?
`63055b8779f6d5ac6b0a81de378c574e45385903d3a13899a008061d36cc35b2`

**Comment by gagantrivedi** [comment]
> @gagantrivedi Can you please do the same for this identifier as well? `63055b8779f6d5ac6b0a81de378c574e45385903d3a13899a008061d36cc35b2`

It is already done for this identity

**Comment by matthewelwell** [comment]
@vivonk we've been trying to reproduce this in multiple ways but are still unable to do so. Is there any additional information that you can provide us with as to how / when these identities were initially created? If you can share your Java code that uses the Flagsmith API that might also help us out. Thanks!

**Comment by matthewelwell** [comment]
@vivonk are you able to provide any more information here as we requested above? If not, I'll close the issue in a few days.

**Comment by levrik** [comment]
Hey everyone. I'm also seeing this issue on our API. I originally thought these 502's were coming from our Kubernetes Ingress as I was seeing a few timeouts on the `/health` endpoint and opened https://github.com/Flagsmith/flagsmith/issues/3744. But after further investigation it turned out that these 502's are indeed coming from Flagsmith itself and not our Ingress.

I'll try to collect some information about when it happens from our system and report back here asap but TBH it's rather difficult to figure out what's going on at all within Flagsmith. Even with DEBUG log level enabled the only thing I'm getting is `Running task 'tasks.track_request' in separate thread` a few times per second and that's it. Are there any other ways that I'm not aware of that can help understanding what Flagsmith is doing internally?

So far I can tell that the identity ID and traits sent with the request don't seem to matter. From time to time it simply fails with 502 and when you retry a few seconds later it just works most of the time. Sometimes it only works again on the 3rd or 4th try.
