### ISSUE TITLE
JIRA Integration

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2818]
As per https://github.com/Flagsmith/flagsmith/discussions/2133 This issue is going to spec out a v1 release. We will build on this functionalty over time.

## Setup

1. Copy your API token in the `Account` area in Flagsmith. 
2. Open Jira Cloud and add the Flagsmith integration (not sure the steps here)
3. In JIRA, Add the API token from Flagsmith to the integration configuration
4. If the API token has access to > 1 Organisation, select the organisation
5. Associate the Flagsmith Project with your JIRA project

## Usage

When viewing an issue in JIRA, you will be able to associate that issue with a Flagsmith flag. Once the association has been made, JIRA will show you the flag state for each of the Environments within that Project directly in JIRA, within that issue.  

Users will also be able to edit the link to either change it to a different Flagsmith flag, or remove the association entirely.

**Comment by kyle-ssg** [comment]
@dabeeeenster I think this can be closed?

Do we need to add it to the integrations page in the app?
