### ISSUE TITLE
Change requests don't show before and after of Multivariate values

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2819]
<img width="1130" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/4c57175d-f7bc-42d3-9b4a-401fb14b1090">

Here I modified the variation. The original value is `white` and I added a change request for `white2`. The original value of `white` is no longer showing. We should show the original value and the new value.

**Comment by jatingodnani** [comment]
@dabeeeenster instersted
Can you assign me this issue

**Comment by jatingodnani** [comment]
my question is where should i display original value

**Comment by dabeeeenster** [comment]
The original value should be in the left column and the new value in the right

**Comment by jatingodnani** [comment]
![Screenshot_20231006_234530_Chrome](https://github.com/Flagsmith/flagsmith/assets/97869761/95b61371-0885-43fd-8585-5fcd94423720)
Like this

**Comment by dabeeeenster** [comment]
Correct yes.

**Comment by jatingodnani** [comment]
Then i need to make two input

**Comment by jatingodnani** [comment]
i am not able to run repo locallly. it showing this when i run cmd npm run dev
what could be the reason @dabeeeenster 
![Screenshot 2023-10-07 121143](https://github.com/Flagsmith/flagsmith/assets/97869761/bf0c3e2d-59bb-46e8-89f7-69b1fe2d45f6)

**Comment by dabeeeenster** [comment]
the server is started up here - you can see it is listening on port 8080

**Comment by jatingodnani** [comment]
In change request it showing payment plans.how to acces this page then @dabeeeenster

**Comment by dabeeeenster** [comment]
Easiest is to edit the nav/page to short circuit the check

**Comment by jatingodnani** [comment]
Is there any docs available? @dabeeeenster

**Comment by dabeeeenster** [comment]
No sorry! You will need to look through the code in the relevant place.

**Comment by jatingodnani** [comment]
![Screenshot 2023-10-07 152516](https://github.com/Flagsmith/flagsmith/assets/97869761/4f1580fb-5af6-43ce-a1d1-11975f368e57)
I am not able to open the changes request page.
If can tell me the exact url it will be helpfull @dabeeeenster

**Comment by dabeeeenster** [comment]
For this issue just edit the JSX code to ignore this check

**Comment by matthewelwell** [comment]
This was completed in the redesign.
