### ISSUE TITLE
Log realtime environment keys

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2831]
Our realtime CDN collapses requests. We need to track data of which SaaS environments are connecting to our realtime service and the volume of those connections.

**Comment by gagantrivedi** [comment]
This is what fastly suggested: 
 
The workaround for this would be to set up log streaming to an endpoint of your choice and perform log analysis, this would show you more detailed information.
 
You can take a look at our log streaming documentation: https://docs.fastly.com/en/guides/about-fastlys-realtime-log-streaming-features
 
Guide to setting this up: https://docs.fastly.com/en/guides/setting-up-remote-log-streaming
 
Integrations we offer: https://docs.fastly.com/en/guides/integrations

**Comment by gagantrivedi** [comment]
This is done, and the data is available in influx
