### ISSUE TITLE
Update Twitter Logo

### ISSUE THREAD

**Issue by Kaushik080** [SolidStateGroup/bullet-train-api#2851]
To reproduce -
Go to the footer of the website
In the current version of the website the logo of the twitter is not updated
![image](https://github.com/Flagsmith/flagsmith/assets/120493528/d63fd19e-78e0-4250-9d57-87177df16d30)

**Comment by niranjan-kurhade** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by matthewelwell** [comment]
@Kaushik080 thanks for this - we will get it fixed. 

@niranjan-kurhade unfortunately this is not part of our open source codebase so is not something you will be able to resolve.

**Comment by dabeeeenster** [comment]
<img width="263" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/7bf7df46-b2ca-4f99-a3ea-68ca04f534e4">
