### ISSUE TITLE
Compare / Clone Identities

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2871]
Add the ability in the dashboard to compare flags between two Identities and then copy/clone the flags from Identity A to B

**Comment by matthewelwell** [comment]
Compare identities is done, but clone needs doing still.

**Comment by matthewelwell** [comment]
Note that the clone functionality will need to consider both Edge and Core.

**Comment by kyle-ssg** [comment]
I think it's also worth noting that clone would never take Multivariate into account. It'd be a pretty confusing feature 

As mentioned, compare is already done: 

![image](https://github.com/Flagsmith/flagsmith/assets/8608314/c16d6706-1f87-4a7c-aff6-d53f399f8007)

**Comment by novakzaballa** [comment]
Is there any additional context, background, or feature request that I can use to implement the cloning part of this ticket?
Some considerations need to be clarified like:

1. Do we want to copy the configuration by copying only the overridden feature states from source to target?
2. In that case, should we also copy the identity traits?
3. We cannot (do not want to) enforce the multi-variate value right?
