### ISSUE TITLE
Improve "Save permission" Button in EditPermission component

### ISSUE THREAD

**Issue by novakzaballa** [SolidStateGroup/bullet-train-api#2886]
**Is your feature request related to a problem? Please describe.**

Depending on the design of the roles, there should be a global button to save changes at a permission level

**Describe the solution you'd like**

Add a global button to save changes to a permission level

**Comment by jatingodnani** [comment]
@novakzaballa, can you  pls tell me more about this issue

**Comment by novakzaballa** [comment]
Hey @jatingodnani , this is a feature we recently introduced for our Enterprise customers, roles management. [A role ](https://docs.flagsmith.com/system-administration/rbac#roles)
I will update the description for clarity, however, this would be hard to develop for an external contributor since enterprise/paid subscription would be required for testing it.

**Comment by matthewelwell** [comment]
@kyle-ssg could this be resolved by your work on #3652 or #3730 ?

**Comment by novakzaballa** [comment]
It was closed because this button no longer exists in the UI.
