### ISSUE TITLE
Additional flag filtering options on main flag page

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2909]
It would be helpful to be able to filter by:

- Tag
- Owner/owners
- State (on, off)

We should maybe use the same UI pattern github does for their issues list:

<img width="1282" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/752f607c-b20a-4cad-95a9-4785adc89ec1">

<img width="1270" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/af5938e5-bb4d-4172-8df0-4a492e474b26">

**Comment by zachaysan** [comment]
I like the idea of following the GitHub way of doing things. It's unobtrusive but leaves functionality there if you need it.

**Comment by gnumoreno** [comment]
@dabeeeenster can we close this one?

**Comment by MatheusLasserre** [comment]
I think #3136 solves this one
