### ISSUE TITLE
Edit Environment Permissions fails without UI indication

### ISSUE THREAD

**Issue by zachaysan** [SolidStateGroup/bullet-train-api#2916]
**Describe the bug**

Edit Environment Permissions for both users and groups results in an error.

**To Reproduce**

1. Go to the settings page of an environment as an admin on the environment, but not as an admin of the org. 
2. Click on the members tab of the settings page.
3. Find a user that is a regular user and click on the gear to edit their Environment Permissions.
4. Change some permissions of the user, but do not make them an admin.
5. Click on the save permissions button.

**Expected behavior**

The user will now have the permissions, but instead the request silently fails with an error:
```
{user: ["This field is required."]}
```

When inspecting the request, it is clear that the JS is not setting the user on the `POST`, which may be because of a permission error somewhere else during loading. A similar bug happens with user group permissions as well.

**Screenshots**
<img width="1104" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/222715/c1bf6e91-3d56-4099-b4a2-e4ccaa4a4982">

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

I am an employee of Flagsmith and this is on one of our test accounts, so reproducing it should be possible.

**Comment by gagantrivedi** [comment]
Need some help from @kyle-ssg  on this. The environment permission for the `environment admin` user are also not populated in the UI

**Comment by kyle-ssg** [comment]
Hmm, sorry I'm not quite sure what this refers to.

The original issue is no longer the case, and I can see an environment admin's permissions.

![Image](https://github.com/user-attachments/assets/1c015c81-3a7d-4be0-acb7-0e772a765910)

**Comment by gagantrivedi** [comment]
> Hmm, sorry I'm not quite sure what this refers to.

If I log in as `environment-admin` and click on my user, I see this:


![Image](https://github.com/user-attachments/assets/1afc7013-ef0a-4bb7-be5b-a435e3fb7415)
