### ISSUE TITLE
"announcement" flag as null is causing the Flagsmith Frontend app to crash

### ISSUE THREAD

**Issue by benjiekibblewhite** [SolidStateGroup/bullet-train-api#2917]
**Describe the bug**
We noticed this morning that our self-host open source Frontend UI no longer works. We see a blank screen, and this error in the console: 

```
react-dom.production.min.js:187 TypeError: Cannot read properties of null (reading 'id')
    at o.render (App.js:290:70)
    at fa (react-dom.production.min.js:173:192)
    at ca (react-dom.production.min.js:172:282)
    at Ds (react-dom.production.min.js:247:361)
    at Ss (react-dom.production.min.js:216:164)
    at xs (react-dom.production.min.js:210:471)
    at ms (react-dom.production.min.js:204:166)
    at Zs (react-dom.production.min.js:263:24)
    at Ks (react-dom.production.min.js:263:118)
    at react-dom.production.min.js:272:306
    ```

Looking at the response from `https://edge.api.flagsmith.com/api/v1/identities/?identifier=MY_EMAIL_ADDRESS`, I see that the value for the `announcement` flag is `null`, but there's code looking for an `id` property on it:  https://github.com/Flagsmith/flagsmith/blob/ec444bd653d7d21453cb40902bca021948aff22c/frontend/web/components/App.js#L285-L289

**To Reproduce**

1. Go to the flagsmith frontend and sign in
2. See if the page loads, or if you have the error message in the console

**Expected behavior**

The page should load, and there should be fallbacks for null values.

**Screenshots**
![image](https://github.com/Flagsmith/flagsmith/assets/20599250/40b4a875-7eeb-4e32-86c4-9bc8504caa56)

**How are you running Flagsmith?**

- [x] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way

**Comment by dabeeeenster** [comment]
We would recommend running Flagsmith on Flagsmith for self hosted installs: https://docs.flagsmith.com/deployment/overview#running-flagsmith-on-flagsmith
