### ISSUE TITLE
Add copy button for server-side environment keys

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#2941]
As per the client-side environment key, we should add a 'copy' button next to each of the server-side environment keys. 

<img width="1164" alt="Screenshot 2023-11-08 at 14 25 14" src="https://github.com/Flagsmith/flagsmith/assets/14089968/c4ae7831-8641-4b57-a05c-da08c25d35c4">

**Comment by gnumoreno** [comment]
https://github.com/Flagsmith/flagsmith/pull/2943
