### ISSUE TITLE
Surface Segment/Feature/Segment override limits

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2980]
We should show the Segment/Feature/Segment override limits and current usage numbers on the project settings page

**Comment by fabricanva** [comment]
Hey team, can I take this one?

**Comment by dabeeeenster** [comment]
Yes that would be great! I'm not sure if we surface this data in the API currently? Any ideas @khvn26 ?

**Comment by matthewelwell** [comment]
Yes, we do! Endpoint at `/api/v1/projects/:id` returns the following attributes: 

<img width="372" alt="Screenshot 2024-01-12 at 10 14 32" src="https://github.com/Flagsmith/flagsmith/assets/14089968/ec373b7c-79a9-4180-b64d-b2790fee3954">

**Comment by matthewelwell** [comment]
I've updated the issue description because we don't currently limit identity overrides.

**Comment by MatheusLasserre** [comment]
Hey! Can i make a PR for this one?

If so, is there any endpoint that i can fetch the total segments overrides?

**Comment by gagantrivedi** [comment]
Hi @MatheusLasserre  Yes, endpoint at `/api/v1/environments/{api_key}/`
