### ISSUE TITLE
After cancellation, users still see old plan in organisation settings

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#3000]
Currently, after an organisation cancels their subscription, the organisation settings page still shows the old plan.

We need to decide what we want to do here, whether we want to show that the plan was cancelled and they are now on the free plan, or just show 'free plan' and not surface information about the previous plan.

**Comment by dabeeeenster** [comment]
Just show "Free plan" and behave as if they never had a subscription.
