### ISSUE TITLE
Manage members layout is broken

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#3001]
What I see:

<img width="1084" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/ed11a017-5451-47e0-95b6-783c6310a834">

What the designs show:

<img width="1192" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/91317699-4aa6-4e45-b4b5-010c2baf8331">

**Comment by jatingodnani** [comment]
@novakzaballa i would like to try
