### ISSUE TITLE
The detail view for the scheduled feature changes does not show the upcoming value

### ISSUE THREAD

**Issue by zachaysan** [SolidStateGroup/bullet-train-api#3005]
**Describe the bug**

See below, the live value of the feature for the environment is listed, but the actual scheduled value is not listed.

![image](https://github.com/Flagsmith/flagsmith/assets/222715/d43e0f7d-57a2-4a14-94bc-101cec171645)

**To Reproduce**

1. Schedule a change to a feature.
2. Click the `Scheduling` tab for a given environment.
3. Click on the scheduled feature change.
4. Observe that it is not visible. 

**Expected behavior**

The value of the upcoming change.

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [x] I work for Flagsmith

**Additional context**

N/A

**Comment by jatingodnani** [comment]
@zachaysan can you pls explain more about this issue
