### ISSUE TITLE
The text in the button is misaligned in mobile view.

### ISSUE THREAD

**Issue by Tushar-sahani** [SolidStateGroup/bullet-train-api#3033]
**Describe the bug**

In mobile view Get Started button text get misaligned in different pages like feature flags & Remote config page, A/B & multivariate Testing page, Real-time Flag pages and more.
In mobile view the text of Get started button aligned to the right which should be align in center.
![image](https://github.com/Flagsmith/flagsmith/assets/104075614/5a66a97d-d48b-4570-8a69-13e9878f3923)

**Expected behavior**

This issue can be fixed by removing the ```text-align:right``` property form ```.button.is-primary``` class.
![Screenshot 2023-11-26 112948](https://github.com/Flagsmith/flagsmith/assets/104075614/49a4f771-b77a-4626-828e-5cf78b3ab1d6)

**Comment by annaredbond** [comment]
Thank you, @Tushar-sahani! I'm investigating this now

**Comment by annaredbond** [comment]
This is fixed!! Thanks again for reporting it, @Tushar-sahani
