### ISSUE TITLE
Only track Delighted NPS after login

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#3034]
We use https://delighted.com/ to track NPS scores. Some people have complained that they get asked a score the first time they log in. 

Code here: https://github.com/search?q=repo%3AFlagsmith%2Fflagsmith%20delighted&type=code

I think we are loading the delighted script before succesful login. This means we start tracking people before they sign up. Delighted is set like this:

<img width="387" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/61f20f60-d2e8-45f2-9c8c-3bb7b61b6737">

but if you visit the login page I think this timer will start. 

Can we make sure the delighted script is loaded and the user tracked when they actually log into Flagsmith.

**Comment by matthewelwell** [comment]
From #3312 

>We are using the organisation created date here https://github.com/Flagsmith/flagsmith/blob/ec272ba29f08f58c5a30bdc6e6da7a03233b8513/frontend/common/stores/account-store.js#L315 which I think is wrong as per https://app.delighted.com/docs/api/web - this should be when the user account registered

**Comment by kyle-ssg** [comment]
> From #3312
> 
> > We are using the organisation created date here https://github.com/Flagsmith/flagsmith/blob/ec272ba29f08f58c5a30bdc6e6da7a03233b8513/frontend/common/stores/account-store.js#L315
> >  which I think is wrong as per https://app.delighted.com/docs/api/web - this should be when the user account registered

I think that must be what's causing it, unfortunately I don't thing the FE has access to the account registration date.

**Comment by kyle-ssg** [comment]
@matthewelwell I think to resolve this I'll just need created_at returning in /me

**Comment by matthewelwell** [comment]
@kyle-ssg just FYI, the field is called `date_joined`. I can mask that with `created_at` if it makes any difference to your implementation. It's a few extra lines on our side.
