### ISSUE TITLE
self-hosted app does not working.

### ISSUE THREAD

**Issue by kakaru1331** [SolidStateGroup/bullet-train-api#3049]
**Describe the bug**

self-hosted app does not working.

**To Reproduce**

1. git clone git@github.com:flagsmith/self-hosted.git
2. docker-compose -f self-hosted/docker-compose.yml up
3. Go to the port app is running (8000)
4. no content show

docker logs is below.
flagsmith-self-hosted-flagsmith-1            | WARNINGS:
flagsmith-self-hosted-flagsmith-1            | ?: (axes.W002) You do not have 'axes.middleware.AxesMiddleware' in your settings.MIDDLEWARE.
flagsmith-self-hosted-flagsmith-1            | [2023-11-28 06:07:21 +0000] [1] [INFO] Starting gunicorn 20.1.0
flagsmith-self-hosted-flagsmith-1            | [2023-11-28 06:07:21 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
flagsmith-self-hosted-flagsmith-1            | [2023-11-28 06:07:21 +0000] [1] [INFO] Using worker: gthread
flagsmith-self-hosted-flagsmith-1            | [2023-11-28 06:07:21 +0000] [12] [INFO] Booting worker with pid: 12
flagsmith-self-hosted-flagsmith-1            | [2023-11-28 06:07:21 +0000] [13] [INFO] Booting worker with pid: 13
flagsmith-self-hosted-flagsmith-1            | [2023-11-28 06:07:21 +0000] [14] [INFO] Booting worker with pid: 14

**Expected behavior**

Display home page

**Screenshots**

![image](https://github.com/Flagsmith/flagsmith/assets/30231633/a806881c-ed6c-477a-bb6e-292df0879a9b)

**How are you running Flagsmith?**

- [ v ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

**Comment by mfv-brian** [comment]
I have the same issue

**Comment by dabeeeenster** [comment]
We're looking into it - looks related to the `index.html` consolidation

**Comment by matthewelwell** [comment]
This has been resolved.

**Comment by mfv-brian** [comment]
![image](https://github.com/Flagsmith/flagsmith/assets/88994767/0b270fa4-b7b4-4490-94ba-2c36f9ed4698)
Not yet, which branch should I checkout to ?

**Comment by matthewelwell** [comment]
You shouldn't need to checkout any other branches. It should just work (it is working here for me). Can you share the network tab and look for a call to `https://edge.api.flagsmith.com/api/v1/flags` please?

**Comment by matthewelwell** [comment]
In the response, you should see the following (amongst other flags): 

```json
    {
        "feature": {
            "type": "STANDARD",
            "name": "announcement",
            "id": 54542
        },
        "enabled": false,
        "feature_state_value": "{}"
    }
```

**Comment by mfv-brian** [comment]
![image](https://github.com/Flagsmith/flagsmith/assets/88994767/de0b59c8-29b3-4682-905b-8ac1d269a027)
oh, it works, thanks

**Comment by kakaru1331** [comment]
I also checked it.
This has been solved.
Thank you. :)

**Comment by mfv-brian** [comment]
Excuse me, it is the first time a login with flag smith 
![image](https://github.com/Flagsmith/flagsmith/assets/88994767/e415a7f5-30b5-47d0-afdd-7635c652b2ba)
I do as the document, but I cannot see the reset password link. How to login ?

**Comment by matthewelwell** [comment]
@mfv-brian Please raise a separate issue or send a message in [our discord channel](https://discord.gg/hFhxNtXzgm)
