### ISSUE TITLE
When the Segment Overrides per Environment limit is reached there is no UI validation on save

### ISSUE THREAD

**Issue by landonjs** [SolidStateGroup/bullet-train-api#3103]
**Describe the bug**
https://docs.flagsmith.com/system-administration/system-limits

**To Reproduce**

When the limit has been reached the saving an override on the segment does not show any validation. The Save button continues to saving "Saving" even though a 400 is returned from the request

**Expected behavior**

**Screenshots**

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [x] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

**Comment by dabeeeenster** [comment]
Fixed in latest version
