### ISSUE TITLE
Write identity overrides as segments to the `flagsmith_overrides` DynamoDB table

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#3104]
When modifying `EdgeIdentity.identity_features`:

1. Map them to Segments:
   a) Highest possible priority
   b) Segment conditions with `"_$identity.identifier"` property name and `EQUAL` operator.
2. Write those to `flagsmith_overrides` DynamoDB table, keyed by Environments, with `page` set to a constant value of `1`.

Make sure the override count is limited to 1000.

Make this behaviour configurable per-project.

**Comment by matthewelwell** [comment]
As part of this, we'll also need to consider all of the actions on the EdgeIdentityFeatureStateViewSet. This will involve changing the following:

* Create identity override should write to new table
* List identity overrides should retrieve from new table
* Delete identity override should remove from new table
* Retrieve identity override should retrieve from new table
* Update identity override should update new table

All of this should be dependent on a flag against the project.

**Comment by khvn26** [comment]
Closing in favour of #3105 and #3106.
