### ISSUE TITLE
Broken UI on user invite form

### ISSUE THREAD

**Issue by alextrueman** [SolidStateGroup/bullet-train-api#3129]
**Describe the bug**

Invited users facing with broken UI after clicking both external invite link or invite link in email.

**To Reproduce**

1. Go to https://app.flagsmith.com/organisation-settings
2. Open "Members"
3. Click on "Invite members"
4. Fill user email
5. Click on "Send Invitation" 

6. When invited user open link from email ( or from "Copy Invite Link" ), he see that UI is broken ( screenshot )

**Expected behavior**

User should be able to read all the labels.

**Screenshots**

![image](https://github.com/Flagsmith/flagsmith/assets/14744824/cea8c3f8-2070-401d-a2ea-b033129f5041)

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

**Comment by gnumoreno** [comment]
@alextrueman thanks for reporting. I will ask our engineering team to take a look.

**Comment by gnumoreno** [comment]
Related? https://github.com/Flagsmith/flagsmith/issues/2915

**Comment by kyle-ssg** [comment]
Although it's the same page, these issues are unrelated.

In this case believe the above screenshot is just on browsers where the user has previously logged in and enabled dark mode. Will implement dark mode on this screen to fix.
