### ISSUE TITLE
Identity overrides in local evaluation mode SDK implementations

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#3132]
Part of https://github.com/Flagsmith/flagsmith/issues/1762.

All server side SDKs can now implement Identity overrides:

- [x] Node.js
- [x] Java
- [x] .Net
- [x] Python
- [x] PHP
- [x] Ruby
- [x] Rust
- [x] Go
- [x] Elixir

**Comment by khvn26** [comment]
### Current status

Ready to merge:

- https://github.com/Flagsmith/flagsmith-python-client/pull/72

Ready for review:

- https://github.com/Flagsmith/flagsmith-java-client/pull/142
- https://github.com/Flagsmith/flagsmith-nodejs-client/pull/143

Up for grabs:

- https://github.com/Flagsmith/flagsmith-dotnet-client/issues/89
- https://github.com/Flagsmith/flagsmith-php-client/issues/60
- https://github.com/Flagsmith/flagsmith-ruby-client/issues/42
- https://github.com/Flagsmith/flagsmith-rust-flag-engine/issues/11 and https://github.com/Flagsmith/flagsmith-rust-client/issues/17
- https://github.com/Flagsmith/flagsmith-go-client/issues/112

**Comment by andreamouraud** [comment]
Hi and thank you for this work ! Do you know if the approved PRs could be merged/released or are you waiting for every SDK to implement it to release them all at once?

**Comment by khvn26** [comment]
Hello @andreamouraud! We're not rushing to release the SDKs because the server-side implementation is yet to be released. Besides that, only pilot projects/environments will be able to use this feature. Please let us know if you want to be among the first to test this feature!

**Comment by khvn26** [comment]
This is released:


- NodeJS SDK [3.3.0](https://github.com/Flagsmith/flagsmith-nodejs-client/releases/tag/v3.3.0)
- Java SDK [7.3.0](https://github.com/Flagsmith/flagsmith-java-client/releases/tag/v7.3.0)
- .Net SDK [5.3.0](https://github.com/Flagsmith/flagsmith-dotnet-client/releases/tag/v5.3.0)
- Python SDK [3.6.0](https://github.com/Flagsmith/flagsmith-python-client/releases/tag/v3.6.0)
- PHP SDK [4.3.0](https://github.com/Flagsmith/flagsmith-php-client/releases/tag/v4.3.0)
- Ruby [4.1.0](https://github.com/Flagsmith/flagsmith-ruby-client/releases/tag/v4.1.0)
- Rust SDK [1.5.0](https://github.com/Flagsmith/flagsmith-rust-client/releases/tag/v1.5.0)
- Go [3.5.0](https://github.com/Flagsmith/flagsmith-go-client/releases/tag/v3.5.0)
- Elixir SDK [2.1.0](https://github.com/Flagsmith/flagsmith-elixir-client/releases/tag/v2.1.0)
