### ISSUE TITLE
Archiving Flags

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#317]
## Overview

We have had feedback that admin users often want to tidy up/clear up old flags, but are worried about removing the flag from SDK API requests (due to aspects like old Mobile app versions needing old/stale flags). 

## Proposal

Add an Archive button to the flag modal. Archiving a flag removes it from the default flag list for a project. If an environment has any archived flags, indicate the number here:

![image](https://user-images.githubusercontent.com/173290/133435689-b09c4c00-ed30-497f-9aca-1305f50cb01e.png)

e.g. 

🚀 Features      9 Archived Flags

The "9 Archived Flags" button would act as a toggle. Clicking on "9 Archived Flags" would toggle showing/hiding the archived flags in the list.

**Comment by gagantrivedi** [comment]
Since this endpoint is paginated(with page size of 10 and no way for client to change that, although we can enable that) I think we have to implement pagination for this endpoint.

**Comment by dabeeeenster** [comment]
@kyle-ssg how is the main list of features called from the front end dashboard? Is it doing paging in any way?

**Comment by matthewelwell** [comment]
@dabeeeenster @gagantrivedi I remembered this morning (and verified) that we hacked this for production only. Check out app.settings.production, it has this line: 

```python
REST_FRAMEWORK["PAGE_SIZE"] = 999
```

**Comment by dabeeeenster** [comment]
OK yes lets fix that 🤣

**Comment by dabeeeenster** [comment]
Needs Front End @kyle-ssg

**Comment by kyle-ssg** [comment]
Note: for tech debt I'll be adding page_size=999 as a get param to /projects/:id/features in order to remove the need for the global page_size param. (Done in https://github.com/Flagsmith/flagsmith/pull/357)

**Comment by kyle-ssg** [comment]
Frontend tested on staging and pushed live under the flag archive_flags https://github.com/Flagsmith/flagsmith/pull/356

**Comment by dabeeeenster** [comment]
Archived flags should be hidden by default. Archiving flags on staging works but they are still showing in the default list.

**Comment by kyle-ssg** [comment]
![image](https://user-images.githubusercontent.com/8608314/135167446-3f005805-d631-4bb1-9dd0-7034bca6f6dc.png)
Not true?  Archived toggle is deselected by default.

**Comment by dabeeeenster** [comment]
I see this as the default page:

![image](https://user-images.githubusercontent.com/173290/135167591-975b06e9-24cd-4c1d-81e3-29f471395b62.png)

Also toggling archive has no effect for me

**Comment by kyle-ssg** [comment]
And if you select archived does it show an additional 2 flags?

**Comment by dabeeeenster** [comment]
[Video](https://cdn.benr.win/Screen%20Cast%202021-09-28%20at%2010.25.45%20PM.mp4)

Nothing in JS console

**Comment by kyle-ssg** [comment]
Ok, that only happens in the case where no tags are selected , fixed here https://github.com/Flagsmith/flagsmith/pull/367

**Comment by gagantrivedi** [comment]
@dabeeeenster safe to close?
