### ISSUE TITLE
show new password validations in the frontend

### ISSUE THREAD

**Issue by xmonader** [SolidStateGroup/bullet-train-api#3221]
so I rand the docker compose up command and got in the logs a reset password url with admin@example.com user

Whenever i try to set the password it doesn't show detailed error, just `oops`

and in the console this was the issue

![image](https://github.com/Flagsmith/flagsmith/assets/64129/1b947ad9-36b0-47f2-b5e0-28bf2a1241e7)

**Comment by dabeeeenster** [comment]
We should reflect the error message to the user in this situtation
