### ISSUE TITLE
can't create a new project 

### ISSUE THREAD

**Issue by xmonader** [SolidStateGroup/bullet-train-api#3222]
![image](https://github.com/Flagsmith/flagsmith/assets/64129/c9ff8e04-c737-4bf8-b784-ce123a12cac5)

the field isn't enabled, i have only the default organization and default project

**Comment by dabeeeenster** [comment]
Please can you resubmit this issue with the bug report template and fill out steps to reproduce etc.

**Comment by xmonader** [comment]
Definitely, thank you for your patience
