### ISSUE TITLE
Provide an environment export to support Offline Mode

### ISSUE THREAD

**Issue by zachaysan** [SolidStateGroup/bullet-train-api#3226]
See [this related ticket](https://github.com/Flagsmith/flagsmith/issues/2024).

Now that we're supporting an increasingly larger number of SDKs operating in Offline Mode, it would be a real usability win if an `environment.json` file could be generated for our users which can then be manually imported into their SDKs for use in Offline Mode. 

@matthewelwell has some ideas on how to make this export really straight forward.

**Comment by matthewelwell** [comment]
User token authentication (instead of Server Key authenticated) endpoint already exists for this at `GET /api/v1/environments/{api_key}/document/`.
