### ISSUE TITLE
Can't create a new project

### ISSUE THREAD

**Issue by xmonader** [SolidStateGroup/bullet-train-api#3228]
**Describe the bug**

Can't create a new project 

**To Reproduce**

- `curl -o docker-compose.yml https://raw.githubusercontent.com/Flagsmith/flagsmith/main/docker-compose.yml
&& docker compose -f docker-compose.yml up`
- wait until it's up
![image](https://github.com/Flagsmith/flagsmith/assets/64129/dab72710-531d-4cc9-ab28-01bdc3221fa5)
- access the url in this line `Please go to the following page and choose a password: http://localhost:8000/password-reset/confirm/MQ/c06wfn-a4188fd4e41d50c19b33d2b499e5ffad`
- 
![image](https://github.com/Flagsmith/flagsmith/assets/64129/f3c0facb-a80e-4b85-a07a-9174f93a2dfd)

- 
![image](https://github.com/Flagsmith/flagsmith/assets/64129/30a0d1b7-e619-4228-80db-bd66c18f1a9f)
- now click on create project
![image](https://github.com/Flagsmith/flagsmith/assets/64129/926d12ce-0774-4391-9ca7-1d3e0033fda1)

the button is disabled 
**Expected behavior**

I should be able set the project name to continue the project
**Screenshots**

All been added to the steps in the issuee

**How are you running Flagsmith?**

- [x] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

I tried it also on multiple browsers (vivaldi and chrome) also my host is ubuntu 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```

**Comment by dabeeeenster** [comment]
Ah ok - this will explain things: https://github.com/Flagsmith/flagsmith/issues/3231
