### ISSUE TITLE
Support longer rules than 1000 characters

### ISSUE THREAD

**Issue by Dogacel** [SolidStateGroup/bullet-train-api#3242]
https://github.com/Flagsmith/flagsmith/blob/79851ce74d26c5f712105402c131023ce3b7cc0e/api/segments/models.py#L154-L154

The current limit of 1000 characters is not enough for some cases, especially for `in` operators. We should update it to support up to at least 10,000 UUIDs if possible. (around 369,999 characters)

You know the limits of the evaluation engine better, let me know how much it can handle, the higher the better.

**Comment by dabeeeenster** [comment]
This also has limitations/ramifications for the Edge API. I think we need to come up with some sort of new Entity/solution for larger segment rule values.

**Comment by dabeeeenster** [comment]
Closing in favour of https://github.com/Flagsmith/flagsmith/issues/2771
