### ISSUE TITLE
Can't save after deleting condition on "Segment Overrides" screen and `OR` button disappears

### ISSUE THREAD

**Issue by Dogacel** [SolidStateGroup/bullet-train-api#3244]
**Describe the bug**

When a new condition is added to the segment override and immediately deleted without being modified, it doesn't allow 

**To Reproduce**

1. Go to 'Features', click on a feature.
2. Go to `Segment Overrides`, create a new override.
3. Enter a dummy trait & value.
4. Click `OR` and delete the `OR`ed condition immediately without modifying it.

**Expected behavior**

`OR` button should appear on the first condition and the flag should be saved.

**Screenshots**

OR button disappearing:

https://github.com/Flagsmith/flagsmith/assets/7023385/383fb261-3efd-418e-8746-d7c713c6943c

Rule failing to update:

https://github.com/Flagsmith/flagsmith/assets/7023385/36aaa988-4c09-4c62-8508-e5d830c0bf4b

**How are you running Flagsmith?**

- [x] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

Captured from network tab, seems like those conditions are still included in the request
```json
{
  "description": "",
  "name": "sa",
  "project": 14554,
  "rules": [
    {
      "id": 83757,
      "type": "ALL",
      "rules": [
        {
          "id": 83759,
          "type": "ANY",
          "rules": [],
          "conditions": [
            {
              "id": 384088,
              "operator": "EQUAL",
              "property": "6",
              "value": "8",
              "description": null
            },
            {
              "id": 384087,
              "operator": "EQUAL",
              "property": "3",
              "value": "4",
              "description": null
            },
            {
              "operator": "EQUAL",
              "property": "5",
              "value": "7",
              "delete": "true"
            }
          ]
        },
        {
          "id": 83758,
          "type": "ANY",
          "rules": [],
          "conditions": [
            {
              "id": 384086,
              "operator": "EQUAL",
              "property": "1",
              "value": "2",
              "description": null,
              "delete": "true"
            }
          ],
          "delete": true
        },
        {
          "conditions": [
            {
              "operator": "EQUAL",
              "property": "",
              "value": "",
              "delete": "true"
            },
            {
              "operator": "EQUAL",
              "property": "",
              "value": "",
              "delete": "true"
            }
          ],
          "rules": [],
          "type": "ANY",
          "delete": true
        },
        {
          "conditions": [
            {
              "operator": "EQUAL",
              "property": "",
              "value": "",
              "delete": "true"
            },
            {
              "operator": "EQUAL",
              "property": "",
              "value": "",
              "delete": "true"
            }
          ],
          "rules": [],
          "type": "ANY",
          "delete": true
        }
      ],
      "conditions": []
    }
  ],
  "id": 23863,
  "uuid": "0cefcfd0-8988-4a30-bd8e-4ea45e4df216"
}
```

Note this wasn't the case when I typed the condition atribute, value and proceeded to delete it. It did not appear in the payload.

**Comment by MatheusLasserre** [comment]
Can i make a PR for this one?

**Comment by kyle-ssg** [comment]
Hey @MatheusLasserre, sure! I do think I know the issue as I was just checking it.

The api requires sending up deleted conditions with ``delete:true`` where the condition already had an id, however it still seems to require validation of other fields. There are therefore 2 scenarios that seem to cause this happening

- Deleting a condition that had no operator/trait/value
- Deleting required fields from an existing condition then removing the condition entirely

**Comment by kyle-ssg** [comment]
@MatheusLasserre, if you're to look at this I think the conclusion is that we just set the property / value to "deleted" on the frontend to prevent both scenarios.
