### ISSUE TITLE
Disabled Feature-specific Segment Overrides interfere with isFeatureEnabled evaluation

### ISSUE THREAD

**Issue by guillemcorominas** [SolidStateGroup/bullet-train-api#3247]
**Describe the bug**

Feature-specific Segment Overrides interfere with the evaluation of isFeatureEnabled even their individual toggle is disabled

**Given** that I have a Feature in the Development environment that has configured a Segment Override based on a "trait" which is a numerical value and using the IN clause (in my example: "deployment_id" IN (179,8161),
**When** the Feature is Enabled, and the Feature-specific Segment is Disabled
**Then** the Feature-specific Segment interferes with the computation, considering the feature disabled for this case (even though the feature-specific segment condition is 'true')
**Instead** it should ignore all disabled segments and return according to the global feature status (in this case disabled)

**To Reproduce**

Steps:
1. Go to a Edit Feature
2. Click on Enable so the feature is enabled
3. Click on Segment Overrides
4. Create a feature specific segment with a condition that can be true for the values of the traits we are going to evaluate
5. Evaluate the feature using the Java SDK -> the result to `isFeatureEnabled` is "true" --> CORRECT
6. **Disable** the feature specific segment using either the individual toggle or the disable all button
7. Evaluate the feature using the Java SDK -> the result to `isFeatureEnabled` is "false" -> this is the ERROR
8. **Remove** the "feature specific segment" leaving the feature with no segments (using the bin button)
9. Evaluate the feature using the Java SDK -> the result to `isFeatureEnabled` is "true" --> CORRECT

**Expected behavior**

Having a disabled feature-specific segment should have the same computational effect than deleting the segment it, however, as described above it doesn't, and it is being strangely applied

**Screenshots**
![Screenshot 2024-01-08 at 12 26 13](https://github.com/Flagsmith/flagsmith/assets/17450486/dfe2f42c-45f8-4859-8d3e-1d57ef6f8a83)

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

We are currently evaluating Flagsmith with a Free plan

**Comment by matthewelwell** [comment]
Hi @guillemcorominas, thanks for the detailed bug report. If I am understanding correctly, I think this is just a misunderstanding of how the Flagsmith segments work. The value of the toggle that you have included in the screenshot is the 'enabled' value that will be provided to any identity that evaluates as 'in' the segment. If you want to 'disable' the segment from affecting evaluations, you need to remove the segment from the feature entirely, as per steps 8 & 9 in your description. 

Essentially, if a segment is shown in the list of segment overrides on a feature, it will always have an effect on the value that is given to any identities that match that segment (ignoring any ordering). 

Hopefully that helps to clear things up here?

**Comment by matthewelwell** [comment]
For more context, this essentially allows you to use segments to override features that you might want 'on' by default, but turned off for a given segment of your users.

**Comment by guillemcorominas** [comment]
Hi Matt,

I understand your answer, however, it is then not very intuitive to me. If
I understand correctly, what Flagsmith does then is "negate" the segment,
which is very different to disabling it. Additionally, given that you are
using the same UI toggle for both the feature enable/disable and the
segment toggle, it is confusing.

Anyway, I still believe that it make sense to disable a segment (without
deleting it), for example to prepare a rollout to be applied certain day.
But that is up to you.

Thanks for the fast response,

Guillem


El dl., 8 de gen. 2024, 14:48, Matthew Elwell ***@***.***> va
escriure:

**Comment by dabeeeenster** [comment]
It's not negating the segment. The toggle widget you highlighted in your original screengrab is just showing what the boolean state of the flag will be if that segment override takes effect. 

So for example, the if the environment default of the flag is On, but you want to override for a segment to turn it Off, thats what your screen grab is showing.

**Comment by guillemcorominas** [comment]
Hi Ben, nice to meet you and congrats for the product you guys are building!

I think we are saying the same thing: when I say negating I mean applying
the inverse to the result of the evaluation function. So if the evaluation
function is user_role = 'ADMIN' and the toggle is enabled, it will let
admin users use the function. If the toggle is disabled (like in my
screenshot), it will explicitly block the access to the feature to admin
users (even if the feature is enabled globally).

I understand your point that it is not a bug, however I find this toggle
confusing and probably requires some UI/UX change (label/component
type/placement/etc) to make it cristal clear what it does.

Those are my five cents, I hope you take it as constructive feedback

Cheers

Guillem




El dl., 8 de gen. 2024, 17:41, Ben Rometsch ***@***.***> va
escriure:

**Comment by dabeeeenster** [comment]
Yeah I get where you are coming from, but theres no concept in the platform of "negating" a default flag or similar.
