### ISSUE TITLE
Can't create negated condition (AND NOT)

### ISSUE THREAD

**Issue by Dogacel** [SolidStateGroup/bullet-train-api#3259]
**Describe the bug**

- Can't create a negated condition.
- No option to create a negated condition with 1 rule.
- Also, it looks like a regular `AND` condition when I create it via API calls.

**To Reproduce**

- Try to create a segment rule, there is no option to negate it.
- When you create a regular segment rule, I am able to convert it by updating its type in database. It looks like a normal condition with one rule, but in reality, that condition should be negated.

**Expected behavior**

We should be able to add `AND NOT` conditions. 

**Screenshots**

https://github.com/Flagsmith/flagsmith/assets/7023385/7030326c-a353-480c-b8f7-dbb228fb81c4

**How are you running Flagsmith?**

- [x] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

**Comment by khvn26** [comment]
Turns out the frontend made an incorrect assumption about the naming of the `NOT` operator.
 
Closing in favour of the initial implementation ticket  https://github.com/Flagsmith/flagsmith/issues/382

CC @kyle-ssg
