### ISSUE TITLE
Unable to clear selected tag value from Tags filter in Features page

### ISSUE THREAD

**Issue by giladgurvich** [SolidStateGroup/bullet-train-api#3306]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] Self Hosted at flagsmith.com
- [X] Some other way (add details in description below)

### Describe the bug

In the Features page, once I filter on a certain tag I can’t seem to be able to remove the tag filter. I can select more/less tags but can't seem to remove all which means I can't see all features.
This gets resolved after re-login.

### Steps To Reproduce

1. Go to the "Features" page
2. Select the "Tags" filter and choose some value
3. Remove the selected tag to restore the view
4. The view is still filtered by the tag value that should have been removed

### Expected behavior

Removing the selected tags from the filter should clear the filter and show all flags.

### Screenshots

![Screenshot 2024-01-18 at 14 49 05](https://github.com/Flagsmith/flagsmith/assets/34208707/41d11d94-0987-4422-ad8f-e14fbd4803eb)

**Comment by kyle-ssg** [comment]
Hi @giladgurvich!

Are you able to provide more detail or perhaps a video of the steps mentioned? Attempting to replicate the above with many tags I see no issue with filtering.

https://github.com/Flagsmith/flagsmith/assets/8608314/a715417f-3db8-4417-a3f3-c10bf49091a8

**Comment by kyle-ssg** [comment]
Upon replicating this I have found the steps, this only seems to occur when filtering by a tag that has no features. We will investigate this further and come up with a fix.
