### ISSUE TITLE
Improve Delighted NPS prompting rates

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#3312]
We are using the organisation created date here https://github.com/Flagsmith/flagsmith/blob/ec272ba29f08f58c5a30bdc6e6da7a03233b8513/frontend/common/stores/account-store.js#L315 which I think is wrong as per https://app.delighted.com/docs/api/web - this should be when the user account registered

**Comment by matthewelwell** [comment]
Duplicate of #3034
