### ISSUE TITLE
Sort features by status

### ISSUE THREAD

**Issue by nivkenshoo** [SolidStateGroup/bullet-train-api#3318]
### Is your feature request related to a problem? Please describe.

We need a way to easily watch all enabled features. Our organization uses hundreds of features under a single Flagsmith project and its hard to understand which features are enabled by browsing through all the features.

### Describe the solution you'd like.

A sort by status option in the features page will resolve our issue. Only 'name' and 'created date' are available as sort parameters at the moment.
<img width="1181" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/53254234/b7749618-144c-4c93-ade6-b4142b815f5b">

### Describe alternatives you've considered

1. Scroll throgh many pages.
2. Use external tool (maybe Mixpanel) to create a view for enabled features.

**Comment by matthewelwell** [comment]
@nivkenshoo, I believe this is a duplicate of (or at least heavily related to) https://github.com/Flagsmith/flagsmith/issues/3243 ?

**Comment by nivkenshoo** [comment]
It is a duplicate indeed. Sorry for not searching before opening the issue.

**Comment by matthewelwell** [comment]
No problem. I'll go ahead and close this one. Feel free to add a comment / reaction to the one I linked.
