### ISSUE TITLE
Dynamo DB prod deployments

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#332]
- [x] Env var needed: AWS_DEFAULT_REGION - ENVIRONMENTS_TABLE_NAME_DYNAMO - IDENTITIES_TABLE_NAME_DYNAMO
- [x] Enable DynamoDB IAM permissions for beanstalk service user
- [x] Configure DNS in front of Cloudfront

**Comment by dabeeeenster** [comment]
Enable DynamoDB permissions for beanstalk service user
