### ISSUE TITLE
Flagsmith identities should ignore whitespace

### ISSUE THREAD

**Issue by wheineman-sunrun** [SolidStateGroup/bullet-train-api#3326]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] Self Hosted at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

Flagsmith should not respect whitespace as part of an identifier, or it needs to make it more obvious on the identify page.

### Steps To Reproduce

1. Send a request to `https://edge.api.flagsmith.com/api/v1/identities/?identifier=abc` in any environment
2. Send a request to `https://edge.api.flagsmith.com/api/v1/identities/?identifier=abc
` in the same environment (note the trailing new line).
3. Search for identities starting with "abc" - https://app.flagsmith.com/project/\<project>/environment/\<environment>/users
 
There are multiple results that are indistinguishable - https://app.flagsmith.com/project/\<project>/environment/\<environment>/users/abc/\<id 1> and https://app.flagsmith.com/project/\<project>/environment/\<environment>/users/abc/\<id 2>

NOTE: The same behavior happens with a trailing space, but that at least shows in the URL - https://app.flagsmith.com/project/\<project>/environment/\<environment>/users/abc%20/\<id>

### Expected behavior

An identity should be a unique identifier - leading or trailing whitespace should not be considered. It seems fair to say that leading or trailing whitespace represents a programmer error on the part of the consuming application, and Flagsmith shouldn't accept this. I would vote for Flagsmith to just "be smart" and trim the whitespace when processing an identifier - but I'd happily accept the request being rejected for bad input.

Or if this is a valid use-case, then that needs to be viewable on the identity page somehow.

### Screenshots

![image](https://github.com/Flagsmith/flagsmith/assets/123393375/d4245203-f7d1-4dcc-879e-e396eb47c52f)
Which identity is this? Is it the one with the trailing newline?

**Comment by dabeeeenster** [comment]
I think we should steer away from being prescriptive / mutating the identifier that we are provided to the SDK/API. There maybe good reasons why spaces are relevant that we are not aware of. 

I do think we should be clearer in the UI to show spaces if they are present in the identifier (especially if they are at the beginning or the end of the identifier string.

**Comment by wheineman-sunrun** [comment]
I agree that an improved display would address this concern (even if it's not my preferred resolution). Thanks for taking the time to review!
