### ISSUE TITLE
Add a limit to number of segment rules

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#3327]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] Self Hosted at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

A large number of segment rules can slow down the platform and clog the task processor. We should consider adding a limit under the fair usage policy.

### Steps To Reproduce

Related slack thread: https://flagsmith.slack.com/archives/C02HPR34L65/p1706125902463089

### Expected behavior

Related slack thread: https://flagsmith.slack.com/archives/C02HPR34L65/p1706125902463089

**Comment by zachaysan** [comment]
Solved in https://github.com/Flagsmith/flagsmith/pull/3397
