### ISSUE TITLE
Paging for multiple list views showing NaN

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#3329]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] Self Hosted at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

<img width="1231" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/64b070e9-d351-43e1-8fcb-566fd03d23ec">

### Steps To Reproduce

Generate a lot of segments. Go through the paging.

### Expected behavior

Paging shows correctly. 

### Screenshots

<img width="1231" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/a3a1359b-a793-42a0-a4ce-8063d7fcb08f">

**Comment by matthewelwell** [comment]
@kyle-ssg can you check all implementations of paging here please? I've noticed this is the case also on the Audit Log page. 

<img width="1172" alt="Screenshot 2024-02-05 at 17 17 31" src="https://github.com/Flagsmith/flagsmith/assets/14089968/105c3d5f-3c01-4de5-a22f-98ea60df3680">
