### ISSUE TITLE
413 Payload to Large -- Error in Jira Integration while linking flag

### ISSUE THREAD

**Issue by Jaribeau** [SolidStateGroup/bullet-train-api#3350]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When a project has many flags/overrides/?, the Jira integration does not work, due to the request payload being too large.

The list of flags is shown correctly, but after selecting a flag and clicking "link", the following error is shown:

![image](https://github.com/Flagsmith/flagsmith/assets/6071465/6aaaae8c-386c-495d-8c16-96728f55b421)

```
{
    "timestamp": 1706619953071,
    "path": "/central/graphql",
    "status": 413,
    "error": "Payload Too Large",
    "message": "GraphQl query and variables must not exceed 512000 bytes in size",
    "requestId": "ad93b2d2-2555788",
    "exception": "io.atlassian.graphql.gateway.http.request.RequestTooLargeException",
    "request_id": "UNKNOWN",
    "query": "unknown",
    "operation": "unspecified",
    "schema": "unspecified",
    "errorSource": "GRAPHQL_GATEWAY"
}
```

### Steps To Reproduce

Given our company's account (i.e. with "lots" of flags, overrides, etc)

1. Click "Linked Feature Flags"
![image](https://github.com/Flagsmith/flagsmith/assets/6071465/476823f0-ddbe-42e0-b474-e41571b4b0f6)

2. Select a flag to link
![image](https://github.com/Flagsmith/flagsmith/assets/6071465/a164e080-1904-4ace-afba-6c529d6967fe)

3. Click "link flag". Then this is shown:
![image](https://github.com/Flagsmith/flagsmith/assets/6071465/9a84cb59-5a37-41ac-914c-8e02253a7fb6)

### Expected behavior

Flag should be linked successfully, as shown with this test project containing only one flag:

![image](https://github.com/Flagsmith/flagsmith/assets/6071465/9cc9278e-ae01-4669-a67a-46fabc002c1a)

**Comment by matthewelwell** [comment]
Hi @Jaribeau , thanks for raising this and apologies for not getting a response back to you sooner. We will take a look into this to see if we can optimise the integration to get around this. Please bear with us while we look into it and we'll update here once we have more information.

**Comment by novakzaballa** [comment]
Hi @Jaribeau, I tried to reproduce the issue by creating a test project with a similar number of flags, segments, and segment overrides, but I was unsuccessful. Could I add myself to your organisation to reproduce the issue? Also, could you please provide the project and issue IDs that raised the issue?

**Comment by Jaribeau** [comment]
Sure thing -- project is 7048.

For Jira -- it was happening with every issue.

**Comment by novakzaballa** [comment]
Thank you, I have been able to reproduce the issue and I'm investigating further. I will return with an answer as soon as possible.

**Comment by matthewelwell** [comment]
@dabeeeenster @novakzaballa I think this is just waiting on a new releae of the JIRA application, can you guys arrange this?

**Comment by dabeeeenster** [comment]
What's in `main` is what is live right now AFAIK - what PRs need to go live @novakzaballa ?

**Comment by novakzaballa** [comment]
There's a [PR ](https://github.com/Flagsmith/flagsmith-jira-integration/pull/6)that needs approval from @matthewelwell
