### ISSUE TITLE
Failed to initialize execute state

### ISSUE THREAD

**Issue by trondhindenes** [SolidStateGroup/bullet-train-api#3363]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [X] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

I'm seeing this error quite often:
```
flagsmith-api-5b546857bc-s5w5x flagsmith-api influxdb_client.rest.ApiException: (404)
flagsmith-api-5b546857bc-s5w5x flagsmith-api Reason: Not Found
flagsmith-api-5b546857bc-s5w5x flagsmith-api HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'Vary': 'Accept-Encoding', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.3.0+SNAPSHOT.090f681737', 'X-Platform-Error-Code': 'not found', 'Date': 'Thu, 01 Feb 2024 07:47:18 GMT', 'Transfer-Encoding': 'chunked'})
flagsmith-api-5b546857bc-s5w5x flagsmith-api HTTP response body: b'{"code":"not found","message":"failed to initialize execute state: could not find bucket \\"default_downsampled_15m\\""}'
flagsmith-api-5b546857bc-s5w5x flagsmith-api 

```
Vanilla helm chart install

### Steps To Reproduce

Just regular helm install. I noticed the error when testing the python sdk

### Expected behavior

no errors

**Comment by matthewelwell** [comment]
@trondhindenes it looks like you haven't completed the set up of influx. There is some documentation on doing so [here](https://docs.flagsmith.com/deployment/overview#time-series-data-via-influxdb). 

I would also recommend using postgres for analytics instead of influx for any new installs. Documentation for this is available [here](https://docs.flagsmith.com/deployment/overview#time-series-data-via-postgres).

**Comment by trondhindenes** [comment]
Thanks! On the first link it states
"by default this data will be stored in Postgres" - that doesn't seem to be the case. I guess my first-impression is that it's harder to get started with the Helm chart than what I was expecting since the "getting started path" isn't clearly defined.

**Comment by matthewelwell** [comment]
Apologies, yes, there is an [outstanding PR](https://github.com/Flagsmith/flagsmith-charts/pull/133) to remove influx db but there are breaking changes that we are working through. I'll check on the documentation to ensure that it's up to date.
