### ISSUE TITLE
Hubspot Integration

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#3384]
We are replacing Pipedrive with Hubspot. In the app, we currently have some [code](https://github.com/Flagsmith/flagsmith/tree/main/api/integrations/lead_tracking) that sends all sign ups (who match certain filters) to Pipedrive.

Currently we create an organisation in Pipedrive based on the user's email domain, then create the user inside that organisation. It looks like we can do something similar with Hubspot using [Companies](https://developers.hubspot.com/docs/api/crm/companies) and [Contacts](https://developers.hubspot.com/docs/api/crm/contacts).

**Comment by zachaysan** [comment]
Closed in https://github.com/Flagsmith/flagsmith/pull/3473
