### ISSUE TITLE
Clean install influxdb missing bucket

### ISSUE THREAD

**Issue by Vrtak-CZ** [SolidStateGroup/bullet-train-api#340]
After clean install (helm chart) influxdb contains only `default` bucket but flagsmith tries to access `default_downsampled_15m` as it's sits here https://github.com/Flagsmith/flagsmith/blob/main/api/app_analytics/influxdb_wrapper.py#L12-L18 but on clean install these buckets does not exists.

**Comment by maxisam** [comment]
There is another one called `_downsampled_1h`

**Comment by dabeeeenster** [comment]
This is fixed in the docs https://docs.flagsmith.com/deployment/overview#influxdb
