### ISSUE TITLE
Organisation usage charts should show data for current billing period

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#3406]
Conversation for context: https://github.com/Flagsmith/flagsmith/pull/3340#pullrequestreview-1872606131. 

Currently the Organisation usage charts show the numbers for the previous 30 days. We are making changes in the PR linked above to send customers alerts when they hit certain thresholds of their API calls limits. Based on this, we'll need to add information to this screen which shows the data for the current billing period. 

![image](https://github.com/Flagsmith/flagsmith/assets/14089968/f5892818-d30a-426a-9519-a9a4b43bc818)

I suggest that we add some kind of switcher which allows you to switch between current billing period and then the previous 30 days. The charts should display exactly the same, but the numbers should change (in 99% of cases).

**Comment by matthewelwell** [comment]
Next step: discuss with @novakzaballa as to what is feasible from a FE perspective.

**Comment by zachaysan** [comment]
Notes from call with Novak:

 - Include prior billing period as it's own selection
 - Include current billing period (TBD: how does the current billing period look if there is not many days?)
 - Include rolling 30 day billing period.

Some possible nice to haves:
 - A 60 or 90 day window to show longer window to users.

Notes on the integration:
 - Should be straightforward if the structure is similar for the graphs.
 - Not 100% sure about the structure for the current billing period or the 90 day window will be able to easily snap in.

**Comment by dabeeeenster** [comment]
@zachaysan I can explain how the downsampling works in Influx - there are several downsampling stages so its important you are querying the right bucket if timeliness of data is important.

**Comment by matthewelwell** [comment]
The endpoint at `/api/v1/organisations/{organisation_pk}/usage-data` accepts the query parameter `period=current_billing_period|previous_billing_period|90_day_period`. 

Note that only paid organisations should have access to the billing period specific periods.
