### ISSUE TITLE
High resources usage on idle

### ISSUE THREAD

**Issue by icecube092** [SolidStateGroup/bullet-train-api#3415]
### How are you running Flagsmith

- [X] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

High cpu and memory usage on idle state

### Steps To Reproduce

deploy with docker-compose

### Expected behavior

few resources usage

### Screenshots

![image](https://github.com/Flagsmith/flagsmith/assets/58211133/e032e4a0-b8f9-4ebf-add0-05b44a524e6d)

**Comment by icecube092** [comment]
How can I decrease usage?

**Comment by dabeeeenster** [comment]
Please look into using caching, local evaluation mode or our edge proxy. You can find further details on all of these topics in our docs.

**Comment by matthewelwell** [comment]
You're running a database server with only 300MiB of memory allocated, I'm not sure what you're expecting here? Please increase the available resources.

**Comment by icecube092** [comment]
I had decrease resources cause all server resources was used by flagsmith.

**Comment by matthewelwell** [comment]
If you can provide accurate steps to reproduce then we can reopen this issue.
