### ISSUE TITLE
"My Flags" view in web ui

### ISSUE THREAD

**Issue by michaelorr** [SolidStateGroup/bullet-train-api#3454]
### Is your feature request related to a problem? Please describe.

As an organization, we are trying to audit and cleanup old flags that have long been removed from the codebase. Unfortunately, there is no way to see all the flags that I have created over time. Adding a "My Flags" view in the UI would be a big help in this effort.
(Full search/filter across Author would be way more powerful, but understandably more involved to implement)

### Describe the solution you'd like.

On the "Features" page for a specific environment, it would be super helpful if there were a "My Flags" filter here:

![Screenshot 2024-02-22 at 6 11 52 PM](https://github.com/Flagsmith/flagsmith/assets/1821185/2ed52bdb-8cf6-4828-a5ec-ee1b6dfba17f)

### Describe alternatives you've considered

It could really be located anywhere in the app, but currently there really is no other way to get at this information. The author isn't even shown so it is not possible to paginate and manually cmd-f.

(Edit)

### Flagsmith Notes (from @matthewelwell)

To implement this, I recommend that we add a filter on flag owners. This may relate to a group or a user so we will need to consider this. To achieve the key requirement in this issue, we should separate 'Current user' as a filter at the top of the users list to make filtering on your own features easier.

**Comment by matthewelwell** [comment]
Thanks for this @michaelorr , I agree that this would be helpful. We'll hopefully get onto this soon!

**Comment by matthewelwell** [comment]
@michaelorr actually implementing a 'my flags' filter would be slightly _harder_ than being able to filter by all authors so I'm going to slightly modify this issue to include the ability to filter on all users / groups.

**Comment by matthewelwell** [comment]
@kyle-ssg @novakzaballa it looks like we now have the option to filter by user, but it would be really nice if we could just pin the current logged in user to the top of the list.
