### ISSUE TITLE
Flagsmith JavaScript API - Unable to Connect

### ISSUE THREAD

**Issue by AlanCPSC** [SolidStateGroup/bullet-train-api#3515]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

A few days ago, the following piece of code started to return 403 errors.

```
flagsmith.init
({
    environmentID:"...",
    onChange: (oldFlags, params) =>
    {
        const { isFromServer } = params;
    },
    onError: (errors) =>
    {
        console.log("Failed to retrieve flags:", typeof(errors), errors);
    },
});
```

Did something happen to the SaaS server endpoint? I am using the free testing plan.

Also, if I add the extra parameter `api: "https://api.flagsmith.com/api/v1/"` to `flagsmith.init({...})`, then the promise doesn't even return. It just hangs perpetually. I don't even get an error back. I just straight up get nothing.

### Steps To Reproduce

See above description.

### Expected behavior

See above description.

### Screenshots

![Screenshot 2024-03-01 at 1 44 19 AM](https://github.com/Flagsmith/flagsmith/assets/22120384/219475b9-49d2-4029-a266-0653b1e2adee)

**Comment by matthewelwell** [comment]
Hi @AlanCPSC, are you able to please contact support@flagsmith.com with this as we'll need to get a few details about your organisation?
