### ISSUE TITLE
Organisation is not created on the first try after signup

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#3544]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When creating a new user account, an organisation is only created on second try.

### Steps To Reproduce

1. https://app.flagsmith.com — click 'Sign up'
2. Enter your user details
3. When prompted, enter organisation name
4. Get prompted again, enter it again
5. Organisation is created

### Expected behavior

Organisation is created after step 3

**Comment by kyle-ssg** [comment]
This was caused by albacross, we haven't adjusted anything internally so conclusion is they rolled out a breaking change. I've contacted their support and removed this for now
