### ISSUE TITLE
Enterprise Licence Management

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#3597]
The UX around installing Flagsmith on-prem can be improved with some additional license management. Suggested approach:

- Flagsmith generates an encrypted file with its _private_ key that includes meta data such as customer name, department name, number of seats, expiry date and possibly other data
- This file is then sent to the customer
- When starting the EE version of Flagsmith, this file can be passed in with different methods (ENV var, attached volume etc) so that the file can be read
- The file is decrypted with the Flagsmith _public_ key and the meta data used to help configure the service

We should also display the org name and department name in the header of the dashboard.

**Comment by khvn26** [comment]
Do we limit installations and how (e.g. keep track of installation IDs)?

> this file can be passed in with different methods (ENV var, attached volume etc)

Most obviously, a dedicated UI in organisation settings.

**Comment by dabeeeenster** [comment]
I think v1 would not have any tracking and would still function if the Flagsmith API had no public internet access.
