### ISSUE TITLE
Create group should auto focus on the name input

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#3620]
Currently when you press the 'Create Group' button, the window auto focuses on the 'External ID' input field rather than the 'Name' field.

**Comment by fabricanva** [comment]
Hey, I'm interested in this issue, could you assign it to me?

**Comment by fabricanva** [comment]
Thank you @dabeeeenster, It's done, here's the [PR](https://github.com/Flagsmith/flagsmith/pull/3632).
