### ISSUE TITLE
When creating an Organisation API key, Free plans should not show the roles toggle

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#3644]
<img width="658" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/173290/752f553a-a90c-4a84-80b0-597277b3caa8">

The Free plan should always just create a full permission API key.

**Comment by priyanshu2k3** [comment]
so we can just disable the toggle button and set it to on by default 
since admin have the full access ??

**Comment by dabeeeenster** [comment]
Yes that's correct
