### ISSUE TITLE
Search users missing CSS box

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#365]
When editing environment settings - same happens in Project settings

![image](https://user-images.githubusercontent.com/173290/135162923-84eb26d3-6e8f-4bf8-81ca-deab338abb04.png)

Styling should be as per Organisation settings page:

![image](https://user-images.githubusercontent.com/173290/135163256-b5330148-058f-43c9-91c9-3b24d4580a42.png)

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/368
