### ISSUE TITLE
Locally and sometimes in the e2e tests, the value of use_v2_feature_versioning does not update from false to true when you enable this feature.

### ISSUE THREAD

**Issue by novakzaballa** [SolidStateGroup/bullet-train-api#3712]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [X] Some other way (add details in description below)

### Describe the bug

The versioning e2e test may fail because the hideHistory value, which depends on whether `use_v2_feature_versioning` is enabled, is `false`.

Locally, if you create a new project and enable the Feature versioning function without any flags, the value does not change.

### Steps To Reproduce

In the e2e test:
- Run the e2e versioning test
Local:
- Create a new Organisation and a new project
- Go to the setting from an environment
- Enable Feature Versioning -> Confirm the modal
- Refresh the page
- The Feature Versioning switch is disabled, and the API response indicates that the value of `use_v2_feature_versioning` is false.

### Expected behavior

If you enabled the Feature Versioning switch and the modal is confirmed, the `use_v2_feature_versioning` would be changed to true.

### Screenshots

https://github.com/Flagsmith/flagsmith/assets/41410593/7af09141-721b-4953-8a6f-fea6c1652ea5

In the Versioning test:

<img width="269" alt="Screen Shot 2024-04-02 at 18 40 38" src="https://github.com/Flagsmith/flagsmith/assets/41410593/457d1ebe-088d-4e0e-8050-a8131fe1c297">

**Comment by kyle-ssg** [comment]
I can't replicate this issue after creating many projects, need a bit more info.

https://github.com/Flagsmith/flagsmith/assets/8608314/aa2a7e17-3706-4d4a-a538-5232dad729de


Based on the sequence of calls in your video it suggests to me that enable-v2-versioning isn't updating the environment synchronously in the API? and after the enable endpoint is called, the following call to /environments still has the option disabled

**Comment by kyle-ssg** [comment]
Discussed with matt, PR should resolve.
