### ISSUE TITLE
"frontend/web/components/pages/AccountSettingsPage.js" 

### ISSUE THREAD

**Issue by Durgesh4993** [SolidStateGroup/bullet-train-api#3726]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

I noticed a few potential issues or areas for improvement in the provided code:

**Undefined Variables:**

- In the constructor, you're accessing AccountStore.getUser(), but AccountStore is not defined anywhere in the component.
- In the invalidateToken method, openConfirm and AppActions are referenced but not defined. Ensure these are imported or defined elsewhere.

**Missing Imports:**

- Some components and utilities are referenced (like Utils, AccountProvider, InputGroup, Row, Switch, flagsmith, toast, openModal, closeModal, openConfirm, AppActions), but their imports are not provided in the snippet. Make sure these are imported correctly.

**Class Naming Convention:**

- The component class name is TheComponent, which is quite generic. Consider giving it a more descriptive name related to its functionality.

**Props Validation:**

**Although you've imported propTypes, you're not utilizing it to define prop types for your component. It's recommended to define prop types for better code maintainability and to catch errors during development.**

### Steps To Reproduce

- Integrate TheComponent into your React app.
- Resolve missing imports like AccountStore, Utils.
- Render the component and verify its functionality.
- Check for undefined variables like openConfirm.
- Ensure prop validation with propTypes.
- Trigger async operations and test error handling.
- Test conditional rendering based on forced2Factor.

### Expected behavior

The expected behavior includes accurately displaying user account info, enabling editing & saving, secure password/email changes, token invalidation, proper account deletion confirmation, clear error feedback, and a user-friendly interface, ensuring consistent behavior across devices.

**Comment by matthewelwell** [comment]
Hi @Durgesh4993 thanks for this - would you be willing to raise a PR (or multiple PRs) for this?
