### ISSUE TITLE
/health endpoint sometimes has response time >2 seconds

### ISSUE THREAD

**Issue by levrik** [SolidStateGroup/bullet-train-api#3744]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [X] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

Sometimes the /health endpoint has a response time >2 seconds although the system checks displayed there themselves took way below 1 second. This has the side-effect of liveness and readiness probes on Kubernetes timing out (2 seconds configured by default), resulting in temporary unavailability or full restarts. I manually changed this timeout to 5 seconds on our deployment now but still wonder why this endpoint takes so long sometimes.

### Steps To Reproduce

No steps. Simply happens several times throughout the day.

### Expected behavior

To have a more consistent response time of this endpoint when the system is fine. Obviously not expected when there are indeed issues.

**Comment by dabeeeenster** [comment]
Can you confirm if this happens with e.g. docker-compose? This is almost certainly related to your setup and not something we could feasibly fix.
