### ISSUE TITLE
Add an option to only allow super users to create organisations

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#380]
Expose the `superuser` django User boolean field in the User API as a read only field. 

Add an env var on the API called `ONLY_SUPERUSERS_CAN_CREATE_ORGANISATIONS` that defaults to `False`. 

If this env var is `True`, only show the `Create Organisation` button to superuser Django admins.

**Comment by gagantrivedi** [comment]
Adds `is_superuser` to /api/v1/auth/users/me/ endpoint that can be used to check if the current user is super user or not
