### ISSUE TITLE
Add "Not" predicate operator in the Segment rules

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#382]
We should have an "Add AND NOT" as per below:

![image](https://user-images.githubusercontent.com/173290/135628991-6d201d0c-e9b4-471f-8773-bdabad489561.png)

Would also mean updating https://github.com/Flagsmith/flagsmith-engine

**Comment by kyle-ssg** [comment]
Added frontend under flag "not_operator", presumed format would be type:"NOT". The flag allows for adding an array of supported clientside evaluation SDKs (see staging for an example, leaving empty will remove the tooltip).

```
[
  {
    "type": "ALL",
    "rules": [
      {
        "type": "ANY",
        "rules": [],
        "conditions": [
          {
            "operator": "EQUAL",
            "property": "test",
            "value": "test"
          }
        ]
      },
      {
        "type": "NOT",
        "conditions": [
          {
            "property": "test",
            "operator": "EQUAL",
            "value": "test2"
          }
        ]
      }
    ],
    "conditions": []
  }
]
```

**Comment by khvn26** [comment]
As discussed internaly, the proposed operator should actually be `"NONE"` (and is already supported by engine implementations).

**Comment by kyle-ssg** [comment]
This is now available under the **not_operator** flag, I've tested my end and users do seem to be correctly assigned to segments based on the rules.

**Comment by Dogacel** [comment]
Hi, is the frontend of and not still being implemented? I am not able to see the `and not` button in our on-prem setup.

**Comment by dabeeeenster** [comment]
Heads up @kyle-ssg ?

**Comment by kyle-ssg** [comment]
> This is now available under the **not_operator** flag, I've tested my end and users do seem to be correctly assigned to segments based on the rules.

This @dabeeeenster, we need to simply turn on the not_operator feature for self hosted defaults if we're happy with it.

**Comment by dabeeeenster** [comment]
OK! `NOT` operator is live for self hosted installs.
