### ISSUE TITLE
Reset password email comes from example.com

### ISSUE THREAD

**Issue by luk355** [SolidStateGroup/bullet-train-api#385]
For self hosted Flagsmith, password reset emails are referring to example.com instead of the actual site. 

I did try to search for some setting which might affect domain value but couldn't find one. Did I miss it?

![image](https://user-images.githubusercontent.com/9592890/135842103-db1a16f5-1500-47fa-8e23-09fc2eb18106.png)

This is happening with 2.7.3 version deployed via flagsmith helm charts.

**Comment by dabeeeenster** [comment]
Check in the `django_site` DB table.

**Comment by pohorely** [comment]
Hello, I don't understand why this "administration" should be done by direct editing in DB while Flagsmith has an administration web-based portal.
Why do we have an "Organisation Administrator" accounts when it does not correspond with DB users?

Do you have a list of what is and what is not correct to edit in DB?

**Comment by luk355** [comment]
just confirming this is indeed the case. `django_site` table is by default populated by example.com domain settings.

![image](https://user-images.githubusercontent.com/9592890/135858380-d99877c8-f373-410a-bd00-5682b6d46c5b.png)

**Comment by dabeeeenster** [comment]
Hi - the email templates are powered by Django, and that's how Django constructs fully qualified URLs when sending out emails. 

I've added some info to the docs (https://docs.flagsmith.com/deployment/locally-api#email-environment-variables) which will help here.
