### ISSUE TITLE
Original source > HubSpot

### ISSUE THREAD

**Issue by annaredbond** [SolidStateGroup/bullet-train-api#3855]
We send contacts to HubSpot via the API, so they will always come up as original source = Offline. This means that all app signups don't have original source attribution in HubSpot, which affects tracking and ad performance for our paid ads. 

Can we either:
1. Implement tracking in the app domain so that their source can send across (right now when users reach the app they become "invisible" to HubSpot) OR
2. Capture and send their GCLID and their UTM values to HubSpot

More info and a Slack thread: https://flagsmith.slack.com/archives/C06D7F82WF7/p1714390077596589?thread_ts=1714058518.960549&cid=C06D7F82WF7 

Another Slack thread for more info:
https://flagsmith.slack.com/archives/C06D7F82WF7/p1713357279287279

**Comment by matthewelwell** [comment]
@annaredbond are you able to provide us with a way that we can test this out? i.e. some user journeys where we expect the UTM / GCLID parameters to be set?

**Comment by annaredbond** [comment]
@matthewelwell From our SEO/PPC agency: 
"They can create a custom UTM and test if it's pulling through to HubSpot. https://ga-dev-tools.google/campaign-url-builder/"

The UTM/GLCID parameters should be set for things like ads, third-party published content, newsletters etc. e.g. Someone clicks on a paid ad, gets sent to the app signup and then signs up for a free account. Currently, tracking data is not being sent to HubSpot when users sign up so we can't track the effectiveness of our campaigns and efforts.

So, when someone creates an account, the contact in HubSpot needs to be created or updated.

**Comment by matthewelwell** [comment]
https://legacydocs.hubspot.com/docs/methods/forms/submit_form
https://app-eu1.hubspot.com/forms
https://community.hubspot.com/t5/APIs-Integrations/How-to-Pass-Hubspot-User-Token-ID-from-Webflow-form-to-Hubspot/m-p/622419
https://community.hubspot.com/t5/APIs-Integrations/Create-contact-from-user-token/m-p/237102/highlight/true#M15998

Relevant cookie name: `hubspotutk`
