### ISSUE TITLE
API key should be hidden on environment setting page

### ISSUE THREAD

**Issue by luk355** [SolidStateGroup/bullet-train-api#386]
For security reasons, API key should be by default hidden when entering Environment setting page. 

![image](https://user-images.githubusercontent.com/9592890/135847041-ab3f86a4-2928-4c31-a4da-0f2adb79161e.png)

One solution would be display dots instead of real API key characters and add a new button to show key.

![image](https://user-images.githubusercontent.com/9592890/135847971-ee878ce2-03c9-4b8d-abc7-d16951df2d27.png)

**Comment by dabeeeenster** [comment]
The API key is not private - its sent to clients and trivially discoverable in code, similar to a Google Analytics API key. There is no reason for it  to be secured.
