### ISSUE TITLE
`util.pydantic.exclude_model_fields` fails when inside `freezegun.freeze_time`

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#3869]
The code [here](https://github.com/Flagsmith/flagsmith/blob/41a8aa3dd133424adef69b3f1b4ac0ae0df0bba8/api/environments/sdk/schemas.py#L5-L14) causes tests to fail with the following error:

```
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for [class 'datetime.datetime'](https://app.slack.com/client/TTKSY58MC/class%20'datetime.datetime'). Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
```

Related discussion: https://github.com/pydantic/pydantic/discussions/9343

**Comment by khvn26** [comment]
One solution, possibly, would be to add the `util.pydantic` model in freezegun's ignore list: https://github.com/spulec/freezegun?tab=readme-ov-file#ignore-packages

**Comment by khvn26** [comment]
Currently, the way to fix this is to add the following to `api/conftest.py`:

```python
def pytest_sessionstart(session):
    from environments.sdk.schemas import SDKEnvironmentDocumentModel
```

A less hacky way to avoid the error would be something like

```python
import freezegun

freezegun.configure(extend_ignore_list=["pydantic"])
```

but it will need a bit more trial and error to determine the exact module name to ignore.

**Comment by matthewelwell** [comment]
Fixed by workaround applied in https://github.com/Flagsmith/flagsmith/pull/3876. We should in future be able to remove the workaround if/when freezegun resolves the issue, but the workaround is sufficient for now.
