### ISSUE TITLE
Segment modal is closed after editing or creation

### ISSUE THREAD

**Issue by rolodato** [SolidStateGroup/bullet-train-api#3922]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When creating or editing a segment, the modal is closed immediately after changes are saved, with no confirmation or possibility to continue making further changes. I'm almost certain this did not use to be the case, and is inconsistent with the behaviour for features (the modal stays open as expected)

### Steps To Reproduce

1. Create or edit any segment
2. Save changes

The modal is closed with no confirmation that changes were saved, or possibility to continue making changes.

### Expected behavior

The modal should stay open and should show confirmation when changes are saved, similar to how Features behave:

https://github.com/Flagsmith/flagsmith/assets/829698/1571c287-7b11-40b0-9f2c-325605ba912d

**Comment by kyle-ssg** [comment]
It didn't used to be the case because our UX audit suggested we close the modal. 

I'll adjust it to keep it open.
