### ISSUE TITLE
Implement Civo Marketplace Tile

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#3936]
Instructions (also check README file):
Contributing to the Civo Marketplace involves the following steps:

Step 1: Identify the Application
- Choose an application that can be installed in a Kubernetes cluster and fits the criteria for inclusion in the Civo Marketplace.

Step 2: Prepare the Files
- Create the necessary files for the application's integration into the Civo Marketplace.
- The three main files required are:
  a. app.yaml: This contains the manifest files needed for the application to be installed on clusters. An example application like Linkerd or Acorn can be used as a reference.
  b. [Install.sh](https://install.sh/): For certain applications like Nginx or Istio, an [install.sh](https://install.sh/) script is needed. This script contains bash commands and can only be used by app maintainers. Istio, for instance, may require the installation of its CLI before installing the marketplace app.
  c. manifest.yaml: This file includes different types of installations, such as various versions of an application like Portainer. Additionally, it may include post-installation steps that need to be performed after the application is installed.

Step 3: Raise a Pull Request (PR)
- Use the provided template to raise a Pull Request in the Civo Marketplace repository.
- Include all the necessary files and documentation related to the application in the PR.

Step 4: Review and Approval
- Wait for the Civo Marketplace maintainers to review the PR.
- They will assess the quality, functionality, and compatibility of the application with the platform.

Step 5: Feedback and Iteration
- If required, make any necessary changes based on the feedback provided by the maintainers.
- Iterate through the review process until the PR meets the necessary standards.

Step 6: Merge and Publish
- Once the PR is approved, and any requested changes have been made, the maintainers will merge the changes into the Civo Marketplace repository.
- The application is now officially added to the Civo Marketplace and can be made available for users to install on their Kubernetes clusters.

**Comment by utkarsh-1905** [comment]
Hi @dabeeeenster , can I take this up (if no one is working on it already)? want to contribute more 😀

**Comment by matthewelwell** [comment]
Hi @utkarsh-1905 , thanks for reaching out here but I believe that @dabeeeenster is already most of the way through this work.

**Comment by utkarsh-1905** [comment]
Oh alright, will look for something else😄

**Comment by dabeeeenster** [comment]
If you want to work on my fork its here! https://github.com/civo/kubernetes-marketplace/compare/master...dabeeeenster:kubernetes-marketplace:master 

I'm not experienced with Civo however...

**Comment by utkarsh-1905** [comment]
I'll take a look

**Comment by utkarsh-1905** [comment]
Hey @dabeeeenster , I tested the scripts on my civo cluster, they are working fine, I added loadbalancer install instructions or portforward instruction in the post_install.md file and link to flagsmith docs in it. I have raised a pull request to your fork. Please review.

**Comment by dabeeeenster** [comment]
Awesome thanks - PR is in!
