### ISSUE TITLE
Change request diff shows incorrect value diff

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#3937]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

If a feature state has multiple values for different types then the diff can show the wrong previous value for the change request. 

### Steps To Reproduce

1. Create a feature state and change it's value from integer to boolean
2. Create a change request for that feature without changing the value
3. Notice that the change request diff shows that the value has changed

### Expected behavior

The change request diff should not show any change to the value

### Screenshots

<img width="368" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/14089968/16c4eaa2-8760-4455-a595-2122b3b4083f">

<img width="718" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/14089968/d70f1f7c-3305-4f6a-9364-7b5dda68feb5">

**Comment by kyle-ssg** [comment]
@matthewelwell I'm not exactly sure how we could solve this. It's not clear how we'd do a comparison if there are multiple values.

If i'm not mistaken, isn't this an invalid state? What does the SDK endpoint return since it only has 1 feature_state_value?

**Comment by kyle-ssg** [comment]
I think the issue here is more that the feature state has multiple values for different types. That's an invalid state, right @matthewelwell ?

feature_state_value only has 1 value in the SDK flags endpoint, so we don't really support (or should support) multiple types.

**Comment by matthewelwell** [comment]
> I think the issue here is more that the feature state has multiple values for different types. That's an invalid state, right @matthewelwell ?
> 
> feature_state_value only has 1 value in the SDK flags endpoint, so we don't really support (or should support) multiple types.

@kyle-ssg we don't clear the value for other types, we just set the `type` parameter which is used everywhere on the server side and should be respected by the FE too. You're right that, strictly, we should probably clear other values when the type changes, but clearing that data, vs getting the FE to respect the `type` value is a lot of effort.

**Comment by kyle-ssg** [comment]
Yeah, I think the FE should be clearing the other values here when a new one is set. I thought this was the case.
