### ISSUE TITLE
Navigation issues post plan change in organisation settings

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#3952]
When completing a change of plan in the organisation settings (note that this happens for upgrades and downgrades), the FE shows an error message regarding permissions and the navigation does not show all the options. 

https://www.loom.com/share/3f06d7304a7c477c86412b26349822be?sid=bf0245b7-e21e-4973-9de7-bb78bb934d41

**Comment by kyle-ssg** [comment]
@matthewelwell I believe this has been resolved and can be closed, though assign back to me if not

**Comment by matthewelwell** [comment]
@kyle-ssg I'm still able to reproduce this in staging but I'm not sure if that's a valid test case?
