### ISSUE TITLE
When showing a segment, list any flags that it is currently being used against 

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#396]
It is useful to know which flags are being overridden within the project for a particular segment. 

We might need to turn the segment editor into a full slide out panel?

**Comment by kyle-ssg** [comment]
I don't think there's backend support for this, if there is / something gets added assign back

**Comment by dabeeeenster** [comment]
On staging swagger

**Comment by kyle-ssg** [comment]
Unfortunately no, I don't believe there's any endpoint available to get a list of flags that have a particular segment override. Though maybe @matthewelwell @gagantrivedi could confirm.

**Comment by dabeeeenster** [comment]
Need to write an API endpoint to achieve the above.

**Comment by kyle-ssg** [comment]
I think this is a duplicate, closing in favour of https://github.com/Flagsmith/flagsmith/issues/1122
