### ISSUE TITLE
Identity Override Stays After Identity is Deleted

### ISSUE THREAD

**Issue by graytonio** [SolidStateGroup/bullet-train-api#3964]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When an identity has an identity override when the identity is deleted, the override remains and cannot be deleted because it fails to find the associated identity.

### Steps To Reproduce

1. Create a new identity
2. Create a identity override for a feature
3. Delete the identity
4. See the identity override still exists in the UI

### Expected behavior

If the identity is deleted the overrides for it should also be deleted.

### Screenshots

![image](https://github.com/Flagsmith/flagsmith/assets/9275515/e47731b0-77f9-4086-9ddd-849e24ec97b0)
![image](https://github.com/Flagsmith/flagsmith/assets/9275515/27cd97c8-1dd5-4a47-865d-6a7895327838)

**Comment by kyle-ssg** [comment]
Closed duplicate https://github.com/Flagsmith/flagsmith/issues/3611

**Comment by matthewelwell** [comment]
This has been fixed in a recent release.
