### ISSUE TITLE
Cancelling a flag override for a user shows the wrong set state value

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#397]
Flag is `disabled` in the Environment:

![image](https://user-images.githubusercontent.com/173290/136524712-972156d3-d808-4c20-8806-f3ce74bfe940.png)

Override the flag for a single Identity:

![image](https://user-images.githubusercontent.com/173290/136524991-7fdb1f68-fc9f-4e85-a611-a40837bf651c.png)

Click the toggle:

![image](https://user-images.githubusercontent.com/173290/136525087-1077f2ee-444c-491b-a63c-e912ba2970c1.png)

These values are wrong. This should say:

> This will turn 123123 "Off" for Development user bullet_train_sample_user

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/407
