### ISSUE TITLE
Clearing down a config value still shows "" in the dashboard

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#398]
To reproduce:

- Create a flag and set a config value
- Save flag
- Edit flag and delete config value completely
- Dashboard still shows `""` as the value. It should not show anything at all

![image](https://user-images.githubusercontent.com/173290/136525636-ad71386c-2cdc-40f4-827c-6c175133e5fe.png)

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/405/files
