### ISSUE TITLE
Search results not rendering on front end

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#399]
Using `D8EAC4B1-5371-4712-8D8D-D74B9621E624` as the Identity ID breaks search. 

![image](https://user-images.githubusercontent.com/173290/136530098-b666772e-61f2-42f7-86af-090e24258b0c.png)

I cant reproduce this with some other strings - maybe this GUID format is causing an issue somewhere?

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/404
