### ISSUE TITLE
Improve UX for segment condition descriptions

### ISSUE THREAD

**Issue by rolodato** [SolidStateGroup/bullet-train-api#4000]
### Is your feature request related to a problem? Please describe.

This is the UI to create a new segment:

![image](https://github.com/Flagsmith/flagsmith/assets/829698/fdd2ef4c-d338-4566-bdc1-2f736e835948)

The button "Show condition descriptions" does nothing until you figure out you need to create a condition first for this to make sense. This button is also confusingly named, since the option "Show condition descriptions" looks to be disabled, but this changes to "Hide condition descriptions" once enabled:

![image](https://github.com/Flagsmith/flagsmith/assets/829698/66084ebe-714c-4fbd-bb9c-6dd7c457048c)

I understand why this button exists, since adding a "description" field below every condition can get big fast:

![image](https://github.com/Flagsmith/flagsmith/assets/829698/664de6f0-76d1-431e-8f8a-e70c5f9addec)

Segment descriptions can be very valuable and we should encourage their use. We should get rid of the "Show condition descriptions" button to remove a useless choice for unfamiliar users and provide a better way to show and edit descriptions.

### Describe the solution you'd like.

One alternative would be to collapse all the available actions for a condition (edit, delete, add "Or") into a collapsible menu. Example from Vercel's environment variable editor:

![Screenshot 2024-05-21 at 16 51 05](https://github.com/Flagsmith/flagsmith/assets/829698/464c9846-ca3f-4d80-b3c8-a97f5a0e5271)

This would have the added benefit of making it less likely to fat-finger the Delete button, which currently requires no confirmation and has no undo.

### Describe alternatives you've considered

A quick fix might be to simply reduce the placeholder height for descriptions, and expand them as needed up to a certain limit. For example, this screenshot shows the default textbox height compared to the smallest my browser allows me to resize them:

![Screenshot 2024-05-21 at 16 54 26](https://github.com/Flagsmith/flagsmith/assets/829698/2cc55ab6-f8bb-4fc5-9afe-e75619b60d80)

I would be okay with something similar to this as well - the goal here is to reduce friction for creating segments.

### Additional context

Related issues:

https://github.com/Flagsmith/flagsmith/issues/3920
https://github.com/Flagsmith/flagsmith/issues/3918

**Comment by kyle-ssg** [comment]
> - The button "Show condition descriptions" does nothing until you figure out you need to create a condition


Isn't an issue once we re-add the placeholder rule.

> -This button is also confusingly named, since the option "Show condition descriptions" 


Ok agree yep will keep the label as show condition descriptions, I've added this in the same PR


> -Segment descriptions can be very valuable and we should encourage their use


Not sure I agree here, adding descriptions for every single rule is tedious and unnecessary for simple rules and is only useful if there's nuance or complex rules.

**Comment by rolodato** [comment]
> Not sure I agree here, adding descriptions for every single rule is tedious and unnecessary for simple rules and is only useful if there's nuance or complex rules.

That's fair - we might be able to come up with a better solution later on, so I'm happy to stay this way for now.
