### ISSUE TITLE
Add a placeholder AND condition when creating segments

### ISSUE THREAD

**Issue by rolodato** [SolidStateGroup/bullet-train-api#4001]
### Is your feature request related to a problem? Please describe.

This is the UI to create a new segment:

![image](https://github.com/Flagsmith/flagsmith/assets/829698/09057057-e0dc-4969-a093-58b4fe89c2cd)

To proceed, users must choose between "Add AND Condition" or "Add AND NOT Condition". I don't have data to back this up, but I would guess the vast majority of users will start by creating an AND condition. For unfamiliar users and demos, this masks what segments are for - if we showed the "trait" "condition" "value" boxes straight away, this becomes more self-evident by just looking at the UI. The word "trait" is mentioned twice in the text here, but it's not clear what it's referring to if you're not already familiar with segments.

The only situation that absolutely requires an AND NOT condition is if using an operator that does not have an opposite equivalent. As of today, these are only `Modulo` and `In`. `Matches regex` also does not have an opposite, but any regex is trivial to negate. All of these are fairly advanced use cases anyway.

### Describe the solution you'd like.

Show the segment creation UI with one empty AND condition placeholder, something like this:

![image](https://github.com/Flagsmith/flagsmith/assets/829698/a00281d7-f8cb-403e-a4d3-07946c9b3e62)

This makes it more obvious what segments are for and lets users define a simple segment without needing to choose between AND or AND NOT.

This also has the benefit of removing the second "NOTE" banner which just looks ugly.

### Describe alternatives you've considered

We might want to make a larger redesign of the segment condition editor as described here https://github.com/Flagsmith/flagsmith/issues/4000

However this issue is a quick win that can be implemented today with the current UI.

**Comment by kyle-ssg** [comment]
@rolodato Makes sense, I removed this initially due to the new AND NOT rule, but I was thinking the same about not being a more advanced case.
