### ISSUE TITLE
Feature states in versioning v2 environments fail to update if modal is not closed

### ISSUE THREAD

**Issue by rolodato** [SolidStateGroup/bullet-train-api#4025]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

In versioning v2 environments, trying to update the same feature without first closing the modal results in a 404, which forever blocks the "Update Feature Value" button until the page is fully reloaded.

### Steps To Reproduce

See video below.

1. Open any feature in an environment with versioning v2 enabled
2. Update the flag value to anything, save changes
3. Update the flag again, save changes again

Saving changes fails with a 404, and the Save button is forever stuck until the page is fully reloaded - see https://github.com/Flagsmith/flagsmith/issues/4026.

### Expected behavior

Saving the feature state should not fail.

### Screenshots

https://github.com/Flagsmith/flagsmith/assets/829698/29c14e37-068c-4482-b77e-09eb537e2317

**Comment by matthewelwell** [comment]
@kyle-ssg can you look into this tomorrow? Although we might be better off investing time in reworking the FE to use the new attributes I added in a PR [here](https://github.com/Flagsmith/flagsmith/pull/3991) to allow the FE to create a new version in a single endpoint.
