### ISSUE TITLE
Implement Modulo operator for Segment rules

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#403]
Implement the [modulo operator](https://en.wikipedia.org/wiki/Modulo_operation). 

 - [x] Python
 - [x] Java
 - [x] .NET
 - [x] Node
 - [x] Ruby
 - [x] Go
 - [x] Rust
 - [x] Elixir
 - [x] PHP

**Comment by aman0408** [comment]
Hi can I take this issue? Incase there is no progress on it?

**Comment by dabeeeenster** [comment]
Hey @aman0408  - that would be amazing! Jump on our Discord if you need to chat about it further! https://discord.gg/hFhxNtXzgm

**Comment by aman0408** [comment]
Sure, will be working on it over the weekend!

**Comment by dabeeeenster** [comment]
@gagantrivedi @matthewelwell this will need to be migrated over to the engine

**Comment by matthewelwell** [comment]
This is now done in the core API. We need to implement it in each of the engines.

**Comment by gagantrivedi** [comment]
Python engine https://github.com/Flagsmith/flagsmith-engine/pull/144

**Comment by gagantrivedi** [comment]
Rust engine https://github.com/Flagsmith/flagsmith-rust-flag-engine/pull/6

**Comment by gagantrivedi** [comment]
Golang - https://github.com/Flagsmith/flagsmith-go-client/pull/51

**Comment by matthewelwell** [comment]
Ruby - https://github.com/Flagsmith/flagsmith-ruby-client/pull/21
