### ISSUE TITLE
Docs - Correct list of feature differences between OS and Enterprise

### ISSUE THREAD

**Issue by kyle-ssg** [SolidStateGroup/bullet-train-api#4047]
### Is your feature request related to a problem? Please describe.

The following doc does not contain the full differences between OS and Enterprise, e.g. Audit log and Change Requests are Enterprise only https://docs.flagsmith.com/deployment/configuration/enterprise-edition

### Describe the solution you'd like.

A single source of truth listing the differences between enterprise and OS

### Describe alternatives you've considered

We could also have this in the website.

**Comment by dabeeeenster** [comment]
https://docs.flagsmith.com/version-comparison

**Comment by kyle-ssg** [comment]
I think either we should:

1. Have an area on the site where we list ee benefits
2. Link https://docs.flagsmith.com/version-comparison in the ee docs page

Either way we could do 2 for now
