### ISSUE TITLE
Add a Github refresh button that updates Issue/PR drop downs

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#4078]
### Is your feature request related to a problem? Please describe.

With the github integration, its hard to know what causes the Issue/PR lists to be refreshed. If you go to the link page on the Flagsmith dashboard before you've created a github issue, the list in flagsmith does not refresh to reflect the new issue. 

### Describe the solution you'd like.

Add a "refresh" icon/button next to the list that forces an update

### Describe alternatives you've considered

Refreshing the entire Flagsmith dashboard UI works but is a hack

**Comment by novakzaballa** [comment]
It was closed as there's already an issue for this. https://github.com/Flagsmith/flagsmith/issues/4019
