### ISSUE TITLE
Audit log search is client side only

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#408]
Needs to be server side.

Add new API endpoint which accepts filter elements:

- Text String
- Project ID
- Environment IDs

And returns pageable results.

**Comment by gagantrivedi** [comment]
Adds a query param named `search` to search logs https://github.com/Flagsmith/flagsmith/pull/633

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/653 As of this, frontend for this will be live under the flag audit_api_search, the remote config value of this flag determines the page size
