### ISSUE TITLE
Allow organisations to force SSO for all users

### ISSUE THREAD

**Issue by rolodato** [SolidStateGroup/bullet-train-api#4093]
### Is your feature request related to a problem? Please describe.

When customers are growing into an Enterprise subscription that allows them to use SSO, they will usually have one or more preexisting non-SSO users who were manually invited to their Flagsmith organisation. Even if SSO is enabled for their organisation, there is nothing that prevents these pre-SSO users from logging in with their own passwords that are not managed by an enterprise identity provider. This is a policy/security risk for customers.

The closest that customers can currently get to enforcing SSO is to:

* Delete all non-SSO users from their organisation. This can be confusing for users who did not get the memo about SSO being configured - from their perspective, they would still be able to log in to Flagsmith, except they would not have access to the organisation anymore.
* Not give out the Organisation Administrator role to any users, as this role is this required to invite additional users to an organisation. There must be always at least one user with this role, so this hole cannot currently be closed, only minimised
* Re-create any existing invite links and never give them out again. This is an unreasonable expectation to have from customers, and nothing prevents the single organisation admin from sending the link to other people

Even if customers manually delete their pre-SSO users, this can be error-prone as the UI does not show which login method each user has.  For example, here `rodrigo.lopezdato+1@flagsmith.com` is an SSO user, and all others are non-SSO:

![image](https://github.com/Flagsmith/flagsmith/assets/829698/2d49f6cf-8768-4ad4-a105-dd6174a86d5c)

### Describe the solution you'd like.

Add an admin-only organisation-level option to force SSO for all logins. This should have the following effects:

* Revoke all non-SSO user sessions in the organisation, forcing them to log in again
* When a non-SSO user tries to access an organisation with "force SSO" enabled, they should be unable to take any actions except logging in with SSO, or switching to a different organisation if they have any. If possible, there should be a link to direct users to log in with their organisation's SSO provider, to prevent them needing to reach out to an administrator for instructions

Also, the following should always happen, even if "Force SSO" is not enabled: If an SSO user logs in with the same email as an existing non-SSO user within the same organisation, this should remove the non-SSO user's organisation membership and, if possible, merge all preexisting data into the new SSO user.

Even if an organisation forces its users to use SSO, there should still be an escape hatch to manually add a non-SSO user, for example only usable from Django Admin. This still lets Flagsmith staff access customer organisations if needed, or lets self-hosting admins access Flagsmith if their SSO provider is unavailable or misconfigured.

### Describe alternatives you've considered

It might be less risky to not do any data merging between SSO/non-SSO users, and instead make users manually delete non-SSO users as needed. To achieve this we would need at the very least to show which identity provider each organisation user uses to log in (GitHub/Google/SAML/AD/password).

**Comment by matthewelwell** [comment]
@rolodato this is done via our domain auth methods logic. I'm not sure if this is actually documented anywhere though so we should discuss. Code is [here](https://github.com/Flagsmith/flagsmith-auth-controller).

**Comment by matthewelwell** [comment]
Closing based on above comment.
