### ISSUE TITLE
Allow organisation admins to mandate 2fa for their organisation

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#411]
This should be a scale-up only feature. 

Need to figure out how we upgrade existing accounts that don't have 2fa but are logging into an organisation that has it mandated.

**Comment by kyle-ssg** [comment]
We can just force the 2f setup screen on login if 1 or more orgs have a field force_2fa

**Comment by kyle-ssg** [comment]
Frontend is live on the flag force_2fa

Basically, the backend just needs to persist a field called "force_2fa" and return it on the organisations endpoint.

The frontend will send up this bool in the put to the organisation, this option is only visible on scaleup with the flag force_2fa

![image](https://user-images.githubusercontent.com/8608314/144722986-aec073ec-63cc-481c-9a98-a70a11d9432a.png)

![image](https://user-images.githubusercontent.com/8608314/144722999-e25470b2-56e2-42f4-9567-60535584765d.png)


If a user does not have 2fa and has an organisation with this as true they will see this post login no matter what page they attempt to visit. This will also be the case if the user attempts to disable 2fa.

![image](https://user-images.githubusercontent.com/8608314/144723212-cb334f44-858a-4746-b6ae-05a4f14e8538.png)

![image](https://user-images.githubusercontent.com/8608314/144723395-23124912-a6a8-4d45-8a0d-46597286cd2f.png)

**Comment by kyle-ssg** [comment]
This was marked as done on the roadmap, but from what I can see the feature flag hasn't been enabled in production?

**Comment by gagantrivedi** [comment]
Just to double-check if this is enabled, user should not be allowed to log in from the API as well? And not just the UI? @dabeeeenster  @matthewelwell

**Comment by gagantrivedi** [comment]
Questions:

1. Scenario 1: org admin has enabled force 2fa but some of the users have not enabled 2fa. What should happen in that case? 
Option 1. They should not be allowed to log in
 problems: How are they going to enable 2fa in that case? 
 
 Solution: only allow org admin to enable 2fa if all the user have 2fa configured in that organisation.

**Comment by novakzaballa** [comment]
I think we can not implement a general BE enforcement for 2FA, until we provide an alternative for enterprise customers to access our API. Currently, I think the only way we provide is by using an API Key related with a user right? So we should either provide exceptions (Which will be either a vulnerability or will complicate things), or an alternative API Key though the roles as I understand is planned, right?
