### ISSUE TITLE
Improve Users page to display search options when waiting for initial Identities API call

### ISSUE THREAD

**Issue by luk355** [SolidStateGroup/bullet-train-api#416]
Initial load of Users page page takes couple of seconds to load on a project with lots of users. As basic developer workflow is __Open Users page -> search for user -> go to user details to update given flag__, it would be great to redesign the Users page so that the user does not have wait for initial Identities call and can search for his/her user right away.

![image](https://user-images.githubusercontent.com/9592890/137684725-4aa22a9e-dc24-4974-8848-1e9228f6d701.png)

## Suggested solution

Consider displaying Users table heading with search options when doing the initial Identities call.

![image](https://user-images.githubusercontent.com/9592890/137685992-c4aa8f4e-e525-4dbe-adcc-fe518ca32d6e.png)

**Comment by kyle-ssg** [comment]
https://github.com/Flagsmith/flagsmith/pull/433

@dabeeeenster Although this is done, I think the above is worth looking at from an api perspective. Flagsmith's own users come back in 40ms, I don't see why this endpoint would take long for other people.

**Comment by dabeeeenster** [comment]
Over to @gagantrivedi we need to generate some test data with large (millions) of users and traits.

**Comment by dabeeeenster** [comment]
@luk355 are you able to clarify - is this happening for you whilst self hosting or with our SaaS product? If SaaS, can you email us directly with the details of your organisation and we can take a look - thanks!

**Comment by luk355** [comment]
Thanks for such quick fix, @kyle-ssg. At the moment, we have more than 8M users in the organization and growing.

@dabeeeenster, that's happening on our self-hosted instance which is hosted in Azure and connected to a Azure PostgreSQL server. We are definitely planning investigate the performance via Sentry.

**Comment by dabeeeenster** [comment]
OK thanks @luk355  - if you can get some metrics/telemetry that would be helpful. Sentry and maybe see if there are slow logs being recorded against the database?
