### ISSUE TITLE
"Create Segment" disappears when deleting last segment

### ISSUE THREAD

**Issue by rolodato** [SolidStateGroup/bullet-train-api#4256]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

Self-explanatory, watch this video:

https://github.com/Flagsmith/flagsmith/assets/829698/cea98bee-4e4d-48dd-8235-3cf9c91c73e6

### Steps To Reproduce

Watch video above.

### Expected behavior

...

**Comment by kyle-ssg** [comment]
The replication I believe is when you have a feature-specific segment leftover.
