### ISSUE TITLE
Change Request audit log should include the creator of the Change Request

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#4267]
### Is your feature request related to a problem? Please describe.

Currently Change Requests show up in Audit log events but with the "User" field blank.

### Describe the solution you'd like.

Set the "User" field as the person who created the Change Request

### Describe alternatives you've considered

None

**Comment by matthewelwell** [comment]
Cannot reproduce

![Image](https://github.com/user-attachments/assets/671a6c1d-e002-4465-88f4-6a59e4689af6)
