### ISSUE TITLE
google oAuth not work

### ISSUE THREAD

**Issue by aakuz** [SolidStateGroup/bullet-train-api#4319]
### How are you running Flagsmith

- [X] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

Google oAuth not work 

### Steps To Reproduce

- I use this template https://raw.githubusercontent.com/Flagsmith/flagsmith/main/docker-compose.yml
- Configure environment: OAUTH_CLIENT_ID & OAUTH_CLIENT_SECRET
```dockerfile
version: '3'

volumes:
  pgdata:

services:
  postgres:
    image: postgres:15.5-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flagsmith
    container_name: flagsmith_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d flagsmith -U postgres']
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 20s

  flagsmith:
    image: flagsmith.docker.scarf.sh/flagsmith/flagsmith:latest
    environment:
      DJANGO_ADMIN_SSO_OAUTH_CLIENT_ID: skippp
      DJANGO_ADMIN_SSO_OAUTH_CLIENT_SECRET: skippp
      OAUTH_CLIENT_ID: skippp
      OAUTH_CLIENT_SECRET: skippp
      # All environments variables are available here:
      # API: https://docs.flagsmith.com/deployment/locally-api#environment-variables
      # UI: https://docs.flagsmith.com/deployment/locally-frontend#environment-variables

      DATABASE_URL: postgresql://postgres:password@postgres:5432/flagsmith
      USE_POSTGRES_FOR_ANALYTICS: 'true' # Store API and Flag Analytics data in Postgres

      ENVIRONMENT: production # set to 'production' in production.
      DJANGO_ALLOWED_HOSTS: '*' # Change this in production
      ALLOW_ADMIN_INITIATION_VIA_CLI: 'true' # Change this in production
      FLAGSMITH_DOMAIN: localhost:8000 # Change this in production
      DJANGO_SECRET_KEY: secret # Change this in production
      ENABLE_ADMIN_ACCESS_USER_PASS: 'true'
      # PREVENT_SIGNUP: 'true' # Uncomment to prevent additional signups
      ALLOW_REGISTRATION_WITHOUT_INVITE: 'true'
      AXES_ONLY_USER_FAILURES: 'false'

      # Enable Task Processor
      TASK_RUN_METHOD: TASK_PROCESSOR # other options are: SYNCHRONOUSLY, SEPARATE_THREAD (default)
    ports:
      - 8000:8000
    healthcheck:
      test: ['CMD-SHELL', 'python /app/scripts/healthcheck.py']
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 20s
    depends_on:
      postgres:
        condition: service_healthy

  # The flagsmith_processor service is only needed if TASK_RUN_METHOD set to TASK_PROCESSOR
  # in the application environment
  flagsmith_processor:
    image: flagsmith.docker.scarf.sh/flagsmith/flagsmith:latest
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/flagsmith
      USE_POSTGRES_FOR_ANALYTICS: 'true'
    depends_on:
      flagsmith:
        condition: service_healthy
    command: run-task-processor
``` 

I followed documents https://docs.flagsmith.com/deployment/hosting/locally-api#environment-variables and configure my Flagsmith for Google oAuth, but I not find buttom for google login.
What I am doing wrong?

PS And which Authorized redirect URI for oAuth?

### Expected behavior

I see form for google login 

### Screenshots

<img width="581" alt="Screenshot 2024-07-09 at 17 11 48" src="https://github.com/Flagsmith/flagsmith/assets/37076190/9bff83a8-8b7f-4934-8648-9a67959356e7">

**Comment by rolodato** [comment]
Those environment variables are used to use Google OAuth to log in to Django admin, not to Flagsmith itself. You need to configure the `oauth_google` Flagsmith on Flagsmith feature flag to log in to Flagsmith using Google: https://docs.flagsmith.com/deployment/overview#oauth_google

I'll close this issue for now, let me know and we can re-open if needed.

**Comment by aakuz** [comment]
Okay, Thank you
Would do you like show me example full flag value for  https://docs.flagsmith.com/deployment/overview#oauth_google becouse origin google json something other.
And I not found example for redirect_uris
