### ISSUE TITLE
Links to individual segments don't work unless they're for a segment on page 1

### ISSUE THREAD

**Issue by BioSurienDG** [SolidStateGroup/bullet-train-api#4389]
### How are you running Flagsmith

- [X] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

If you pass the id of a segment to the Flagmith url (ex. [baseurl]/project/2/segments?id=3) usually it will open the panel for the segment. However, if the segment is on page 2 it doesn't automatically navigate to page 2 - you have to do it yourself and then the panel pops up

### Steps To Reproduce

1. Navigate to a segment on page 1 of the segments ui
2. Click on the segment to open the configuration panel on the right
3. Copy the url in the browser bar
4. Try to navigate to this url in another tab and note that it opens up the configuration panel for this feature
5. Now repeat steps 1 to 3 but instead of clicking a segment visible on page 1 click on one that is only available on page 2.
6. Now repeat steps 3-4 but note that the configuration panel for this feature does not automatically open until you manually navigate to page 2

### Expected behavior

The manual navigation mentioned in step 6 of the "Steps to Reproduce" section above should not be needed. The browser link should automatically open the configuration for the feature identified in the id in the url regardless of what page it is on.

**Comment by matthewelwell** [comment]
Thanks for raising this @BioSurienDG . We'll take a look into it and get it fixed up.

**Comment by kyle-ssg** [comment]
This slipped through the cracks, the good news is it's already fixed!
