### ISSUE TITLE
Organisation level integrations

### ISSUE THREAD

**Issue by kyle-ssg** [SolidStateGroup/bullet-train-api#4434]
### Is your feature request related to a problem? Please describe.

Some integrations should be able to be enabled at the organisation level so that they don't have to be created per project.

### Describe the solution you'd like.

- Configure integration remote config ``project_integration: true organisation_integration:true``
- Allow integrations to be viewed / created at the organisation level

### Describe alternatives you've considered

Add a switch in the project integrations config, this seems quite convoluted

**Comment by kyle-ssg** [comment]
Backend related PR https://github.com/Flagsmith/flagsmith/pull/4400

**Comment by khvn26** [comment]
`ghcr.io/flagsmith/flagsmith-api:pr-4400` Docker image is available for testing the backend.

You can use the `/api/v1/organisations/{org_id}/integrations/grafana` analogous with the project-level one.

**Comment by khvn26** [comment]
I propose the new keys to be named `perProject` and `perOrganisation` for consistency's sake.

For backwards compatibility, consider assuming `perProject` to be true if it's not included.

**Comment by khvn26** [comment]
@kyle-ssg The backend for this is now in staging.
