### ISSUE TITLE
Search Identities based on Trait key/value

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#444]
Need to design a way to index traits with the global data store. Some options:

- https://aws.amazon.com/about-aws/whats-new/2015/08/amazon-dynamodb-elasticsearch-integration/
- https://typesense.org/docs/guide/dynamodb-full-text-search.html

In SaaS, this is problematic due to the size of the data we are storing and would need to index. 

For self hosted/open source we should investigate using postgres to drive this.

**Comment by landonjs** [comment]
We could really use something like this as well +1

**Comment by Rednegniw** [comment]
Hi! I'd really love this feature as well.

**Comment by matthewelwell** [comment]
Superseded by #4016
