### ISSUE TITLE
Identity overrides are not deleted when deleting Edge identities

### ISSUE THREAD

**Issue by rolodato** [SolidStateGroup/bullet-train-api#4457]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

In SaaS, deleting an identity that has identity overrides associated with it will not delete the identity overrides. These left-over identity overrides cannot be deleted or modified - any actions will fail with a 404.

This is a cosmetic bug, as the left-over identity overrides do not have any effect, and the identity can be re-created with the same identifier and have overrides associated with it.

### Steps To Reproduce

1. In SaaS, create an edge identity `A`
2. Create an identity override for this identity on any feature
3. Delete the identity
4. Navigate back to the feature - it will still show identity overrides existing, which cannot be modified or deleted

### Expected behavior

Deleting an identity should also delete all overrides associated with it, the same way that Core currently behaves.

### Screenshots

Two identity overrides for the same identity, but only one is valid:

<img width="1472" alt="image" src="https://github.com/user-attachments/assets/05c5f753-2f02-4601-917e-b2e38afb54aa">

**Comment by gagantrivedi** [comment]
Related: https://github.com/Flagsmith/flagsmith/issues/3370
