### ISSUE TITLE
Creating an environment can take a long time and seem unresponsive

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#4489]
Currently, when creating a new environment, it is only possible to do so by cloning from an existing environment. This process can take a long time, so the UI often looks like it's hanging. 

There is a PR open on the BE [here](https://github.com/Flagsmith/flagsmith/pull/4005/files) which asyncs this logic and adds a new `is_creating` status to the environment which the FE should use to show a UI prompt, and prevent the user from opening the environment until the creation is complete.

**Comment by kyle-ssg** [comment]
Hmm the create button does indicate loading state though. I'm not sure it'd make sense to offer a way to create an environment without basing on an existing environment?

![image](https://github.com/user-attachments/assets/b994938b-76f1-4eb7-bbbd-c7476f92f8ac)

**Comment by matthewelwell** [comment]
Instead of making the BE automatically async the cloning of feature states, I have added a new attribute (`"clone_feature_states_async": true|false`) to the payload on the clone environment endpoint to trigger the async behaviour. Note that the default is false meaning that we should be able to merge the BE without needing the FE changes.
