### ISSUE TITLE
Unable to delete feature when using permission via role assigned to a group

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#4506]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When using a role, configured with the delete feature permission, it is not possible to delete features. Note that it _is_ possible to achieve this if the permission is directly attached to the group. 

### Steps To Reproduce

1. Create a role with the DELETE_FEATURE permission on a given project (note that you will also need at least view project and view environment on at least one environment in the project)
2. Assign the role to a group, and add a user to the group
3. Log in with the user in the group 
4. Try to delete a feature in the project
5. Notice that the feature is not deleted and a 403 error is thrown

### Expected behaviour

The feature is successfully deleted

### Screenshots

<img width="605" alt="image" src="https://github.com/user-attachments/assets/b55f9c1b-ef05-438b-b2e4-cb775e23a3d1">

**Comment by gagantrivedi** [comment]
https://github.com/Flagsmith/flagsmith-rbac/pull/24
