### ISSUE TITLE
Add missing `permission_classes` / `get_permissions` to views 

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#4532]
The views listed below need to be updated with `permission_classes` / `get_permissions`.

- `api/integrations/slack/views.py:SlackGetChannelsViewSet` — potentially leaks Slack channels accessible to previously created integration

**Comment by matthewelwell** [comment]
These 2 are actually false positives, the permissions are added in `urls.py`. See [here](https://github.com/Flagsmith/flagsmith/blob/main/api/sales_dashboard/urls.py#L10) and [here](https://github.com/Flagsmith/flagsmith/blob/main/api/sales_dashboard/urls.py#L43).

> The following views are protected by admin login but have no permissions at class or action level:
>
> api/sales_dashboard/views.py:OrganisationList
> api/sales_dashboard/views.py:EmailUsage
