### ISSUE TITLE
Support traits for local evaluation mode

### ISSUE THREAD

**Issue by khvn26** [SolidStateGroup/bullet-train-api#4553]
Currently, stored identity traits are not expected to be included for the overrides in the environment document. However, the server-side SDKs will take them into account should they be provided by the SDK API.

For Edge API:
- Consider the cost of reading every identity document individually when pulling identity overrides for local evaluation mode.
- Alternatively, design and implement trait storage in the Edge V2 table.

For Core API:
- Verify that stored traits are returned along with the environment document.

**Comment by matthewelwell** [comment]
I think this would be a significant amount of work for not a huge amount of benefit so I'm going to close it for now, and let's see what the user base's reaction is to identity overrides in local evaluation first.
