### ISSUE TITLE
Could you please provide a docker-compose that uses mysql?

### ISSUE THREAD

**Issue by Waylon-Firework** [SolidStateGroup/bullet-train-api#4563]
Could you please provide a docker-compose that uses mysql? Thanks.

https://github.com/Flagsmith/flagsmith/blob/main/docker-compose.yml

Should I delete USE_POSTGRES_FOR_ANALYTICS when using MySQL?

**Comment by matthewelwell** [comment]
Hi @Waylon-Firework, I'm afraid that we do not support the MySQL database engine.
