### ISSUE TITLE
Add additional segment rule operators

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#457]
- Begins With
- Ends With
- ~Is One Of~
- Dost not match Regex
- Does not begin with
- Does not end with
- Is not one of

**Comment by matthewelwell** [comment]
This depends on https://github.com/Flagsmith/flagsmith/issues/382 (and we should not add these: Dost not match Regex, Does not begin with, Does not end with, Is not one of)
