### ISSUE TITLE
Bug: The SDK initialisation code provided, is incorrect

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SolidStateGroup/bullet-train-api#4593]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

The maven dependency code to add flagsmith Java client SDK is incorrect.
It's currently :point_down:
```xml
<dependency>
<groupId>com.flagsmith</groupId>
<artifactId>flagsmith-java-client</artifactId>
<version>5.0.0/version>
```
It doesn't have closing `</dependency>` tag and a wrong closing version tag (`/version>`) which must be `</version>`.

### Steps To Reproduce

1. Go to a project in Flagsmith.
2. Click on `Environments`.
3. Click on `Features` and see the code example section for initializing the SDK.

### Expected behavior

The dependency code for maven pom file must be :point_down:
```xml
<dependency>
            <groupId>com.flagsmith</groupId>
            <artifactId>flagsmith-java-client</artifactId>
            <version>5.0.0</version>
</dependency>
```

### Screenshots

![image](https://github.com/user-attachments/assets/a062c214-1c81-4915-b605-2f9fd5761c6e)

**Comment by SaptarshiSarkar12** [comment]
I have found out that the problem lies in this segment of code, and I would like to work on this issue.
https://github.com/Flagsmith/flagsmith/blob/0c38bda7cba419fcc7d5352f5d1aa42b4685e8d4/frontend/common/code-help/install/install-java.js#L3-L8

**Comment by matthewelwell** [comment]
Thanks @SaptarshiSarkar12 , please feel free to submit a PR to resolve. Thanks!

**Comment by SaptarshiSarkar12** [comment]
Thank you @matthewelwell.
I also found another same type of issue under **Initialising your project** code example.
The code shown in `flagsmith.com` is :point_down: 
![Screenshot from 2024-09-06 14-19-50](https://github.com/user-attachments/assets/b82fa434-28ee-4f32-a73e-b817a1b142fa)
The `false` shouldn't be there and is produced by this code :point_down: 
https://github.com/Flagsmith/flagsmith/blob/4e85975d231ee41e9ddf2f1c87e96b19dc234a30/frontend/common/code-help/init/init-java.js#L3-L14

@matthewelwell Should I also patch that fix along with this issue or should I create a new issue for that?

**Comment by matthewelwell** [comment]
Good catch, thanks! You can solve them both in the same PR, yep.

**Comment by SaptarshiSarkar12** [comment]
@matthewelwell Okay. Thank you :smile:.
