### ISSUE TITLE
Add delete button to identity detail page

### ISSUE THREAD

**Issue by kyle-ssg** [SolidStateGroup/bullet-train-api#4623]
### Is your feature request related to a problem? Please describe.

Currently you can only delete identities from the list view

### Describe the solution you'd like.

Add way to delete identity from detail view

### Describe alternatives you've considered

N/A

**Comment by jatingodnani** [comment]
@kyle-ssg could you explain in detail?

**Comment by matthewelwell** [comment]
@jatingodnani we want to replicate the delete identity behaviour available in the list view as per the following screenshot on the page that you see when you click into an individual identity. 

<img width="1195" alt="Screenshot 2024-09-27 at 12 17 51" src="https://github.com/user-attachments/assets/a32e944e-94a4-46bf-855d-6e10fdb6c272">
