### ISSUE TITLE
Scrollbar missing on JSON editor

### ISSUE THREAD

**Issue by turgaygulmez** [SolidStateGroup/bullet-train-api#4638]
### How are you running Flagsmith

- [X] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

User overrides JSON editor scrollbar is missing

### Steps To Reproduce

1- Go to environment users section
2- Search and find any user
3- Click on specific user to display settings for that particular user
4- Open a flag which is JSON type and has a long JSON config
5- Click show more 
6- The right panel model is not scrollable therefore "Update Feature" is not visible

### Expected behavior

Panel model to be scrollable

### Screenshots

![image](https://github.com/user-attachments/assets/7b82e224-8f21-4af9-9d37-5ecf297d357c)

**Comment by matthewelwell** [comment]
@turgaygulmez it seems as though you are self hosting and running a much older version than the latest (since the 'users' tab was updated to 'identities' a long time ago). Can you please upgrade to the latest version and re-open if this is still an issue?
