### ISSUE TITLE
PUT to organisations/:id/roles/:id returns 400 name already exists in organisation

### ISSUE THREAD

**Issue by kyle-ssg** [SolidStateGroup/bullet-train-api#4640]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

Currently I'm unable to update the tags associated with a role whilst keeping its name the same, it's incorrectly detecting a role with that name already exists. 

### Steps To Reproduce

Do a PUT to organisations/:id/roles/:id 

### Expected behavior

I can update a role without modifying the name

**Comment by gagantrivedi** [comment]
Fixed in https://github.com/Flagsmith/flagsmith/pull/4523
