### ISSUE TITLE
Get /api/v1/identities/ can request multiple environments for some reason?

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#466]
https://sentry.io/organizations/flagsmith/performance/flagsmith-api:beecdd1e6de247059c6f21db0cb35da7/?statsPeriod=1h&transaction=%2Fapi%2Fv1%2Fidentities%2F

![image](https://user-images.githubusercontent.com/173290/139944340-e040ee09-255d-4a6c-ac3d-046911a2f838.png)

**Comment by dabeeeenster** [comment]
@gagantrivedi did you say you couldnt reproduce? If you cant, just close this.

**Comment by gagantrivedi** [comment]
can't reproduce.
