### ISSUE TITLE
Announcement banner styling issue

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#4679]
See the following screenshots. The colours on the CTA are not correct. Possibly caused by #4634 ? 

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/6e176661-0acb-42bb-ad1e-483756bc6bd8">

<img width="1047" alt="image" src="https://github.com/user-attachments/assets/26beaf72-fbc8-4f1a-901f-09800e3ba6eb">

**Comment by kyle-ssg** [comment]
Spotted / fixed earlier
