### ISSUE TITLE
"@" Breaks page when entered in any search bar

### ISSUE THREAD

**Issue by Edenbj** [SolidStateGroup/bullet-train-api#4685]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

When I input the “@” symbol into any search bar the app redirects to a broken page suggesting a faulty request to the controller/handler. 

When typing in other special chars it handles them as expected. 

### Steps To Reproduce

**Example 1**

1. Login as a user
2. Select any project
3. Click "Identities"
4. Click on any identity
5. In the search bar type "@" OR any other search
6. Err! - Page redirect https://app.flagsmith.com/404?entity=environment

### Expected behavior

Search to filter with no results found.

### Screenshots

Already sent via Chat as includes PII.

**Comment by matthewelwell** [comment]
Thanks @Edenbj , I've reproduced this. We'll get this fixed up as soon as we can.
