### ISSUE TITLE
Webhook signature validation is not working

### ISSUE THREAD

**Issue by singhaniket26** [SolidStateGroup/bullet-train-api#4762]
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [x] Some other way (add details in description below)

### Describe the bug

I am using app.flagsmith.com with an account and have created an azure function which is called through webhook page of the flagsmith. For security thing i have used a secret and I am validating the signature at azure function but this doesn't seem to work at all.

### Steps To Reproduce

Go to environment settings and click on webhook and then on create feature webhook. See the screenshot attached. 
Code used in C# is 
public static bool ValidateSignature(string hexSecret, string jsonRequestBody, string receivedSignature)
{
    // Convert hex string to byte array
    byte[] secretKeyBytes = Encoding.UTF8.GetBytes(hexSecret);

    // Convert JSON string to byte array
    byte[] requestBodyBytes = Encoding.UTF8.GetBytes(jsonRequestBody);

    // Generate HMAC-SHA256 signature
    using (var hmac = new HMACSHA256(secretKeyBytes))
    {
        byte[] hashBytes = hmac.ComputeHash(requestBodyBytes);
        string expectedSignature = BitConverter.ToString(hashBytes).Replace("-", "").ToLower();
        // Compare signatures in a time-constant manner
        return CryptographicOperations.FixedTimeEquals(
            Encoding.UTF8.GetBytes(expectedSignature),
            Encoding.UTF8.GetBytes(receivedSignature)
        );
    }
} and other one tried is 
   public static bool GenerateAndValidateSignature(string secret, string message, string receivedSignature)
   {
       using (var hmac = new HMACSHA256(Encoding.UTF8.GetBytes(secret)))
       {
           // Compute the HMAC hash
           byte[] hashBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(message));

           // Convert hash to Base64 string
           var expectedSignature = Convert.ToBase64String(hashBytes);
           var isValid = expectedSignature.Equals(receivedSignature, StringComparison.Ordinal);
           return isValid;
       }
   }
both of the above are not working

### Expected behavior

It must be validate at azure function.

### Screenshots

![Image](https://github.com/user-attachments/assets/4eec030e-420a-4d32-9a00-5c3d7ab839bd)

**Comment by singhaniket26** [comment]
One of the other codes I have used is -
public static string ComputeHMACSHA256(string message, string secret)
{
    byte[] keyBytes = Encoding.UTF8.GetBytes(secret);
    byte[] messageBytes = Encoding.UTF8.GetBytes(message);

    using (HMACSHA256 hmac = new HMACSHA256(keyBytes))
    {
        byte[] hashBytes = hmac.ComputeHash(messageBytes);
        return BitConverter.ToString(hashBytes).Replace("-", "").ToLower();
    }
}
public static bool ConstantTimeEquals(string a, string b)
{
    if (a == null || b == null || a.Length != b.Length)
    {
        return false;
    }

    int result = 0;
    for (int i = 0; i < a.Length; i++)
    {
        result |= a[i] ^ b[i];
    }
    return result == 0;
}

**Comment by rolodato** [comment]
Please share example payloads and signatures that you're receiving/calculating. Are you using the "test your webhook" button or receiving an actual payload?

**Comment by singhaniket26** [comment]
Yes I am using "test your webhook" button with the sample payload which is there on screen itself. Secret used is "9f82ba9d2a5e2e6e7a128c4b53f59e9fc8d9f4b4b5e0b40d82140e67d104c9b3". The signature which I have received at function app from flagsmith is "475e03286cd0faf388e9179a437e158e7070b19b14e78c78aabde85030adc612" and using the algo the calculated signature comes out different from this and hence validation fails.

**Comment by rolodato** [comment]
You may be running into this bug https://github.com/Flagsmith/flagsmith/issues/3690

Can you confirm if you still get an invalid signature when receiving an actual payload and not using "test your webhook"?

**Comment by singhaniket26** [comment]
With actual payload it works. You can close this bug and please publish a disclaimer on your portal for the issue since it takes up a lot of time for us to identify such things
