### ISSUE TITLE
ALLOW_SIGNUPS not working in combined docker image

### ISSUE THREAD

**Issue by RadovanPelka** [SolidStateGroup/bullet-train-api#480]
Hi,
pls fix ALLOW_SIGNUPS not working, module fe

![image](https://user-images.githubusercontent.com/29738200/140525153-ee02ebfa-f0ba-4bf8-9e2f-9b1c3b6c03e4.png)

**Comment by dabeeeenster** [comment]
This is on account of the merging of the front and back end

**Comment by matthewelwell** [comment]
As per documentation, please use `PREVENT_SIGNUPS` environment variable instead. 

https://docs.flagsmith.com/deployment/locally-frontend#environment-variables
