### ISSUE TITLE
Return tags in /my-permission

### ISSUE THREAD

**Issue by kyle-ssg** [SolidStateGroup/bullet-train-api#4813]
### Is your feature request related to a problem? Please describe.

Tag-based roles allow you to restrict permissions to certain tagged features, however, the frontend doesn't currently receive any information about what tags the user has permissions for in the my-permissions endpoint - this means the frontend isn't disabling / hiding any access where appropriate tags aren't added.

### Describe the solution you'd like.

In order for the frontend to start restricting tag based roles, the my-permissions endpoint needs to return the tags the permission has access to, if none are returned the frontend should assume they have access to permissions regardless of the tagged feature.

### Describe alternatives you've considered

Let the api 403 when attempting actions, however this would add many new scenarios to test where the frontend was originally hiding / disabling ui

**Comment by matthewelwell** [comment]
I guess we can just add an extra key, e.g. `"tag_based_permissions"` to the response object, like

```json
{
  "permissions": ["VIEW_ENVIRONMENT", "CREATE_CHANGE_REQUEST"],
  "admin": false,
  "tag_based_permissions": [{"key": "UPDATE_FEATURE_STATE", "tags": [1, 2]}]
}
```

**Comment by kyle-ssg** [comment]
This makes sense, I will update the frontend PR to use this

**Comment by gagantrivedi** [comment]
@kyle-ssg, I’ve implemented it [here](https://github.com/Flagsmith/flagsmith/pull/4824) with a slight variation. Instead of using 'keys,' I've used 'permissions' (a list) since it can contain more than one permission.

e.g:

```
{
  "permissions": ["VIEW_ENVIRONMENT", "CREATE_CHANGE_REQUEST"],
  "admin": false,
  "tag_based_permissions": [{"permissions":  ["UPDATE_FEATURE_STATE"] , "tags": [1, 2]}]
}
```
