### ISSUE TITLE
Edit Role screen should have context of the role you're editing

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#4894]
For example, here

![Image](https://github.com/user-attachments/assets/651a5378-2c5a-4df1-bb34-7020281e27de)

I cannot see which role I'm editing the members of. In order to confirm which role I'm editing the members of, I need to switch back to the 'General' tab.

**Comment by matthewelwell** [comment]
I have a feeling this is a general issue with our 'edit' slide-out modal. Perhaps we can resolve this in multiple places?

**Comment by Lucifer4255** [comment]
@matthewelwell Can you tell me how to reproduce the issue

**Comment by matthewelwell** [comment]
Hi @Lucifer4255 , hmm... since this feature is behind the paywall it might be a little bit difficult. I think you can probably at least view the page (perhaps not submit any data) though by running the FE and mocking out the response to the relevant endpoints (I think probably `/api/v1/organisations` and `/api/v1/organisations/:id/get-subscription-metadata` would be the endpoints that you need to look at.
