### ISSUE TITLE
Implement identity overrides for edge identities 

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#490]

**Comment by gagantrivedi** [comment]
Endpoint: `/environments/{environment_api_key}/edge-identities/{edge_identity_identity_uuid}/edge-featurestates/`

**Comment by dabeeeenster** [comment]
Need to include whether the Project is Dynamo powered and send that to the FE

**Comment by matthewelwell** [comment]
Dependent on #789 which is approved but not yet merged / deleted.

**Comment by kyle-ssg** [comment]
I need a bit more info here, not really sure what is actionable

**Comment by matthewelwell** [comment]
@kyle-ssg you should now see a new `"use_edge_identities"` attribute on the projects endpoint. If this is true, you should use the `/environments/:key/edge-identities/` endpoints instead of `/environments/:key/identities/`.

**Comment by kyle-ssg** [comment]
Could I get invited to a project that has this @dabeeeenster @matthewelwell

**Comment by kyle-ssg** [comment]
Is this the only change also? I think someone mentioned the trait-keys endpoint won't work for these projects? In which can I can hide this: 
![image](https://user-images.githubusercontent.com/8608314/162608335-5c1dd1e0-4968-47af-8992-13704cc8dc2d.png)

**Comment by kyle-ssg** [comment]
Live under the feature flag edge_identities
