### ISSUE TITLE
Update urls to use <identity_identifier> instead of <identity_id>

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#494]
Due to the changes introduced here: https://github.com/Flagsmith/flagsmith/pull/425 all the urls that points to identity view set using id 
needs to be updated to use identifier
e.g: 
from  `/environments/{environment_api_key}/identities/{id}/`
to: `/environments/{environment_api_key}/identities/{identifier}/` 
for reference checkout: `api/v1/docs/`

**Comment by kyle-ssg** [comment]
Are we going to have to synchronise releasing this with FE and BE? Is this on staging?

**Comment by gagantrivedi** [comment]
Closing this since this since we are not updating the existing viewset
