### ISSUE TITLE
Split API usage by Project and Environment

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#515]
In the Organisation settings area you can see your usage. We are now storing both project and environment data with api calls. 

We should add a UI element to allow customers to see how their usage breaks down based on project and environment, with drop downs for each? 

We can then also add a Usage tab to both the Project and Environment settings pages with the appropriate filters set. 

This would require both API and frontend work.

**Comment by khareyash05** [comment]
I would like to work on this one

**Comment by dabeeeenster** [comment]
Hey @khareyash05 that would be awesome - this is a pretty complex PR tho that spans InfluxDB data stores - do you want to join our Discord to chat about it? https://discord.gg/hFhxNtXzgm

**Comment by kyle-ssg** [comment]
@dabeeeenster I think it would be worth reprioritising this since the issue is quite stale. Then assigning to frontend todo if / when API becomes available

**Comment by ibrahimbroachwala** [comment]
We need this!

**Comment by dabeeeenster** [comment]
@kyle-ssg this is imminently in the API so ready for the front end to be implemented.

**Comment by kyle-ssg** [comment]
Frontend is live, the filter for environments/projects is under the feature flag **usage_filter**

**Comment by dabeeeenster** [comment]
Needs api deployment @matthewelwell

**Comment by dabeeeenster** [comment]
You never see the total for ‘Identities’ requests
Then it definitely looks like the data being returned by the API is lower than it should be
Can you codify in a ticket somewhere?
Also switching back to ‘All projects’ without switching back to ‘All Environments’ doesn’t clear the environment filter (and hence returns no data)
