### ISSUE TITLE
Send new signups to mailerlite

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#565]
We need to ensure we're doing the relevant GDPR checks ahead of this. 

Documentation is [here](https://developers.mailerlite.com/reference/campaigns-by-type). There is also a python client [here](https://github.com/skoudoro/mailerlite-api-python) but it's probably a bit heavyweight for our needs, we can just write our own.

**Comment by matthewelwell** [comment]
@dabeeeenster can you flesh this out with any additional specifics we might need. Some questions off the top of my head: 

 * Should _all_ users be sent? Invited users and fresh signups?
 * Should / can we send any attributes?

**Comment by dabeeeenster** [comment]
OK so here:

![image](https://user-images.githubusercontent.com/173290/145240717-29646fcb-0b5d-45d1-8f4a-d689868f6b9e.png)

Add a pre-selected checkbox with "Join our mailing list! 1 email per month packed with engineering goodness"

Capture First name, last name and email. 

We would want the same to happen to SSO people but I realise that will be trickier.

**Comment by dabeeeenster** [comment]
Can we please pull all new users who sign up - directly to Mailerlite so we can provide an email onboarding

Variables we need to send to Mailerlite:

Email
First Name
Last Name
Is it a paid user or not

**Comment by matthewelwell** [comment]
Some uncertainties around the mailerlite integration: 

1. How does mailerlite handle sending the same email address (given we already have a load of emails already signed up manually). Can we just always use PUT? 
2. What does the `unconfirmed` status mean? 

Some general questions: 

1. How do we get consent for a user that authenticates with Google / Github?

**Comment by dabeeeenster** [comment]
Would be 99% sure answer to 1 is that the user is updated with any further meta data

**Comment by dabeeeenster** [comment]
We need to do a `POST` not a `PUT`. Their docs state: 'Adds a subscriber to an existing subscriber list, including custom field data if supplied. If the subscriber (email address) already exists, their name and any custom field values are updated with whatever is passed in.'

Lets ignore `unconfirmed` for now - just test with `POST` and see what happens - I would expect it to work and mark the account as active.

**Comment by matthewelwell** [comment]
So, essentially their `POST` behaves like a `PUT`...

**Comment by dabeeeenster** [comment]
yes but I'm not sure what `put` does with a new user. So use `post`

**Comment by gagantrivedi** [comment]
@dabeeeenster  @matthewelwell 
> Variables we need to send to Mailerlite:
Email
First Name
Last Name
Is it a paid user or not

How do we know the user is paid or not(at the sign up)?

**Comment by gagantrivedi** [comment]
Endpoint to create user now accepts `marketing_consent_given`(false by default) that will be used to store consent provided by the user.
ps:
![image](https://user-images.githubusercontent.com/18366226/148551259-944623cb-24e8-4417-a3a2-c43b2d9d1106.png)

**Comment by kyle-ssg** [comment]
Live under flag mailing_list
