### ISSUE TITLE
Cannot EDIT feature -- The feature edit flyout is closing automatically 

### ISSUE THREAD

**Issue by badaljain77** [SolidStateGroup/bullet-train-api#571]
Hi all,

I am using flagsmith in a self hosted kubernetes environment. When i try to edit the feature in the flagsmith frontend, the flyout opens for a couple of seconds and then closes automatically with error: 
![image](https://user-images.githubusercontent.com/90994359/145335848-4b1946e7-c45b-402a-a5f5-a3c1de661595.png)

Please help, I am not able to edit the flag

**Comment by badaljain77** [comment]
This is the error in the console:
`breadcrumbs.ts:224 GET http://flagsmith-frontend.flagsmith:8080/api/v1/projects/1/features/1/influx-data/?period=24h&environment_id=1 500 (Internal Server Error)
(anonymous) @ breadcrumbs.ts:224
_request @ _data.js:99
get @ _data.js:35
getInfluxDate @ feature-list-store.js:83
(anonymous) @ feature-list-store.js:202
(anonymous) @ main.js:58
(anonymous) @ main.js:107
dispatch @ main.js:103
handleViewAction @ dispatcher.js:16
getFlagInfluxData @ app-actions.js:156
(anonymous) @ CreateFlag.js:90
(anonymous) @ CreateFlag.js:64
di @ react-dom.production.min.js:213
fi @ react-dom.production.min.js:205
Ra @ react-dom.production.min.js:200
vi @ react-dom.production.min.js:218
bi @ react-dom.production.min.js:218
Oi.render @ react-dom.production.min.js:227
(anonymous) @ react-dom.production.min.js:230
_i @ react-dom.production.min.js:216
ki @ react-dom.production.min.js:230
render @ react-dom.production.min.js:232
exports.openModal @ modals.js:190
(anonymous) @ FeaturesPage.js:79
onClick @ FeaturesPage.js:273
(anonymous) @ react-dom.production.min.js:14
d @ react-dom.production.min.js:15
(anonymous) @ react-dom.production.min.js:15
P @ react-dom.production.min.js:17
S @ react-dom.production.min.js:18
j @ react-dom.production.min.js:18
x @ react-dom.production.min.js:18
I @ react-dom.production.min.js:21
On @ react-dom.production.min.js:84
mi @ react-dom.production.min.js:216
Fe @ react-dom.production.min.js:39
Sn @ react-dom.production.min.js:86
yi @ react-dom.production.min.js:216
Cn @ react-dom.production.min.js:85
a @ helpers.ts:77
Show 10 more frames
react-dom.production.min.js:13 Uncaught (in promise) Invariant Violation: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:1333426
    at i (http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:1333529)
    at http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:1357133
    at rn (http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:1357464)
    at Object.findDOMNode (http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:1423655)
    at http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:694733
    at Object.onError (http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:2321940)
    at Object.<anonymous> (http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:1528062)
    at Object.s.emit (http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:349668)
    at Object.trigger (http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:27271)
    at Object.goneABitWest (http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:27806)
    at http://flagsmith-frontend.flagsmith:8080/static/main.65702c40ac543a5118e9.js:2:1428280`

**Comment by dabeeeenster** [comment]
This is failing as you have not configured/set up the InfluxDB datasource. You need to either set up Influx or disable it with the env var `ENABLE_INFLUXDB_FEATURES` - check the docs here https://docs.flagsmith.com/deployment/locally-frontend

**Comment by badaljain77** [comment]
so basically enable the persistance here?
https://github.com/Flagsmith/flagsmith-charts/blob/main/charts/flagsmith/values.yaml#L160

**Comment by dabeeeenster** [comment]
Can you provide more info about your setup? Are you running with InfluxDB enabled?

**Comment by badaljain77** [comment]
yes, I am using the above helm chart and running in a kubernetes cluster.. The influxdb seems to be enabled by default in the values from the yaml file: https://github.com/Flagsmith/flagsmith-charts/blob/main/charts/flagsmith/values.yaml#L150

Below are the pods and the services created as a result of the helm chart installation
![image](https://user-images.githubusercontent.com/90994359/145509434-ba049413-adb8-47f6-897e-ed33b7142963.png)

Please let me know if this issue can be opened again.

**Comment by badaljain77** [comment]
Hi @gagantrivedi @dabeeeenster,

Is there any update on this issue? or any suggested workaround?

**Comment by gagantrivedi** [comment]
Hi @badaljain77  we are looking into it - in the meatime you can run it with influx db disabled.
the command will look something like this:
`helm install <release_name> flagsmith/flagsmith --set influxdb2.enabled=false`
