### ISSUE TITLE
Protected flag tags feature is not findable

### ISSUE THREAD

**Issue by alexeboswell** [SolidStateGroup/bullet-train-api#576]
There is no way to find out about the tags that protect a flag (Protected, Permanent, Do Not Delete, Read Only). The only way to use this feature right now would be to have someone show it to you. 

There should be some explanation that would lead someone to add one of those tags. Or they could be automatically created (but this could add clutter)

My suggestion is that it is a toggle like Archived is in the settings. Something like that, doesn't really matter as long as it informs users of the feature.

**Comment by kyle-ssg** [comment]
Would require backend, hence why the feature is what it is right now. Assigning back can prioritise then assign back if we want something persisted.
