### ISSUE TITLE
Allow for non environment admin users to control environment / identity feature states

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#578]
At the moment, the permission to control feature states in a given environment and for any identities in that environment is restricted to environment admins. We need to extend that to allow users to control feature states in a given environment without being an admin of that environment.

**Comment by matthewelwell** [comment]
API work is done in #579. There will be FE work required to enable the toggles and value edit functionality if a user has this permission.

**Comment by matthewelwell** [comment]
@kyle-ssg the permission is called `UPDATE_FEATURE_STATE`

**Comment by kyle-ssg** [comment]
This is live under the flag "update_feature_state_permission", backend is on staging for QA

**Comment by matthewelwell** [comment]
Looks good to me.

**Comment by dabeeeenster** [comment]
Needs merging into EE branch @matthewelwell

**Comment by kyle-ssg** [comment]
Looks like ee did get this merged here https://github.com/Flagsmith/flagsmith-ee/commit/a6aedfb4e295cd92abebd7b3e8c98543349805de
