### ISSUE TITLE
Update "user register" event on Heap

### ISSUE THREAD

**Issue by ilyaazovtsev** [SolidStateGroup/bullet-train-api#590]
We have the event "user register" on Heap and it works only when people sign up through form (not Google or Github oAuth)

Could we pls update this event when people also sign up through  Google or Github 
<img width="813" alt="Screenshot 2021-12-14 at 12 37 03" src="https://user-images.githubusercontent.com/95770248/145982362-f5bdd505-a1b5-4a7f-a1de-c280756f3b3d.png">

**Comment by kyle-ssg** [comment]
@gagantrivedi I think the best approach for this is to return an isNewUser boolean from auth/oauth/:type so that the API doesn't need to worry about all the analytics integrations.

Assign back to me when we have something like this
