### ISSUE TITLE
SPF record for flagsmith.com

### ISSUE THREAD

**Issue by ilyaazovtsev** [SolidStateGroup/bullet-train-api#591]
We don't have the right SPF 
here is the 1 min guide how to fix it https://blog.lemlist.com/how-to-create-spf-record/#gmail-spf-setup-example
<img width="1130" alt="Screenshot 2021-12-14 at 17 19 48" src="https://user-images.githubusercontent.com/95770248/146026520-6b7a5e9c-021e-4dc6-bc3a-a18a8e53be74.png">

**Comment by dabeeeenster** [comment]
Implemented for Mailerlite
