### ISSUE TITLE
Safari not showing the github link on homepage...

### ISSUE THREAD

**Issue by malthauser** [SolidStateGroup/bullet-train-api#596]
Github logo next to Sign In button in upper right isn't showing up...

![Screen Shot 2021-12-15 at 2 47 53 PM](https://user-images.githubusercontent.com/661018/146198215-7f7ceda8-fc74-4a76-8aaa-1306cdab845e.png)

here is my version:

![Screen Shot 2021-12-15 at 2 48 20 PM](https://user-images.githubusercontent.com/661018/146198241-30a623e5-b090-4389-9eb4-dcd0b22c6e95.png)

**Comment by kyle-ssg** [comment]
I believe this is now fixed after editing the SVG

![image](https://user-images.githubusercontent.com/8608314/160457499-a42cee89-3ba9-45c0-a170-ecc613b95daa.png)
