### ISSUE TITLE
Custom Domain for Mailerlite

### ISSUE THREAD

**Issue by ilyaazovtsev** [SolidStateGroup/bullet-train-api#599]
Can we please create the custom tracking domain for Mailerlite 

that’s a simple CNAME record, so all our tracked links in our newsletters will have “email.flagsmith.com/….” domain and NOT mailerlite’s one 

email.flagsmith.com

A record 35.198.93.67 
MX record mx.mlsrv.io
TXT record v=spf1 a mx include:_spf.mlsend.com ?all

<img width="646" alt="Screenshot 2021-12-15 at 19 11 31" src="https://user-images.githubusercontent.com/95770248/146232740-27c6cebb-1207-4e2f-8b17-bcca6481a6a9.png">

**Comment by dabeeeenster** [comment]
Done
