### ISSUE TITLE
Design and implement v2 of python SDK

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#600]

**Comment by matthewelwell** [comment]
As part of this work, I am adding the new server side API keys. I'd like to air some thoughts here about the design of these. 

## Implementation options

### Option 1 - Add a new field to the Environment model

Pros - easy! 
Cons - increases tech debt, will mean that after the query to get an environment from it's key we'll need to check which key it matched on to determine the _type_ of key it was, unable to create multiple api keys, deactivate them, etc., requires a new index adding to the edge API dynamo documents and some updates to the query to retrieve an environment

### Option 2 - Add a new model to hold server side api keys only

Pros - makes a start tackling the technical debt, able to handle multiple server side API keys for a single environment, no real change required on the FE
Cons - slight split brain issue, would mean (up to) 2 DB queries to get an environment when making a request from an SDK, requires substantial changes to the dynamo documents / edge API 

### Option 3 - Add a new model to hold both client and server side api keys and keep a client api key up to date with the env copy

This option would essentially be the full solution but we would prevent the FE from viewing the client side API keys when viewing all API keys and just maintain the current norm of the single API key against the environment. We would then make sure the key against the environment was synchronised with the default we will create in the new model table. 

Pros - makes a good leap on tackling tech debt, able to handle multiple server side API keys for a single environment, means we would only need a single query still to grab an environment when making a request from the SDK
Cons - adds a separate piece of tech debt which should be removed in the future, keeping the 2 api keys in sync may be painful, requires substantial changes to the dynamo documents / edge API

### Option 4 - Add a new model to hold both client and server side api keys and migrate from environment model field

Pros - gets us the whole way to a nice clean api key solution for environments, able to handle multiple server side API keys for a single environment, means we would only need a single query still to grab an environment when making a request from the SDK
Cons - a lot of work, would likely need to look at updating all the URLs on all the environment and nested viewsets (or maybe we could just maintain the existing api_key for now (but update it's name in the python code at least), requires substantial changes to the dynamo documents / edge API

---

I guess some key things we need to understand before we can make a decision here: 
 1. How important is it for our users to be able to manage multiple API keys and activate / deactivate / expire them
 2. How much effort is required on the edge API / dynamo DB side for each of the options (really just option 1 vs option 2 vs the rest as 3 & 4 amount to the same thing)

I think my preference would be either option 2 or 3 for now.

**Comment by dabeeeenster** [comment]
I think we have to be able to create multiple server-side sdk keys - given it is now transmitting sensitive data there's a natural need to create many, and be able to rotate keys, so for that reason I think #1 is out. 

I dont see that option 3 gets us that much more in terms of end functionality than option 2.

I don't think there's much reason to need to rotate client side keys given the are effectively public - there's possibly an argument that they should be immutable. 

For that reason I vote for option 2.

**Comment by matthewelwell** [comment]
Just thinking about this, I'm not sure how we'd handle multiple server side keys on the dynamo db side. The only way I can see it working is if we remodel / extend the dynamodb structure a little. I think we'd need a new table to hold the server api keys, mapped to an environment key so we can _then_ look it up in the environments table 🤔

I guess our options are: 

 1. Go with the above
 2. Just allow a single server side API key per environment and add a secondary index on that
 3. Any other ideas?

**Comment by dabeeeenster** [comment]
yep - have a third table in DDB that had the ENV keys and associated data. i think in terms of medium long term that would be needed regardless. 

There are many reasons why for security people would want to rotate out keys. Also we have had the requirement of multiple API keys associated with different permissions (particular tags of flags) come up and a third table would solve that.

**Comment by dabeeeenster** [comment]
There are many reasons why for security people would want to rotate out keys etc

**Comment by dabeeeenster** [comment]
Also we have had the requirement of multiple API keys associated with different permissions (particular tags of flags) come up and a third table would solve that

**Comment by dabeeeenster** [comment]
Implemented in https://github.com/Flagsmith/flagsmith-python-client/pull/16
