### ISSUE TITLE
Set up a Free Trial mechanism

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#604]
New accounts should have access to Scale Up features for the first 14 days of their organisation's account.

**Comment by matthewelwell** [comment]
Can't this just be handled in Chargebee?

**Comment by dabeeeenster** [comment]
This would mean all new customers going thru the CB flow. So I don't think so. We could store the Org created data and use that to drive a segment?

**Comment by matthewelwell** [comment]
Hmm... I don't see how we'd make that time limited? 

We could probably just create a subscription object for each organisation on signup that's not linked to CB but set the expiry date. We could have our own plan id for 'free-trial' or something. Don't think it would be too difficult.

**Comment by dabeeeenster** [comment]
yep ok that sounds good - then drive a segment from that?

**Comment by matthewelwell** [comment]
I don't know that we should be using segments for this should we? Maybe we should. I don't quite know how you'd make sure that every user from an org with a valid subscription would be in the segment. And only in the segment for a given time period.

**Comment by kyle-ssg** [comment]
I don't think this should be based on segments, the frontend can just detect free-trial expiry in the plan logic.

I guess adding a free trial plan might be quite good, but not too fussed from a frontend perspective. Maybe it's easier from an administrative perspective though?

**Comment by dabeeeenster** [comment]
Yes agree lets go with the explicit chargebee subscription status

**Comment by kyle-ssg** [comment]
I'll need the Chargebee subscription type/trial status before I can action this, assign this to me after we start on that.

**Comment by matthewelwell** [comment]
Related: https://www.notion.so/API-Usage-Staging-Plan-67f96d64b94d45a58060769870289b44?d=ea0ac68bca3d444981274c83c638ff9c&pvs=4#55123e5cdfc24c718c938997d1424451
