### ISSUE TITLE
Problem with Trait and Segment

### ISSUE THREAD

**Issue by leon-developer-br** [SolidStateGroup/bullet-train-api#621]
Hi,

I have an user with trait_id = distributor_id = 2557.

![image](https://user-images.githubusercontent.com/29382718/146820042-7821efd6-791d-4539-8725-d2ecf6136e86.png)

I created a segment call franquias and included a trait with distributor_id contains 2557 but my user is not included in the group.

![image](https://user-images.githubusercontent.com/29382718/146819962-9a8fad86-b123-4660-b664-811b890f1523.png)

Can you help me understand what is the problem?

**Comment by dabeeeenster** [comment]
hey @leon-developer-br  - this is probably because the trait is being cast as a number and you're applying a string rule.

**Comment by leon-developer-br** [comment]
Hi @dabeeeenster I tried puting some quotes but my test continue failiing.

**Comment by dabeeeenster** [comment]
Have you tried using `=`?

**Comment by leon-developer-br** [comment]
Yes

**Comment by dabeeeenster** [comment]
If I have a trait for a user like this:

![image](https://user-images.githubusercontent.com/173290/146944227-f28cb5ee-4db8-4cc2-8be1-566dadbd772f.png)

You can check it's a number type by clicking on the trait and looking at the json:

![image](https://user-images.githubusercontent.com/173290/146944278-b0a44a29-d420-4475-853f-f3c123de081b.png)

Then I create a segment with the following:

![image](https://user-images.githubusercontent.com/173290/146944305-f851bfac-6c58-43b7-a489-a08bf9f88448.png)


The user is a member of that segment. Can you reproduce this?
