### ISSUE TITLE
Disable user invitation for free users

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#630]
Whenever someone wants to invite new users to the team:

![image](https://user-images.githubusercontent.com/173290/147133758-241bfe21-723c-4b61-9dbe-d7428943aaa6.png)

we should show the popup 

"You can add more teammates to your team on paid plans, pls upgrade to enjoy Feature Flagging with the team ❤️ (+ add the link to "billing page")"

**Comment by kyle-ssg** [comment]
Depends on https://github.com/Flagsmith/flagsmith/issues/646

**Comment by kyle-ssg** [comment]
I think inst

**Comment by kyle-ssg** [comment]
I could be wrong, but originally I thought this was on prem detection but you might of told me this was SaaS? If so, I think this is done and can be closed since we did it as part of auto seats @dabeeeenster ?

**Comment by dabeeeenster** [comment]
Yeah this is saas only. Current info here is fine but found another bug raised in #1969
