### ISSUE TITLE
Show users their pricing plan & limits

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#631]
We should show our users that they are API call limited. Get the total API calls made in the last 30 days for the organisation (as per the Org usage graph) and show it in the top banner if the calls are within 30% of the limit, so:

"45k out of 50k API calls" with a CTA to upgrade

pls it should be different from other buttons

![image](https://user-images.githubusercontent.com/173290/147133839-e8a7de31-569c-4178-a90e-896519f90859.png)

**Comment by kyle-ssg** [comment]
Can we get better requirements on this ticket @dabeeeenster

**Comment by dabeeeenster** [comment]
We need to hard code the API call limits for each chargebee `plan-id` into the back end, and then present that info to the Front end so it can make the appropriate calculations.
