### ISSUE TITLE
Disable creating new projects for free users

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#632]
Once people create on "create new project" we show them a popup: 

"You can create multiple projects on paid plan only. Please upgrade (+ add the link to "billing page")

![image](https://user-images.githubusercontent.com/173290/147133925-7fe4ea11-72b1-42c3-b83c-5658d3f2ceb0.png)

**Comment by kyle-ssg** [comment]
@dabeeeenster As discussed we should come up with a good way of distinguishing ee from self hosted / saas and treating their plan as enterprise. I'm a bit unsure of how we want to go about this but the options could be

- have an env var that gets passed to the frontend to determine ee
- have organisation plans be forced to enterprise on the backend for ee docker builds (this seems the best to me)
- use the baked in feature flags to determine ee

**Comment by kyle-ssg** [comment]
Depends on https://github.com/Flagsmith/flagsmith/issues/646
