### ISSUE TITLE
Edge API Migration

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#677]
### SDK v2

All SDKs will point to edge.api.flagsmith.com by default. We then need to do some coordination around when we release them. Basically release the v2 SDKs when all the edge stuff below is done and in place. 

### For New Customers

Default to write all identities and environments to DynamoDB from the outset. 

### For Existing Customers

Write a Lambda that copies Identities from Core to Edge API

Create a new button in the Project level settings page that triggers a copy of all their Identity data from Core API to Edge API using above Lambda.

Don't let the user press the button again. 

### Dealing with requests to Core API when they have been migrated to Edge

Have a period of time (***3 months?***) where we copy all Core API Identity writes through to the Edge API. This will be the time that customers can redirect their apps to edge

**Comment by matthewelwell** [comment]
## Tasks

|Task|Status|
|---|---|
|Write migrator to migrate all a project's identities (#788)|In Progress|
|Write code to migrate individual identities to dynamo on requests to /identities (and /traits?) if migration has been completed (#787)|Done|
|Add button to private admin dashboard to allow users to migrate a project's identities to dynamo|For Review|
|Add button to public app dashboard to allow users to migrate a project's identities to dynamo|Not started|
|Update project metadata to handle in progress migrations so we can disable buttons|For Review|
|Expose information about migration status to FE (#789)|Done|
|Document process for both existing and new customers|Not started|

**Comment by matthewelwell** [comment]
@gagantrivedi working on items 3 & 4 in list above today. These involve changing project metadata structure. Once this is done, we can look at migrating larger clients.
