### ISSUE TITLE
Build v2 API for common customer use cases

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#697]
Some examples:

- Request flags for environment. Shows core flag info, tags, overrides

**Comment by kyle-ssg** [comment]
Since this isn't in any milestone attached to this, I think we should close and mark this as stale. We'd need to plan and design many things here, I'd suggest we'd probably start opening tickets per endpoint.

**Comment by dabeeeenster** [comment]
Agreed
