### ISSUE TITLE
Improve UI when going from regular flag value to MV value

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#699]
It's confusing to users when going from a regular flag value to an MV flag value variate. We need to be clear that the values jump from being Environment based to being Project based as it is not really clear from the UI that this is the case.

**Comment by dabeeeenster** [comment]
When adding the first variation to a flag, include the following admonition underneath the "Variations" sub heading:

> Variation *values* are shared amongst environments. Variation *weights* are specific to this Environment. [Check the Docs for more](https://docs.flagsmith.com/basic-features/managing-features#multi-variate-flags).

This admonition should also remain persistent in the modal if there are any multivariate values defined. 

Admonitions being like this: https://docusaurus.io/docs/markdown-features/admonitions not sure we have that as a UI element yet?

**Comment by kyle-ssg** [comment]
Added

![image](https://user-images.githubusercontent.com/8608314/163031932-4690862a-9c39-432a-91c1-403e20a269be.png)

![image](https://user-images.githubusercontent.com/8608314/163031961-912e3b29-9ad5-461f-a125-a060f789225d.png)

**Comment by kyle-ssg** [comment]
Noticed that tooltips arent right on dark from this

Adjusted: 

![image](https://user-images.githubusercontent.com/8608314/163032132-3ebc9280-c5a6-442d-95fe-c13c47744a80.png)
