### ISSUE TITLE
UI is not using `UPDATE_FEATURE_STATE` permission to allow feature state changes

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#704]
UI should allow user to change feature states if user have `UPDATE_FEATURE_STATE` permission. 

![image](https://user-images.githubusercontent.com/18366226/150751782-e4f5a8c2-1aa9-4d9b-9f9c-4062c2e9ebb1.png)

**Comment by kyle-ssg** [comment]
It's actually live under a flag as referenced here https://github.com/Flagsmith/flagsmith/issues/578
