### ISSUE TITLE
Allow control over methods of authentication

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#707]
As a system administrator, I would like to be able to choose which methods people use to log in to the Flagsmith dashboard. 

Suggest an env var with a list of values, defaulting to:

`LOGIN_METHODS=userpass,github,google,saml,ldap`

This variable should be definable on both the front end and the back end.

**Comment by matthewelwell** [comment]
This is done now, right? @dabeeeenster @gagantrivedi ?
