### ISSUE TITLE
Rework tag filtering

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#719]
The tag filtering should work opposite to how it currently does. 

The initial state should be:

- All flags are shown for the environmnt
- All the tags are deselected

When selecting a tag to filter on, only show Flags with that tag. 

When selecting more than one tag, e.g if tagA, tagB and tagC are selected, show all flags with tagA OR tagB OR tagC

**Comment by kyle-ssg** [comment]
I agree with the above except removing the untagged filter, you still need a way of showing / hiding flags that aren't tagged.
