### ISSUE TITLE
Implement API tokens front end

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#723]
Need FE to complement https://github.com/Flagsmith/flagsmith/pull/681

## Overview

The new Server Side SDKs will be able to request the entire Environment document from our API - which will contain all flags, segment rules, overrides etc. etc. Consequently we are securing these endpoint with a token. This issue provides the front end for the functionality. 

## Requirements

For each Environment, allow users who have Admin privileges for the Environment to Create and Delete "Server Side API tokens".

The Environment will also show these Tokens to users with Read permission on the Environment.

## Copy

Create a new Sub Heading above Manage Permissions in the Environment settings Page titled "Server Side SDK Keys". Below that add the copy:

> Flags can be evaluated locally within your own Server environments using our [Server Side SDKs](https://docs.flagsmith.com/clients/overview). These SDKs need to be initialised with a Server Side SDK Key. You can manage these keys below

Add a "Create Server Side SDK Key" button. 

For each Key that exists, add a "Remove Key" with a confirmation dialogue.

**Comment by matthewelwell** [comment]
Endpoints are at: 

```
/environments/{environment_api_key}/api-keys/
/environments/{environment_api_key}/api-keys/{id}
```

**Comment by kyle-ssg** [comment]
Will be live under the flag **serverside_sdk_keys**

**Comment by dabeeeenster** [comment]
Needs additional UI elements

![image](https://user-images.githubusercontent.com/173290/153202910-1058dca9-b35c-435c-9e22-51d7f3ef4602.png)

**Comment by kyle-ssg** [comment]
![image](https://user-images.githubusercontent.com/8608314/153264430-5c926c0d-fee5-4cb9-a7f9-0ec112c28178.png)
