### ISSUE TITLE
Edge API responding with 502

### ISSUE THREAD

**Issue by balintkissshapr3d** [SolidStateGroup/bullet-train-api#736]
We are using the new edge API for a while now, everything worked. Today I deleted some unused flags from the dashboard and suddenly every request started to return 502. ( these 2 things might not be related but the timeline was very close )

The curl export of the browser request that returning 502:
`curl 'https://edge.api.flagsmith.com/api/v1/identities/?identifier=e7c31ec5-ddb1-43ac-9619-52274ca4a499' \
  -H 'authority: edge.api.flagsmith.com' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"' \
  -H 'x-environment-key: thisismaskedforprivacy' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Mobile Safari/537.36' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'accept: /' \
  -H 'origin: https://www.shapr3d.com/' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://www.shapr3d.com/' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  --compressed`

I am testing in Mac using Chrome browser but based on our alerting it happening to lots of different users too

**Comment by dabeeeenster** [comment]
Fixed with latest release
