### ISSUE TITLE
Unable to create split only segment

### ISSUE THREAD

**Issue by gerwim** [SolidStateGroup/bullet-train-api#764]
**Issue** 
When running flagsmith with the latest Docker image, the segment validation is not working correctly when creating a split only segment (see https://docs.flagsmith.com/guides-and-examples/staged-feature-rollouts#creating-staged-rollouts). The "create segment" button is disabled, because the trait value is not set (which is not possible either):
<img width="757" alt="image" src="https://user-images.githubusercontent.com/1841721/153375136-35292eb6-ff74-40ee-9709-06864ad34da6.png">

**Workaround**:
inspect HTML and remove `disabled` attribute from save button.

**Cause**
I think the regression is caused in: https://github.com/Flagsmith/flagsmith/pull/760

**Comment by dabeeeenster** [comment]
Ah this looks like it's a regression due to https://github.com/Flagsmith/flagsmith/pull/760

**Comment by dabeeeenster** [comment]
@gerwim thanks for the report - we will get on it!

If this is breaking things for you I'd advise dropping out of `latest` onto the most recent tag

**Comment by gerwim** [comment]
@dabeeeenster
> If this is breaking things for you I'd advise dropping out of latest onto the most recent tag

Will do! :)

**Comment by kyle-ssg** [comment]
Thanks for raising this so quickly, PR incoming!

Edit: This is built to docker latest now :)
