### ISSUE TITLE
Add an option to hide reset password button

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#768]
For self hosted installations using LDAP, the username / password inputs are hijacked for doing the LDAP authentication. This means that the reset password button is unnecessary so we should have an option to remove it. 

This may well be something that we can tie in with #707 since, if LDAP is enabled, then the reset password button really makes no sense.

**Comment by matthewelwell** [comment]
@kyle-ssg we should discuss this and #707 to determine where the responsibility for this work lies (FE or BE).

**Comment by kyle-ssg** [comment]
I think we can just add an env var for this, will take a look
