### ISSUE TITLE
UI typo in segment overriden variation

### ISSUE THREAD

**Issue by TD-4242** [SolidStateGroup/bullet-train-api#777]
![image](https://user-images.githubusercontent.com/3487671/153626718-7ac69f1b-ca78-4d30-bf4f-fe10972bb951.png)

Says this feature is being overriden by a % variation when it is actually a segment override.

**Comment by dabeeeenster** [comment]
Thanks!

**Comment by kyle-ssg** [comment]
Technically it still is a % variation since it's on an MV flag, I'd have no way of knowing if this value is being served due to a segment without backend. Up to you how you want to prioritise @dabeeeenster

**Comment by dabeeeenster** [comment]
yes agreed - closing
