### ISSUE TITLE
Use Postgres to store Influx Flag Analytics and API traffic data

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#780]
Main concern is around how we would do the downsampling in Postgres.

**Comment by matthewelwell** [comment]
We're currently in the middle of a 4 hour long outage on Influx cloud on which, we have no support from Influx and their status page is showing all green. We should, in my opinion, prioritise this work to avoid issues like this in the future as we're currently losing API request data.

**Comment by gagantrivedi** [comment]
Implemented here: https://github.com/Flagsmith/flagsmith/pull/1849

@kyle-ssg you can find the API changes in the above PR description
