### ISSUE TITLE
Upsert identities in DynamoDB on requests to /identities and /traits

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#787]
When we create or update an identity in postgres based on a request to /identities or /traits we should upsert that identity in DynamoDB. We have a couple of options for doing this: 

 1. Trigger the ECS task with a single identity (probably not advisable)
 2. Make the calls to DynamoDB manually
 3. Trigger an HTTP request to the Edge API (current favourite)

**Comment by dabeeeenster** [comment]
Should the start of this issue not read "When we create or update an identity in Postgres" @matthewelwell ?

**Comment by matthewelwell** [comment]
> Should the start of this issue not read "When we create or update an identity in Postgres" @matthewelwell ?

Yes. Updated now.
