### ISSUE TITLE
Build logic to determine which identities endpoints should be used for management

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#789]
This issue covers 2 things: 

 1. The API needs to expose some information to the FE so that it knows whether it should use the regular endpoints or the dynamo backed endpoints for managing identities in environments within a given project
 2. The FE needs to use this information to hit the correct endpoints

The solution to point 1 has a couple of options: 

 1. We add a flag to the current GET /projects/:id endpoint
 2. We add a new detail endpoint to the ProjectViewSet

The benefit of option 1 is that it will be easier for the FE to integrate with but it comes with the slight downside that we have to make a call to postgres _and_ dynamo to retrieve the information whenever a call is made to that endpoint. 

The benefit of option 2 is that we only make the call to dynamo when it's really needed but it is more work for the FE to integrate with. 

I suggest we go with option 1 for simplicity.

**Comment by gagantrivedi** [comment]
Yep, I agree, option 1 makes more sense since get Item from DynamoDB is pretty fast.
