### ISSUE TITLE
Privacy concern

### ISSUE THREAD

**Issue by ss-o** [SolidStateGroup/bullet-train-api#815]
Hi, 

I am getting multiple reports about emails meant to be sent to me. Could you please check your service and get this fixed?

The following person received twice as seen in the picture below.

Thanks,

![Screenshot_2022-02-24-19-52-28-367_com google android gm](https://user-images.githubusercontent.com/59910950/155585165-2fd0bf00-dbea-4e33-b48b-6f70b01720ae.jpg)

**Comment by dabeeeenster** [comment]
Hi @ss-o  - I only sent these out to folk who had starred our repo. We'll add you to our 'do not contact' list right now. 

Thanks for the feedback.
