### ISSUE TITLE
Allow '+' in invite email addresses

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#820]
We allow them in signups.

**Comment by kyle-ssg** [comment]
![image](https://user-images.githubusercontent.com/8608314/159893336-bb667f9e-4f2f-47eb-b753-b4c7795b7111.png)

It seems to work fine and uses same validation function?

**Comment by dabeeeenster** [comment]
Customer reported but unable to reproduce
