### ISSUE TITLE
Allow for weighting splits on Segment override Multivariate options

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#837]
For multi-variate flags, where a Segment override is defined, we currently provide radio buttons to decide on which variation the segment override receives:

![image](https://user-images.githubusercontent.com/173290/156789699-f57de1d4-f7aa-43e6-ad8f-d25ab839a64d.png)

There are testing uses cases where it would be better to provide weighting % splits. For example:

> There are some new features that we would love to test only on our new users before rolling out to everyone. If you have an idea of how we can even workaround it that would be great

The API already supports this - the radio buttons are a convenience for the front end. 

It would be good to have an option in the UI to select whether you want radio buttons or % split values for each variation.

**Comment by idoshamun** [comment]
Can't wait 😀

**Comment by matthewelwell** [comment]
This will require some API work before the FE can achieve this. We'll need to create default multivariate feature state value objects for segment override feature states.

**Comment by dabeeeenster** [comment]
Depends on #884

**Comment by kyle-ssg** [comment]
I'm sure we discussed as part of allowing this to work that segment featurestates would contain matching mv values with the environment @matthewelwell? Without that, I'm not sure how this can be achieved.

![image](https://user-images.githubusercontent.com/8608314/170796760-833e7728-c7de-43de-a8c9-fa35b8861c21.png)

**Comment by kyle-ssg** [comment]
I'll have a think about whether this is feasible without that, I think that the mv-options endpoint does make this a bit more manageable. In the meantime, there's a few issues assigned to me that can go live under the segment_mv_percentages flag.

**Comment by kyle-ssg** [comment]
This is now live 🚀
