### ISSUE TITLE
Add Migrator Button and Badge to Dashboard

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#844]
We need to add a badge under the Project name showing whether the Identities for the project are being read/written to the Edge API or the Core API. 

Add the badge here:

![image](https://user-images.githubusercontent.com/173290/157028733-ebdca7b6-4613-49ca-aec2-8a2ea253c4d7.png)

We should also add a call to action next to the badge if the Project is still on the core API. The CTA should take people to a docs page that details migrating to the Edge API. URL to follow.

**Comment by gagantrivedi** [comment]
Should be based on `use_edge_identities` 
![image](https://user-images.githubusercontent.com/18366226/166912364-4d04e427-a941-4697-a48e-38dee66c486a.png)

**Comment by kyle-ssg** [comment]
This is live under the edge_identities flag

**Comment by kyle-ssg** [comment]
If we want to adjust the url just reopen
