### ISSUE TITLE
Implement Datadog App

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#855]
Datadog Apps:  It's currently in Beta - you can read more about them in the[ documentation](https://docs.datadoghq.com/developers/datadog_apps) and view our [keynote video ](https://www.youtube.com/watch?v=PvXAFkhcMoM&t=1913s)that shows off some app examples. Additionally, here's the [github repo](https://github.com/DataDog/apps) for Apps with additional Getting Started info, FAQs, etc. 

Marketplace: [Marketplace documentation](https://docs.datadoghq.com/developers/marketplace/) which gives you an overview of the development process for creating and publishing Flagsmith commercial tile on the Marketplace.

**Comment by kyle-ssg** [comment]
@dabeeeenster Unless this is different to what we've implemented I think this can be closed?

**Comment by dabeeeenster** [comment]
👍
