### ISSUE TITLE
Breaking changes included in minor version update

### ISSUE THREAD

**Issue by reschneebaum** [SolidStateGroup/bullet-train-api#863]
The latest minor version, 1.2.0, included **breaking**, non-backwards-compatible changes (specifically `TypeValue` changes). Breaking changes like this should always be introduced in a major version, not a minor version.

Reference: [semantic versioning](https://semver.org/#spec-item-8)

**More details**:
we integrate Flagmith via SPM, like so:
`.package(url: "https://github.com/Flagsmith/flagsmith-ios-client", .upToNextMajor(from: "1.1.2"))`

This should allow the project to stay up-to-date with bug fixes and backwards compatible changes, _without breaking anything_, until we're ready to update to the latest major and make any required changes.

Thank you!

**Comment by dabeeeenster** [comment]
Hi - thanks for the report @reschneebaum  - humble apologies - we thought this wasn't a breaking change 🙏

We have deployed v2.0.0 now.
