### ISSUE TITLE
Unable to remove environment

### ISSUE THREAD

**Issue by RadovanPelka** [SolidStateGroup/bullet-train-api#868]
FE api req timeout: 1min

**Comment by dabeeeenster** [comment]
Can you provide more info:

- Version of Flagsmith 
- Steps to reproduce
- `curl` command that produces error
- logging from API

**Comment by RadovanPelka** [comment]
Version of Flagsmith: latest
Steps to reproduce: 
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/29738200/159684623-79a1586b-895c-4c84-a89c-4258e917b8c4.png">
click the red icon
curl command that produces error: delete env method
logging from API: 

![image](https://user-images.githubusercontent.com/29738200/159684772-7d82e139-9ee8-4017-88f8-96d693c9246f.png)

**Comment by dabeeeenster** [comment]
Can you paste the entire curl command including the response? Thanks

**Comment by RadovanPelka** [comment]
<img width="183" alt="image" src="https://user-images.githubusercontent.com/29738200/159706394-bf95a122-7151-4dea-905b-07a50d5533fd.png">
<img width="272" alt="image" src="https://user-images.githubusercontent.com/29738200/159706420-429aa650-d9dd-4bd8-8562-3f7898716814.png">

**Comment by dabeeeenster** [comment]
@gagantrivedi are you able to take a look?

**Comment by gagantrivedi** [comment]
I am a little confused here.  @RadovanPelka  First, you are running this locally, right? Secondly, the traceback that you have posted is for `identities` endpoint and not for environment delete. Can you post the logs of environment delete as well?

**Comment by dabeeeenster** [comment]
Please reopen if this is still an issue
