### ISSUE TITLE
Add new endpoint to create a multivariate feature option

### ISSUE THREAD

**Issue by matthewelwell** [SolidStateGroup/bullet-train-api#884]
At the moment, the FE creates new MV feature options by passing nested data to the update feature endpoint. This causes the FE a problem when they need to create a new feature option and then update the value for a particular environment. 

If we have a specific endpoint for creating a new mv option then the FE can create a new option with a default percentage of 0 and then immediately (using the returned id value) update the percentage allocation in the environment they are currently working in.

**Comment by gagantrivedi** [comment]
Sorry, I don't think I understand this - Are we creating this endpoint because:
![image](https://user-images.githubusercontent.com/18366226/165438190-859bac1d-1782-41ef-b154-8fec5ea97666.png)

i.e: we want to create variation values that are not shared? 
@dabeeeenster @matthewelwell

**Comment by matthewelwell** [comment]
@kyle-ssg the BE is done for this now (and deployed to staging). There are new endpoints at `/api/v1/projects/:id/features/:id/mv-options` to allow you to manage mv options.

**Comment by matthewelwell** [comment]
The FE work for this is tracked under separate tickets: 

#837, #1016 & #1017
