### ISSUE TITLE
SemVer encoding [Front-end]

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#956]
Front-end needs to append ":semver" at the end of the SemVer values defined in a segment to differentiate SemVer from normal string values. 
e.g: a SemVer string that looks like → "1.2.3" is going to look like → "1.2.3:semver".
PS: the other method considered was to parse the string to see if it's a valid SemVer or not, but that operation turned out to be a little expensive, hence we decided to fall back to this.

**Comment by kyle-ssg** [comment]
As discussed we may end up adjusting the way this works by treating semver as new segment operators. Either way, a lot of the frontend is done for this as it's all via remote config (which I've added for the flagsmith segment) I just need to know what to send for these once it's been agreed.

**Comment by gagantrivedi** [comment]
I think it has been agreed that it will have a ":semver" suffix, right/ @matthewelwell @dabeeeenster

**Comment by dabeeeenster** [comment]
so it would look like:

`2.1.41-beta:semver` 

?

**Comment by gagantrivedi** [comment]
> so it would look like:
> 
> `2.1.41-beta:semver`
> 
> ?

yes

**Comment by dabeeeenster** [comment]
Fine here
