### ISSUE TITLE
Regular users can seemingly skip change requests

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#987]
**Could this be related to Organisation Plan? I am on a free plan for this test account in Prod**

Steps to reproduce:

- Set up an environment with 4 eyes approval, 1 approval required
- Environment admins have to create change requests when modifying values
- Users with only `Update feature state` and `View environment` permissions can modify the value as if the Env did not have 4 eyes enabled.

Also not seeing a "Change request" menu item for the lower level user

## Screenshots

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/173290/164228715-606547b6-c476-40c6-8236-e370a58e0422.png">

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/173290/164228726-b86eb361-902a-4998-aaf2-01d5e10eaa30.png">

![image](https://user-images.githubusercontent.com/173290/164228732-3d42af53-21e1-46d3-8ba7-6cd2fbd51728.png)

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/173290/164228742-b1fb9e21-4efd-4c5f-b8ec-587975c8b6fe.png">

**Comment by kyle-ssg** [comment]
I believe we found this was due to change requests feature flags being turned off for that user.
