### ISSUE TITLE
Replace drf_yasg2  with drf-spectacular

### ISSUE THREAD

**Issue by gagantrivedi** [SolidStateGroup/bullet-train-api#992]
Since drf_yasg2 is not being maintained anymore, we are left with two options:
1. Move back to drf_yasg, we can do that, but it does not support Openapi 3.0, so really we are left with one option to use https://github.com/tfranzel/drf-spectacular

**Comment by SD-13** [comment]
@gagantrivedi From a quick search it seems like this issue is resolved with this PR https://github.com/Flagsmith/flagsmith/pull/2369.

**Comment by matthewelwell** [comment]
Yes, thanks!
